### ISSUE TITLE
Support for PathBuf

### ISSUE THREAD

**Issue by vorner** [TeXitoi/structopt#10]
It is quite common to pass paths as command line arguments to programs and the correct type for them is probably `std::path::PathBuf`. It is, however, not supported by structopt, because it implements `From<&str>`, not `FromStr` (the conversion can't fail).

Would it be possible to implement support for `PathBuf`, or more generally, for anything that can be converted without an error?

**Comment by TeXitoi** [comment]
You want #2 and #3. So that's planned.

**Comment by vorner** [comment]
I'm not entirely sure. `OsString` is a different type (I guess it makes sense to implement it at the same time, but the issue talked specifically about `OsString` and I didn't feel like hijacking it). I'd not like to have a custom converter for something as common as a path to a file.

But OK, if it's planned, I don't really care in which issue O:-).

**Comment by TeXitoi** [comment]
I can't find of an automatic way to detect that we have a `From<&str>`. Thus it will need #3. Maybe some helpers can help to facilitate this case.

And for PathBuf, you really want the conversion from `OsString` because some valid file names can't be written using `&str`.
