### ISSUE TITLE
Support trailing comma for arg_enum!()

### ISSUE THREAD

**Issue by im-0** [TeXitoi/structopt#101]
This code fails to compile:

```rust
arg_enum! {
    #[derive(Debug)]
    enum OutputFormat {
        PrettyJSON,
        JSON,
    }
}
```

Error:

```
error: no rules expected the token `:`
  --> zicsv-tool/src/main.rs:43:1
   |
43 | / arg_enum! {
44 | |     #[derive(Debug)]
45 | |     enum OutputFormat {
46 | |         PrettyJSON,
47 | |         JSON,
48 | |     }
49 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

It seems that this was already fixed in `clap`: kbknapp/clap-rs#1097. But `structopt` currently depends on outdated version.

**Comment by TeXitoi** [comment]
just cargo update, it'll update your version of clap, and it will work.

**Comment by im-0** [comment]
Hmmm... While trying to compose minimal broken example, I realized that this is really not a `structopt` problem.

Symptoms are very weird: my example does not compile even with latest `clap`, but if I only change "enum" to "pub enum", everything starts working as expected.

**Comment by im-0** [comment]
So I'll try to investigate this a bit more. And most probably will reopen kbknapp/clap-rs#1097.

**Comment by TeXitoi** [comment]
OK, thanks for reporting.
