### ISSUE TITLE
How do I move main help message to the bottom?

### ISSUE THREAD

**Issue by vi** [TeXitoi/structopt#108]
By default it shows `description` from `Cargo.toml`. When I add docstring, it deplaces the description.

How do I show both, moving the docstring one to the bottom?

Cargo.toml: `description = "12345"`

main.rs: 

```rust
/// ABCDEF
/// GHI
#[derive(Debug, StructOpt)]
struct Opt {
}
```

I get:

```
$ cargo run -- --help
aus 0.1.0
Vitaly _Vi Shukela <vi0oss@gmail.com>
ABCDEF GHI

USAGE:
    aus

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
```

I want:

```
$ cargo run -- --help
aus 0.1.0
Vitaly _Vi Shukela <vi0oss@gmail.com>
12345

USAGE:
    aus

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ABCDEF
GHI
```

**Comment by vi** [comment]
Found myself a bit:

```
#[structopt(after_help = "
sdfasdf
123456
")]
```

Maybe it should be more documented?

**Comment by dcsobral** [comment]
I wish there was a way of doing with while using the rust docs.

**Comment by CreepySkeleton** [comment]
Maybe just add a file in `examples` and be done with it? cc @TeXitoi 

@dcsobral Doc comments are already in use for `help/about`, this is one of those situations where we have to pick just one. I'm open to proposals though.

**Comment by TeXitoi** [comment]
OK for an example and closing this with it.

**Comment by dcsobral** [comment]
Works for me.
-- 
Daniel C. Sobral
