### ISSUE TITLE
How do I provide my own special option for more help?

### ISSUE THREAD

**Issue by vi** [TeXitoi/structopt#109]
`--help` and `--version` overshadow everything else and work even when required arguments are not specified.

How do I introduce my own such option, like e.g. `--full-help` that prints some long text, generated with multiple functions, yet also substitutes the usual program run?

**Comment by TeXitoi** [comment]
I don't get the feature, but it would be a clap feature, not a structopt feature.

**Comment by vi** [comment]
Maybe clap and structopt should be one project?

**Comment by TeXitoi** [comment]
That's a long term goal https://github.com/kbknapp/clap_derive
