### ISSUE TITLE
Vec<String> as non last argument gives clap panick

### ISSUE THREAD

**Issue by Apanatshka** [TeXitoi/structopt#11]
When I added a field of type `Vec<String>` to my struct with a structopt annotation, my binary stopped working and always kept giving:

```
thread 'main' panicked at 'When using a positional argument with .multiple(true) that is *not the last* positional argument, the last positional argument (i.e the one with the highest index) *must* have .required(true) set.', /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.20.5/src/app/parser.rs:557
```

EDIT: Looking at the documentation, it seems this is because I added the vector argument before a final optional argument. Can you give a compile time error about that?

**Comment by TeXitoi** [comment]
Can you confirm You have fixed your problem?

For the moment, error handling in structopt is very limited, I let this issue open for when error handling will be improved.

Thanks for the bug report

**Comment by Apanatshka** [comment]
Yes, can confirm that I worked around the problem 🙂 
Error handling story makes sense.

**Comment by TeXitoi** [comment]
Special case of #5

**Comment by TeXitoi** [comment]
I can't think of any way to improve this case, as this is a problem in clap.
