### ISSUE TITLE
non-reference pattern used to match a reference (see issue #42640)

### ISSUE THREAD

**Issue by zigguratvertigo** [TeXitoi/structopt#115]
Hi!

On grabbing 0.2.9 from crates.io last night, I hit the following error several times as it tries to compile structopt-derive:

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> C:\...\structopt-derive-0.2.9\src\attrs.rs:112:17
    |
112 | /                 NameValue(MetaNameValue {
113 | |                     ident,
114 | |                     lit: Str(value),
115 | |                     ..
116 | |                 }) => self.push_str_method(&ident.to_string(), &value.value()),
    | |__________________^
help: consider using a reference

Known issue?

**Comment by TeXitoi** [comment]
what's your rust version? Is updating to latest stable fix this problem?

**Comment by hcpl** [comment]
@zigguratvertigo the code you pointed to uses [default binding modes](https://github.com/rust-lang/rfcs/pull/2005), implemented a while ago and stabilized in Rust 1.26.

On the related note, I'd like to know what is the policy around minimum supported Rust version for `structopt`. `clap` has the policy written down in this issue: https://github.com/kbknapp/clap-rs/issues/740 and it is enforced using [Travis CI](https://github.com/kbknapp/clap-rs/blob/f74646de8c94d98db3e50f19846f050f6fee9c76/.travis.yml#L9). @TeXitoi thoughts?

**Comment by TeXitoi** [comment]
No policy for the moment, but it can be added. I think at minimum, we should add a specific version in .travis.yml to catch the needed rust upgrades.

**Comment by TeXitoi** [comment]
Maybe "must compile if clap compiles" a good policy?

**Comment by zigguratvertigo** [comment]
@TeXitoi updating to latest 1.56.2 fixed the compilation issue - thanks.
Having a check around the minimum supported rust version would be great.
