### ISSUE TITLE
Provide a version of `from_clap` that returns a result.

### ISSUE THREAD

**Issue by tomprince** [TeXitoi/structopt#12]

**Comment by TeXitoi** [comment]
What's your use case? Because from_clap mostly exists for testing. Using from_clap with a clap object generated from the clap method can't fail (or it's a bug).

**Comment by tomprince** [comment]
As far as I can tell, it can fail if `from_clap` uses `FromStr` somewhere.

**Comment by TeXitoi** [comment]
If `FromStr` is used in `from_clap`, `Arg::validator` is used in `clap`. Thus, `from_clap` cannot fail if used with the generated `Clap` object (else,  it's a bug).

**Comment by tomprince** [comment]
Ah. That isn't obvious from the code or documentation. Would it make sense to add comments to that effect? I'm used to seeing `Result` when parsing values, so was surprised when I didn't find it, and looking at the code, it wasn't obvious to me that the `unwrap`s were going to be safe.

**Comment by TeXitoi** [comment]
Sure, better documentation is always a plus. I'll try do add it next week. Of course You can propose a PR if you want.
