### ISSUE TITLE
Allow to use a HashMap in place of an array

### ISSUE THREAD

**Issue by dnagir** [TeXitoi/structopt#127]
It would be nice to be able to do this:

```rust
    #[structopt(name = "PARAMS")]
    params: HashMap<String, String>
```

The closest I could find is [keyvalue example](https://github.com/TeXitoi/structopt/blob/01d34fb8d2e6595e4b84d353d50281466f05dc9e/examples/keyvalue.rs).

But that just returns a Vector of tupples which is very different to a Hash.
It doesn't look like the custom parse function can accept multiple arguments to be split into a hash :(

**Comment by TeXitoi** [comment]
Thanks for reporting. This issue is tracked in #79, feel free to gives your feedback there.

**Comment by dnagir** [comment]
Thank you @TeXitoi. Apologies for not noticing it 👍
