### ISSUE TITLE
Structopt derive doesn't like type-parametric structs

### ISSUE THREAD

**Issue by vorner** [TeXitoi/structopt#128]
Probably better showed with some code:

```rust
struct Wrapper<O> {
    #[structopt(flatten)]
    sub: O,
}
```

I get this error message:

```
error[E0412]: cannot find type `O` in this scope
  --> src/lib.rs:31:10
   |
31 | #[derive(StructOpt)]
   |          ^^^^^^^^^ did you mean `OW`?

error[E0243]: wrong number of type arguments: expected 1, found 0
  --> src/lib.rs:31:10
   |
31 | #[derive(StructOpt)]
   |          ^^^^^^^^^ expected 1 type argument
```

Similar thing works with serde, where it automatically places correct type bounds on the generated impl block.

**Comment by TeXitoi** [comment]
StructOpt was not design with generics in mind. That's a complicated thing.

What is your use case?

**Comment by vorner** [comment]
Yes, I already noticed it's a bit harder than just making sure the impl gets the type bounds, because some things are not part of the trait. But I've found a workaround for my own use case.

I'm building a helper start-me-a-daemon library. Some of the options will be specific for each daemon, while some others will be common for all of them (like logging and option not to go to background). So I want to compose the common ones (defined in the library) with the daemon-specific ones provided by the user of the library as a generic.

For now, I have this (I haven't tried it yet, but I guess it should work).

**Comment by vorner** [comment]
Yes, but that's a different use case ‒ they want to expose the verbosity flag to the end application. I don't want to give the application the logging configuration etc ‒ I just want to logging to be configured automagically. That means my library needs access to the common configuration (if I went the verbosity way, I'd have to let the user tell me where the logging configuration is) and it would pollute the user's configuration structure.

**Comment by vorner** [comment]
(Oh, I haven't included the link in the post up there ↑ ‒ this is what I do now: https://github.com/vorner/spirit/blob/master/src/lib.rs#L59)

**Comment by TeXitoi** [comment]
Great workaround!

**Comment by CreepySkeleton** [comment]
Let's get back to the original issue. Do we want to support generic structs and what the pitfalls are?
Or will we just close it as "wontfix"?

**Comment by TeXitoi** [comment]
wontfix is fine for me.

**Comment by CreepySkeleton** [comment]
@TeXitoi actually, there is [a use case](https://www.reddit.com/r/rust/comments/efi4kb/who_else_depends_on_structopts_internal_api/fc0w1cu?utm_source=share&utm_medium=web2x) where this would be pretty useful.

What if we just copy-paste the bounds?
```rust

#[derive(StructOpt)] 
struct Opt<T, U: Read> {}

// expands to 
impl<T, U: Read> StructOpt for Opt<T, U> {
    // ...
}
```

I understand that it's not enough in some corner cases (like type items, implicit `Sized` stuff and all) and yet we will have be 99% covered, including the case above.

**Comment by CreepySkeleton** [comment]
I'm reopening this since it looks like there are people interested in this feature out there (#317).

A PR implementing this serde-like design will be accepted:
```rust

// Each of the generics will be annotated with `G: StructOpt`
// if no `#[structopt(bound = "...")]` is present, unless it's skip only.

// `T: StructOpt` will be added automatically
// since there's no `#[structopt(bound(...))]` annotation
//
// No bounds for `U` should be generated since the only
// occurrence of it is marked as `skip`.
//
// `B: StructOpt` *MUST* be generated since, despite the fact
// it's marked as `skip` on one occurrence, it is also occurring
// in a non-skip field
#[derive(StructOpt)]
struct StructOpt<T, U, B> {
    arg: T,

    #[structopt(skip)]
    skipped: U,

    #[structopt(skip)]
    skipped: B,

    skipped: B,
}

// NO automatic `T: StructOpt` will be added
// since there's an explicit `#[structopt(bound(...))]` annotation
#[derive(StructOpt)]
#[structopt(bound("S: FromStr + StructOpt"))]
struct StructOpt<S, T> {
    #[structopt(parse(from_str))]
    arg: S,

    #[structopt(skip)]
    skipped: T,
}
```

**Comment by TeXitoi** [comment]
I don't think bound should be on fields, more on the struct.

Automatic bound seems complicated to anticipate for the user.

It might complexify the code a lot.

I'm afraid it will be a lot of work for little usage. 

I'm not totally against this feature, but it must be simple enough to understand, implement, document and maintain.

**Comment by CreepySkeleton** [comment]
I must confess, I just stole the design from [`serde`](https://serde.rs/attr-bound.html).

> I don't think bound should be on fields, more on the struct.

I think that "fields vs struct bound attr" is quite irrelevant here, either will do. 

> Automatic bound seems complicated to anticipate for the user.

Not really. I tried to design the automatic bounding so it will work in 99% cases, as any good heuristic would. Thus, in 99% cases users shouldn't even be aware of it since everything "just works". 

Explicit `bound` attributes are for cases like `Foo<T>`, where it's unclear what to do: `Foo<T>: Trait` vs `T: Trait` (i.e if the generic is just a part of the type, not the type itself). In such cases, no bounds will be generated anyway ¯\\_(ツ)_/¯

I honestly can't see a case where this auto bounding may misfire, can you?

> It might complexify the code a lot. I'm afraid it will be a lot of work for little usage.

Not really. In essence, all we need is:
* Traverse the graph (already implemented)
* Collect the info (already implemented)
* Pass it to the top level (this is where dragons be, but should be fairly easy after the refactoring).
* Generate and emit the `where` clause (easy).

**Comment by nathan-at-least** [comment]
I just ran into this with a similar use case to @vorner: I want an "app framework" library that provides consistent logging options across all apps, and then also initializes logging for apps, so I naively just reached for this:

```
trait Command: StructOpt {
    fn execute(&self) -> std::io::Result<()>;
}

#[derive(StructOpt)]
pub struct Options<T: Command> {
    #[structopt(flatten)]
    log_opts: loglib::LogOptions,

    #[structopt(subcommand)]
    cmd: T,
}

fn do_main<T: Command>() -> std::io::Result<()> {
    let opts = Options::<T>::from_flags();
    opts.log_opts.init_logging()?;
    opts.cmd.execute()
}
```

When I follow the link in https://github.com/TeXitoi/structopt/issues/128#issuecomment-408409015 I don't see any code relevant to `structopt`, so I don't know what the workaround was.

**Comment by TeXitoi** [comment]
I'll try to look at it tomorrow, but, as a first read, don't you want to flatten your T instead is subcommand?

**Comment by vorner** [comment]
Ah, sorry, the code moved to another place since then :-(.

It is now here and the workaround is updated since then a bit. This link probably should keep its content:
https://github.com/vorner/spirit/blob/ce2ec171320b33ff34e645250c8951a5cce3a926/src/cfg_loader.rs#L76

**Comment by TeXitoi** [comment]
This is an enhancement, and structopt is now feature frozen.
