### ISSUE TITLE
Feature request: smarter parsing of doc comments

### ISSUE THREAD

**Issue by Lucretiel** [TeXitoi/structopt#134]
If I have a docopt like this:

```rust
#[structopt(short="n", long="no-op")]
/// Run the command as normal, but don't modify the file
///
/// In no-op mode, rewrite will do everything it normally does, including
/// writing to a temporary file, if enabled. The only thing it doesn't do is
/// modify the contents of the file.
no_op: bool,
```

It would be nice if structopt detected the line break, and set the separate parts as [`help`](https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.help) and [`long_help`](https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.long_help). It would also be nice if it automatically reflows the line breaks correctly.

**Comment by TeXitoi** [comment]
Good idea, but it will be a breaking change.

Structopt already merge lines, thus, clap should reflow. If not, that a problem with clap.

**Comment by 0ndorio** [comment]
Would it be possible to come up a new feature flag (e.g. `split_doc_comment`, `upcoming_enhancement`) to introduce such a new feature earlier as an explicit opt-in?

**Comment by TeXitoi** [comment]
That's not a problem of doing a breaking change, we just release a 0.3 and that's it. It will force me to do the other breaking changes that I want (I think of #18).

**Comment by 0ndorio** [comment]
> Structopt already merge lines, thus, clap should reflow. If not, that a problem with clap.

Maybe somthing completly differnt but as it fits the `smarter doc comment parsing` section. Is there any option forcing structopt to keep the formatting of the doc comment to achieve the same behaviour as using a raw string for `long_help` or `long_about`?

This could be nice as it would allow to introduce proper formatted doc comments including lists and source blocks into the long descriptions.

**Comment by ebkalderon** [comment]
Since #146 was already merged and published, shouldn't this issue be closed?

**Comment by TeXitoi** [comment]
@ebkalderon good point

@0ndorio if you still want https://github.com/TeXitoi/structopt/issues/134#issuecomment-429464231 please create a dedicated issue.

**Comment by Lucretiel** [comment]
Thanks!
