### ISSUE TITLE
AllowLeadingHyphen is not working with subcommands

### ISSUE THREAD

**Issue by dcuenot** [TeXitoi/structopt#135]
Hello,

I have an issue with leading Hyphen and subcommand.

When I type this `cargo run newcity city 43.2689 -2.9312`, I get this issue: `error: Found argument '-2' which wasn't expected, or isn't valid in this context`

I try to add a AppSettings::AllowLeadingHyphen in the configuration, but I still have the issue.
Can you help me to find a solution?

You can find below my code.
Thanks in advance for your help

```
#[derive(StructOpt, Debug)]
struct Options {
    #[structopt(short = "v", long = "verbose")]
    verbose: bool,
    #[structopt(subcommand)]
    cmd: Opt,
}

#[derive(StructOpt, Debug)]
#[structopt(raw(global_setting = "AppSettings::AllowLeadingHyphen"))]
enum Opt {
    #[structopt(name = "newcity")]
    NewCity {
        #[structopt(help = "Name of city")]
        city: String,
        #[structopt(help = "Name of city", default_value = "0.0")]
        lat: f32,
        #[structopt(help = "Name of city", default_value = "0.0")]
        long: f32,
    },
    #[structopt(name = "update")]
    UpdateCity {
        #[structopt(help = "Name of city")]
        city: String,
        #[structopt(help = "Player (Optional)")]
        player: Option<String>,
    },
    #[structopt(name = "calc")]
    Calc {
        #[structopt(help = "Player (Optional")]
        player: Option<String>,
    },
}
```

Damien

**Comment by TeXitoi** [comment]
It's working, that just cargo that handle the args:
```shell
$ cargo run -- newcity city 43.2689 -2.9312
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/test-rs newcity city 43.2689 -2.9312`
NewCity { city: "city", lat: 43.2689, long: -2.9312 }
```

**Comment by TeXitoi** [comment]
Is your problem fixed? I'm not sure I'm clear in my remark.

To clarify, your error is cargo error. To force cargo to pass the following args to your binary, you can use `--`. Everything after will be a argument for cargo, and be thus passed to the binary.

Without using `AppSettings::AllowLeadingHyphen`, you can  do the same trick:
```shell
$ cargo run -- newcity -- city 43.2689 -2.9312
```
In this case `newcity -- city 43.2689 -2.9312` will be given to your binary as argument. Then, everything after `--` will be arguments, and thus `-2.9312` will be an argument, and it will work.

**Comment by dcuenot** [comment]
Thanks for your answer @TeXitoi and I managed to make it work with `cargo run` 👍 

However I still have one issue after building the application :(
I did: 
`damiencuenot$ cargo build --release`

And after: 
`damiencuenot$ ./appli newcity bilbao 43.268 -2.93`

And I get the same issue as before:
```
error: Found argument '-2' which wasn't expected, or isn't valid in this context

USAGE:
    invaders newcity <city> [ARGS]

For more information try --help
```

Do you know how I can fix the issue?

**Comment by TeXitoi** [comment]
Working here.

```rust
extern crate structopt;

use structopt::StructOpt;
use structopt::clap::AppSettings;

#[derive(StructOpt, Debug)]
struct Options {
    #[structopt(short = "v", long = "verbose")]
    verbose: bool,
    #[structopt(subcommand)]
    cmd: Opt,
}

#[derive(StructOpt, Debug)]
#[structopt(raw(global_setting = "AppSettings::AllowLeadingHyphen"))]
enum Opt {
    #[structopt(name = "newcity")]
    NewCity {
        #[structopt(help = "Name of city")]
        city: String,
        #[structopt(help = "Name of city", default_value = "0.0")]
        lat: f32,
        #[structopt(help = "Name of city", default_value = "0.0")]
        long: f32,
    },
    #[structopt(name = "update")]
    UpdateCity {
        #[structopt(help = "Name of city")]
        city: String,
        #[structopt(help = "Player (Optional)")]
        player: Option<String>,
    },
    #[structopt(name = "calc")]
    Calc {
        #[structopt(help = "Player (Optional")]
        player: Option<String>,
    },
}

fn main() {
    println!("{:?}", Opt::from_args());
}
```

```sh
$ cargo build --release
    Finished release [optimized] target(s) in 0.04s                                                      
$ ./target/release/test-rs newcity bilbao 43.268 -2.93
NewCity { city: "bilbao", lat: 43.268, long: -2.93 }
$ 
```

**Comment by dcuenot** [comment]
Ok, I found why it is working on your side and not on mine.

This is working:
```
fn main() {
    println!("{:?}", Opt::from_args());
}
```

But if I replace `Opt` by `Options`, it fails
```
fn main() {
    println!("{:?}", Options::from_args());
}
```

In order to fix my issue, I have to also add `AppSettings::AllowLeadingHyphen` before the struct Options.
And now it works!

Thanks for your support

**Comment by dcuenot** [comment]
Ok, I found why it is working on your side and not on mine.

This is working:
```
fn main() {
    println!("{:?}", Opt::from_args());
}
```

But if I replace `Opt` by `Options`, it fails
```
fn main() {
    println!("{:?}", Options::from_args());
}
```

In order to fix my issue, I have to also add `AppSettings::AllowLeadingHyphen` before the struct Options.
And now it works!

Thanks for your support

**Comment by TeXitoi** [comment]
Ha, true, the settings must be on the top level object.
