### ISSUE TITLE
Interest in transitioning to Rust 2018?

### ISSUE THREAD

**Issue by ErichDonGubler** [TeXitoi/structopt#138]
Hey there! I [took some time to fix up this crate](https://github.com/ErichDonGubler/structopt/tree/rust-2018) for the 2018 edition of Rust, since it blocked me on some warnings issued by `cargo fix`. :) Would you like me to file a (maybe rebased later) PR when the edition lands? Another way to save the work and close this now would be to create a branch (i.e., `rust-2018`) and then I could open a PR against that immediately.

I'm more than happy to write documentation describing how client code will need to change to accommodate the new edition. However, **I realize that this has backward-compatibility concerns**. This really is just to test the waters, and see if the fruits of my practicing with transitioning to the 2018 edition might be beneficial.

Thanks in advance for you attention!

**Comment by TeXitoi** [comment]
I don't understand: you can use structopt with edition 2018 even if structopt is 2015. As you said, this would require a post edition 2018 toolchain, which would be a breaking change.

As long as there is no improvement for the user, I don't want such a change. But if you can explain the gain for the user, that's another story.

**Comment by ErichDonGubler** [comment]
Okay! IIRC there were some forward-compatibility concerns I found when moving some of my own applications to Rust 2018, but I can't remember if they were specific to `quicli` or to `structopt` itself.

Feel free to close this issue, then -- if I find an actual problem, I'd consider it separate in spirit from this. :)

**Comment by TeXitoi** [comment]
OK. Please reopen this issue or open a new zone of tout fond any friction.
