### ISSUE TITLE
How to express "either ... or ..." relationship

### ISSUE THREAD

**Issue by vbrandl** [TeXitoi/structopt#141]
I want to express the following relationship using structopt: The positional parameter should either be two strings (username and password) or a PathBuf (from where the credentials will be read).

I tried the following:

```rust
#[derive(Debug, StructOpt)]
enum Opt {
    #[structopt(name = "login")]
    Login { param: LoginCredentials },
    #[structopt(name = "logout")]
    Logout,
}
#[derive(Debug, StructOpt)]
enum LoginCredentials {
    UserPass { loginid: String, password: String },
    File { path: PathBuf },
}
``` 

But this will create another subcommand for the `login` subcommand. What would be the right way to express this relationship? Is there even a way to do so?

**Comment by TeXitoi** [comment]
You might want to look at https://github.com/TeXitoi/structopt/blob/master/examples/group.rs and https://github.com/TeXitoi/structopt/issues/126

**Comment by vbrandl** [comment]
I found that one already but I think it would be cool if we were able to describe groups using enums. That way it is impossible to represent an illegal state and you could simply match over the group variants.

Is it possible to implement this for structopt?

**Comment by TeXitoi** [comment]
That's a new feature, that's why I've tagged this issue enhancement. Then, we can design the details here, and anyone can implement that and do a PR to add it.

I will not implement this feature in short term, as I have others priorities, in this repo and in others. But I encourage anyone interested to contribute, and I'll try to answer any questions as fast as possible.

**Comment by vbrandl** [comment]
Just a few thoughts: 

* How this might be implemented
```rust
#[derive(Debug, StructOpt)]
#[structopt(type = "subcommand")] // this should be implicit
enum Opt {
    #[structopt(name = "login")]
    Login { param: LoginCredentials },
    #[structopt(name = "logout")]
    Logout,
}
#[derive(Debug, StructOpt)]
#[structopt(type = "group")]
enum LoginCredentials {
    UserPass { loginid: String, password: String },
    File { path: PathBuf },
}
```

* Problem: Enums with variants that contain the same types and should be parsed as positional parameters cannot be distinguished and these cases should be compile errors

```rust
#[derive(Debug, StructOpt)]
#[structopt(type = "group")]
enum Group1 {
    Var1 { a: String, b: String },
    Var2 { c: String, d: String }, // this should fail
}

#[derive(Debug, StructOpt)]
#[structopt(type = "group")]
enum Group2 {
    Var1 { 
        #[structopt(short = "a")]
        a: String,
        b: String
    },
    Var2 { c: String, d: String },
} // this should work since the variants are distingushable
```

**Comment by TeXitoi** [comment]
This is similar to #104

**Comment by TeXitoi** [comment]
This is an enhancement, and structopt is now feature frozen.
