### ISSUE TITLE
examples/keyvalue.rs is overly greedly, this works: ./cli -D A=5 B=6

### ISSUE THREAD

**Issue by SamuelMarks** [TeXitoi/structopt#145]
https://github.com/TeXitoi/structopt/blob/30da80cb809d3505a306a9cd0796dfd0d90ec3f0/examples/keyvalue.rs

Works without quotes!

It's actually a handy characteristic, but probably unexpected so should be removed or hidden under a flag?

**Comment by TeXitoi** [comment]
Sorry, forgot to answer.

That's the way clap is doing it. See https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.multiple
