### ISSUE TITLE
Using number_of_values requires nightly

### ISSUE THREAD

**Issue by SpaceManiac** [TeXitoi/structopt#15]
I see that `structopt-derive` passes along attributes to the `Arg` builder by default. For arguments which accept non-string values, such as `number_of_values`, nightly is required:

* `#[structopt(..., number_of_values="1")]` is a type mismatch (expected `u64`, found `&str`)
* `#[structopt(..., number_of_values=1)]` requires nightly and [`#![feature(attr_literals)]`](https://github.com/rust-lang/rust/issues/34981)

It doesn't seem like `attr_literals` is on a quick path to stabilization, so some other form of support may be warranted.

**Comment by TeXitoi** [comment]
Thanks for reporting. This issue is tracked in #4.
