### ISSUE TITLE
error: Invalid value for '--lines <lines>': invalid digit found in string

### ISSUE THREAD

**Issue by Boscop** [TeXitoi/structopt#152]
How can I do this?

```rust
	#[structopt(long = "lines", short = "l", default_value = "std::usize::MAX")]
	lines: usize,
```

> error: Invalid value for '--lines <lines>': invalid digit found in string

It seems that only int literals are allowed (it tries to parse an int from the string), why not allow arbitrary expressions of the arg type, like `derive-new` allows it (e.g. `#[new(value = "std::usize::MAX")]`).

**Comment by TeXitoi** [comment]
Because else, for the normal case, you'll have to double-quote the string.

The `raw` feature is here for that:

```rust
#[structopt(long = "lines", short = "l", raw(default_value = "std::usize::MAX"))]
lines: usize,
```

But default_value need a `&str`, thus it will not work as is. A workaround is to declare a `lazy_static`:

```rust
extern crate structopt;
extern crate lazy_static;

use structopt::StructOpt;
use lazy_static::lazy_static;

lazy_static! {
    static ref MAX_USIZE: String = std::usize::MAX.to_string();
}

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(long, short, raw(default_value = "&MAX_USIZE"))]
    lines: usize,
}

fn main() {
    println!("{:?}", Opt::from_args());
}
```

Does it fix your issue?

**Comment by Boscop** [comment]
> The raw feature is here for that:
#[structopt(long = "lines", short = "l", raw(default_value = "std::usize::MAX"))]
lines: usize,

When I try that, I get
> error: src\main.rs:11: mismatched types
error: src\main.rs:11: expected &str, found usize

Or did you mean that `raw()` works ONLY with strings? But then it's the same as without raw?

**Comment by TeXitoi** [comment]
raw works with anything, but `default_value` want a `&str`.

**Comment by Boscop** [comment]
What about this?
```rust
	#[structopt(long = "lines", short = "l", default_value = r#""std::usize::MAX""#)]
	lines: usize,

**Comment by Boscop** [comment]
Ah no: `error: Invalid value for '--lines <lines>': invalid digit found in string` 
:(
Is there no one-line solution?

**Comment by TeXitoi** [comment]
https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.default_value

**Comment by Boscop** [comment]
But why doesn't this work?
```rust
	#[structopt(long = "lines", short = "l", raw(default_value = r#""std::usize::MAX""#))]
	lines: usize,

**Comment by TeXitoi** [comment]
To be clear, there is 2 things here:
 - clap want a string for its `default_value`
 - structopt convert the string to the needed type using (by default) `from_str`

In your example, clap have the string `std::usize::MAX` as it's default value as you can see in the help message. But, `"std::usize::MAX".parse()` will not work. That's your error message.

**Comment by TeXitoi** [comment]
AFAIK, there is no one line solution, and I can't find a way to implement this without dirty black magic hacks.

**Comment by Boscop** [comment]
And with `raw`, why does the lazy static work but not the escaped string?

**Comment by TeXitoi** [comment]
The lazy_static version read `std::usize::MAX` and then convert it to string.

The raw version gives the string `std::usize::MAX`, that can't be converted to `usize` using `FromStr`.

**Comment by Boscop** [comment]
Ah, right -.-
I guess I keep the `Option<usize>` then.
