### ISSUE TITLE
structopt mangles colons in "author" string sourced from Cargo.toml

### ISSUE THREAD

**Issue by ssokolow** [TeXitoi/structopt#156]
As a matter of convenience, I've had a spam-guarded contact form in my `user.email` Git property ever since I started using Git long ago.

This seems to have tripped off a bug in structopt. Cargo transcribes it correctly...

```toml
[package]
authors = ["Stephan Sokolow <http://www.ssokolow.com/ContactMe>"]
```

...but then, when I view the resulting `--help` output, the colon has been replaced with a comma followed by a space.

    Stephan Sokolow <http, //www.ssokolow.com/ContactMe>

Manually specifying `author="Stephan Sokolow <http://www.ssokolow.com/ContactMe>"` causes it to pass through to `--help` unaltered.

(That said, I'm not in a hurry to have it fixed. I used `author=""` to silence that default as soon as I noticed it, both to achieve maximum consistency with the `--help` output all of the other CLI tools on my Linux machines and because it feels either egotistical or attention-seeking to display my name in my `--help` output.)

**EDIT:** Oops. forgot to mention that I'm on structopt 0.2.14. (I just began a new project and that's what `cargo add structopt` pulled in.)

**Comment by TeXitoi** [comment]
That's because cargo separe authors with colon. I don't have any simple solution.

**Comment by TeXitoi** [comment]
Maybe easier: do not replace if followed by `//`

I'll accept such a PR.

**Comment by CreepySkeleton** [comment]
@TeXitoi we can close this

**Comment by TeXitoi** [comment]
Of course, thanks for your fix.
