### ISSUE TITLE
Hexadecimal numbers are considered invalid?

### ISSUE THREAD

**Issue by m4b** [TeXitoi/structopt#16]
I am hoping I'm stupid as usual and messed something up but it looks like I can't pass hexadecimal values as `u64`, etc. args.  

Is this true ? Perhaps it's downstream clap issue ?

Please tell me no, this is a deal breaker for some of my projects :/

**Comment by TeXitoi** [comment]
That's because of ‘FromStr‘ that is used to do all the conversions now. You want #3 to fix your problem.
