### ISSUE TITLE
How to accept double dash and send arguments to child process

### ISSUE THREAD

**Issue by otaviopace** [TeXitoi/structopt#162]
Hi! I am using `structopt` and I am having trouble to specify a CLI parameter which will be sent to a child process.

Consider the following cenario:

Let's say `my-program` is my CLI and it calls at some point `other-program`, which is a CLI too.

The `other-program` accepts arguments just like `my-program`, however I do not have access to it's code nor implementation.

I want `my-program` to accept the double dash argument to send arguments to the `other-program` child process. Example:
```shell
my-program --cool-arg=blue -- --arg1=foo --arg2=bar
```
That means that all of this part: `--arg1=foo --arg2=bar` will be sent as arguments to `other-program`.

Assuming that I have a `struct` which represents my arguments using `structopt`, like this:

```rust
#[derive(StructOpt)]
struct MyOpts {
    #[structopt(long = "cool-arg")]
    pub cool_arg: String,
}
```

How should I add a `field` to the `MyOpts` `struct` that works like the line I've showed?

**Comment by TeXitoi** [comment]
Hi! Isn't #153 about your problem? Does the thread help you find your solution?

**Comment by otaviopace** [comment]
Yes! It is exactly what I want, thank you very much!
