### ISSUE TITLE
Allow preserving newlines

### ISSUE THREAD

**Issue by konstin** [TeXitoi/structopt#163]
The have the following docstring:

```
    /// Control the platform tag on linux.
    ///
    ///  - `1`: Use the manylinux1 tag and check for compliance
    ///  - `1-unchecked`: Use the manylinux1 tag without checking for compliance
    ///  - `2010`: Use the manylinux2010 tag and check for compliance
    ///  - `2010-unchecked`: Use the manylinux1 tag without checking for compliance
    ///  - `off`: Use the native linux tag (off)
    ///
    /// This option is ignored on all non-linux platforms
```

This renders fine in rustdoc:

![grafik](https://user-images.githubusercontent.com/6826232/51709491-c952be80-2026-11e9-90bd-36cbf5db41d0.png)

Structopt however collapses those lines:

```
        --manylinux <manylinux>
            Control the platform tag on linux. - `1`: Use the manylinux1 tag and check for compliance - `1-unchecked`:
            Use the manylinux1 tag without checking for compliance - `2010`: Use the manylinux2010 tag and check for
            compliance - `2010-unchecked`: Use the manylinux1 tag without checking for compliance - `off`: Use the
            native linux tag (off)

            This option is ignored on all non-linux platforms [default: 1]  [possible values: 1, 1-unchecked, 2010,
            2010-unchecked, off]
```

Since I fear that full markdown to text rendering like pandoc is currently out of scope, it would great to have a way to preserve newlines.

**Comment by TeXitoi** [comment]
I agree with the feature request, but I don't have any solution. Do you have any proposition?

**Comment by konstin** [comment]
One idea would be `#[structopt(preserve_newlines)]` on the field. Another, less rustdoc-friendly would be some thing like https://github.com/clap-rs/clap/issues/617#issuecomment-245268409. i.e. replacing `\n` or `{n}` with newlines.

**Comment by konstin** [comment]
> {n} will work out of the box,

Huh I thought I had checked that this doesn't work but apparently it does, so I'll go with that for now. Thanks!

**Comment by Geobert** [comment]
as `raw` is only allowed with true or false in structopt 0.3, how do we do the workaround now?

**Comment by CreepySkeleton** [comment]
Via raw methods:
```
use structopt::StructOpt;

static MANYLINUX_HELP: &str = r#"Control the platform tag on linux.

 - `1`: Use the manylinux1 tag and check for compliance
 - `1-unchecked`: Use the manylinux1 tag without checking for compliance
 - `2010`: Use the manylinux2010 tag and check for compliance
 - `2010-unchecked`: Use the manylinux1 tag without checking for compliance
 - `off`: Use the native linux tag (off)

This option is ignored on all non-linux platforms"#;

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(long, help = MANYLINUX_HELP)] // <---
    manylinux: Option<String>,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

Come on, people, does anyone read docs these days?

**Comment by Geobert** [comment]
Thanks, I've read the docs, multiple times, but missed it. (English is not my mothertongue, please bear with me)

**Comment by CreepySkeleton** [comment]
@TeXitoi I propose to implement `#[structopt(doc_verbatim)]`, `raw...` names too strongly correlate with "raw methods" in my opinion.

cc @TeXitoi

**Comment by TeXitoi** [comment]
OK for `doc_verbatim`
