### ISSUE TITLE
Using subcommand attributes from separate structs

### ISSUE THREAD

**Issue by ebkalderon** [TeXitoi/structopt#165]
Currently, if you want to work with subcommands in `structopt`, you would use an enum to represent each one:

```rust
#[derive(StructOpt)]
enum Subcommand {
    #[structopt(name = "foo")]
    Foo {
        #[structopt(short = "arg1")]
        first: bool,
        #[structopt(short = "arg1")]
        second: u32,
    },
    #[structopt(name = "bar")],
    Bar {
        #[structopt(short = "arg1")]
        first: bool,
        #[structopt(short = "arg1")]
        second: u32,
    },
    #[structopt(name = "baz")]
    Baz {
        #[structopt(short = "arg1")]
        first: bool,
        #[structopt(short = "arg1")]
        second: u32,
    },
}
```

Since this can get unwieldy very fast, it is convenient to split out each enum variant into a separate struct payload, like so:

```rust
#[derive(StructOpt)]
enum Subcommand {
    #[structopt(name = "foo")]
    Foo(Foo),
    #[structopt(name = "bar")]
    Bar(Bar),
    #[structopt(name = "baz")]
    Baz(Baz),
}
```

One slight annoyance with this is that the attributes must be placed on each enum variant, and any attributes placed on the structs themselves are ignored. For example, if you are using `after_help` to add extra descriptions to each subcommand in the `Subcommand` enum, this can make the definition very lengthy. It would be nice to be able to delegate the `after_help` and other `structopt` attributes to the structs in this case.

**Comment by TeXitoi** [comment]
That's quite complicated technically as far as I remember.

**Comment by rivertam** [comment]
I recognize the technical challenge, and I think it might be out of the scope of this crate, but I would like to add that this would allow reusing logic in different binaries or different parts of the program with similar options.

A few tools I can think of that might want to be able to have nested options that can be reused

- An AWS/gcloud style CLI suite of tools that wants you to be able to specify your authentication config file
- A libav style CLI suite of tools (`ffmpeg` primarily) that might want options like "codec" for a ton of types of commands (but not all), so being able to share the single option would be good.

I have a use for it in my own production code that I won't get too into, but it's quite similar to the second usecase. We could use environment variables for it but I think CLI options is a better fit.

**Comment by TeXitoi** [comment]
Can you check the flatten attribute? Clap-verbose-flag cratère use it d'or exemple.

**Comment by rivertam** [comment]
@TeXitoi I think that covers my usecase. Just didn't see it documented. Thanks!

**Comment by CreepySkeleton** [comment]
> It would be nice to be able to delegate the `after_help` and other `structopt` attributes to the structs in this case.

I'm almost sure this is impossible - macro expansions are independent from each other, there's no way to pass info from one to another

**Comment by CreepySkeleton** [comment]
@TeXitoi I suggest to close this - use case is resolved by `flatten`, but [passing info between macro calls on compile time is impossible](https://github.com/rust-lang/rust/issues/56420#issuecomment-443462926)
