### ISSUE TITLE
Figure out which alias was used

### ISSUE THREAD

**Issue by Fiedzia** [TeXitoi/structopt#167]
For a command that has an alias defined, Is there a way to get an alias that was used?
I see that clap doesn't provide that, nor can I see any way to hook anywhere to get this information.

**Comment by TeXitoi** [comment]
If clap doesn't provide it, structopt doesn't as structopt is "just" a layer over clap.

**Comment by Fiedzia** [comment]
I figured out that what I asked for is not possible, but wrapping struct in new type and defining my own augment_clap and from_subcommand methods will give me more control and allows to define and parse commands at runtime.

**Comment by TeXitoi** [comment]
Note that `augment_clap` and `from_subcommand` are implementation details, and are not guaranteed to not break between updates

**Comment by Fiedzia** [comment]
True. Some stable way of generating commands at runtime would be nice to have.
