### ISSUE TITLE
Accept list of structs

### ISSUE THREAD

**Issue by CodeSandwich** [TeXitoi/structopt#170]
I'm trying to create CLI with list of grouped arguments:
```
my_app --group arg1 arg2 --group arg3 arg4 --flag
```
I was trying to recreate it in structs:
```rust
#[derive(StructOpt)]
struct Args {
    #[structopt(long)]
    group: Vec<Group>,
    #[structopt(long)]
    flag: bool,
}

#[derive(StructOpt)]
struct Group {
    param_1: String,
    param_2: String,
}
```
Obviously this does not work: `Group` does not implement `FromStr`. Is there a way to accept such CLI arguments?

**Comment by TeXitoi** [comment]
This example is close to your question: https://github.com/TeXitoi/structopt/blob/master/examples/keyvalue.rs

Does it answer your question?

**Comment by CodeSandwich** [comment]
Thank you, but unfortunately not quite. It parses list of `key:123` values into keys and values. What I need is parsing list of `value1 value2` into a list of structures with 2 fields.

**Comment by CodeSandwich** [comment]
What I could do is ask users to join grouped arguments with `:`, e.g. `value1:value2` and then parse it and put into `Group`.

**Comment by TeXitoi** [comment]
I don't think it's possible with clap to do the difference between `my_app --group arg1 arg2 --group arg3 arg4` and `my_app --group arg1 arg2 arg3 arg4`. If that's not possible with clap, it's not possible with structopt

**Comment by TeXitoi** [comment]
If you have `--group key:123 --group key:123` then you can adapt my example to your case.

**Comment by TeXitoi** [comment]
Or implement `FromStr` for your `Group` struct from `key:123`

**Comment by CodeSandwich** [comment]
That's a pity. I'll go the `:` way, thank you very much for your help!

**Comment by TeXitoi** [comment]
Welcome.

**Comment by cecton** [comment]
> I don't think it's possible with clap to do the difference between `my_app --group arg1 arg2 --group arg3 arg4` and `my_app --group arg1 arg2 arg3 arg4`. If that's not possible with clap, it's not possible with structopt

I found a trick that makes it possible:

Definition:
```
		/// Pairs of types directly followed by params in the form:
		///
		/// -v <type1> <param1> -v <type2> <param2> ...
		#[structopt(short = "v", name = "type-or-param", number_of_values = 2)]
		params: Vec<String>,
```

Then in your code you can iterate over tuples using itertools:

```
	assert_eq!(params.len() % 2, 0);

	let params = params
		.iter()
		.tuples::<(_, _)>()
```

I hope this will help someone in the future.
