### ISSUE TITLE
Adding env=.. to a bool flag turns it into an option

### ISSUE THREAD

**Issue by shimunn** [TeXitoi/structopt#176]
I'm not quite sure if this belongs here or is an clap issue:

```
#[structopt(short = "l", long = "log")]
log: bool
```
Will be interpreted as a Flag as expected but if I add `env="APP_LOG"` it will turn into an option meaning instead of being able to call `app --log` I'm now forced to write `app --log true`.

I'm happy to fix this myself if that's desired and if somebody could give me a hint which parts of the codebase might influence this behavior.

**Comment by TeXitoi** [comment]
I suspect using `env` in clap change the flag to an option. Please check that you have the same behavior using `.takes_value(false).multiple(false).short("l").long("log").env("APP_LOG")` using clap.

**Comment by TeXitoi** [comment]
From clap doc: NOTE: This implicitly sets Arg::takes_value(true).

https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.env

`env` is not made to support this usage, thus I close this as "clap doesn't really support this usage without hacks".
