### ISSUE TITLE
clippy warning: redundant closure found

### ISSUE THREAD

**Issue by konstin** [TeXitoi/structopt#177]
```rust
/// Manylinux2
pub enum Manylinux2 {}

impl std::str::FromStr for Manylinux2 {
    type Err = &'static str;

    fn from_str(_: &str) -> Result<Self, Self::Err> {
        unreachable!()
    }
}

#[derive(StructOpt)]
pub struct BuildOptions2 {
    pub manylinux: Manylinux2,
}
```

This results in the following clippy warning:

```
warning: redundant closure found
  --> src/build_options.rs:32:10
   |
32 | #[derive(StructOpt)]
   |          ^^^^^^^^^
   |
   = note: #[warn(clippy::redundant_closure)] on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure
```

**Comment by hcpl** [comment]
Triggered by https://github.com/TeXitoi/structopt/blob/c29ba3d67a9841ebe44eda1baeafc2cc6a3ca228/structopt-derive/src/lib.rs#L142 in latest beta (`1.34.0-beta.9`), but not latest stable (`1.33.0`) or latest nightly with clippy (`nightly-2019-03-23`).

Changing that closure to use `ToString::to_string` should fix the warning, though it shouldn't have triggered in the first place, as discussed in https://github.com/rust-lang/rust-clippy/issues/3791.

**Comment by TeXitoi** [comment]
PR to use `ToString::to_string` will be accepted. I'll not publish a new version for such a change, but it can be in the next release.
