### ISSUE TITLE
Option<Vec<T> as argument

### ISSUE THREAD

**Issue by aurabindo** [TeXitoi/structopt#180]
Hi,

An argument with Option<Vec<T>> does not seem to work. Are there any workarounds ?
```
#[derive(StructOpt, Debug)]
pub enum DevCmds {
    #[structopt(name = "list", alias = "show")]
    Cmd1 {
        optional_args: Option<Vec<String>>,
    },
```

This produces errors like:
```
error[E0277]: the trait bound `std::vec::Vec<T>: std::str::FromStr` is not satisfied
```

**Comment by TeXitoi** [comment]
Why not just `Vec`?

**Comment by NextTimeJim** [comment]
Hi, I can't speak for @aurabindo, but for my use case I'd like to differentiate between 
```
./my-app                                                     // None
./my-app --optional-multiple                       // Some(vec![])
./my-app --optional-multiple ARG1 ARG2  // Some(vec![ARG1, ARG2])
```
is this currently possible without `Option<Vec<T>>`? Thanks for your work on structopt!

**Comment by TeXitoi** [comment]
That's not possible with structopt today. That's a structopt limitation, clap allows to do that.
