### ISSUE TITLE
Howto enhance subcommand/USAGE message?

### ISSUE THREAD

**Issue by spooch** [TeXitoi/structopt#183]
Hi,
Im trying to use structopt for a cli-tool like git with two subcommands. The first ist the target, which I want to edit, the second is the action type (like "create" "remove" etc.).

Now on two subcommands the USAGE message always is, although both subcommands are required:
```
my_cli [FLAGS] <SUBCOMMAND>
```

but I would like to see more meaningful like:
```
my_cli [FLAGS] <TARGET> <ACTION>
```
Furthermore It would be great to rename the Header from "SUBCOMMANDS" to "TARGETS" too, even as in the help of the targets to "ACTION".

Is this possible at the moment?

**Comment by TeXitoi** [comment]
StructOpt uses clap under the hook. If that's not possible with clap, that's not possible with structopt.

I don't know such feature on clap, but if you find what you want in the clap documentation, I cn help you translate it to structopt.

**Comment by TeXitoi** [comment]
closing because that's a clap question.
