### ISSUE TITLE
Interactive prompts on failure

### ISSUE THREAD

**Issue by bedax** [TeXitoi/structopt#184]
Hello, I have a small command line program which I always forget the options for and have to use --help for every time. After looking at darcs recently it occurred to me that it would be nice to get a series of prompts when clap fails to parse the input. For example, let's say I'm writing a simple `log` program, with the following options: 

```
#[derive(StructOpt)]
struct Options {
   #[structopt(short="p", long="path")]
   /// The path to the logs file, defaults to `~/.logs`
   path: Option<PathBuf>,

   #[structopt(short="l", long="level")]
   /// The record's log level
   level: Option<String>,
   
   /// The message to log
   message: String
}
```

It would be good if I type `log` with no arguments to be given something like the following:

```
USAGE: log [OPTIONS] <message>

[optional] The path to the log file, defaults to `~/.logs` 
> ~/.some-other-file

[optional] The record's log level 
> info

[required] The message to log 
> something happened
```

I realise this isn't necessarily something you want baked into the core, perhaps an external crate, perhaps a feature. Either way, I'm happy to write this, but I'm not sure how best to tap into the parser.

Perhaps the StructOpt trait could have a `from_fns` function with a signature like this: 

```
struct ArgumentDescription<'a> {
   short: &'a str,
   long: &'a str,
   description: &'a str
}

trait StructOpt {
   fn from_fns<T: FromStr>(optional_getter: impl Fn(ArgumentDescription) -> Option<T>,
                           required_getter: impl Fn(ArgumentDescription) -> T) 
                           -> Self;
}
```

Then `from_args` can be run first, and if it fails it could rerun using `from_fns`, and those getters would in this case prompt the user for the input.

Also, a huge thanks btw for this crate, great work :+1:

**Comment by TeXitoi** [comment]
Thanks for the interrest and proposition.

This kind of feature should be implémentéd by clap. One time clap implémentés the feature, structopt Will implements it for free. Maybe some intégration can be done at that tome for a better programmer experience.

**Comment by bedax** [comment]
Ah okay, thanks for your response, I'll repost this to clap
