### ISSUE TITLE
Testing error messages from procedural macros

### ISSUE THREAD

**Issue by sphynx** [TeXitoi/structopt#199]
As noted [here](https://github.com/TeXitoi/structopt/pull/190#issuecomment-496913036), it would be nice to add tests for checking error messages got from procedural macros during compilation time. Since they are visible to users, it's important to keep them readable, predictable and stable between versions. 

An example of an error message from a macro in compile time:

```
error: proc-macro derive panicked
  --> src/main.rs:11:10
   |
11 | #[derive(StructOpt, Debug)]
   |          ^^^^^^^^^
   |
   = help: message: cannot parse structopt attributes: ( parse ( 2 + 2 ) ): Error("expected identifier")

error: aborting due to previous error
```

There is no easy way to run tests in compile time using conventional `[test]` attributes. However, I've found a nice package called [trybuild](https://github.com/dtolnay/trybuild) from @dtolnay, author of `syn` and `quote`. The package tries to compile test programs and matches the output against predefined `.stderr` files, which looks like exactly what is needed here.

I can take a closer look on that package and then incorporate it in `structopt` testing infrastructure.

**Comment by TeXitoi** [comment]
trybuild seems the way to go, I'll accept such a PR.
