### ISSUE TITLE
Semver break from 0.2.16 to 0.2.17

### ISSUE THREAD

**Issue by vi** [TeXitoi/structopt#200]
Previously function for `try_from_os_str` to get `Option<Vec<u8>>` required signature `Result<Vec<u8>, OsString>`, now it requires `Result<Option<Vec<u8>>, OsString>`.

This resulted in break by `cargo update`.

**Comment by vi** [comment]
Additionally that argument stops being optional and starts being required.

**Comment by TeXitoi** [comment]
Mmm, so #188 is a breaking change.

**Comment by TeXitoi** [comment]
0.2.17 yanked

**Comment by TeXitoi** [comment]
As 0.2.17 is yanked, this issue is now fixed. Feel free to ask anything if you're blocked.

Thanks for reporting!
