### ISSUE TITLE
Flags inside string literals are interpreted incorrectly

### ISSUE THREAD

**Issue by expectocode** [TeXitoi/structopt#210]
Code to reproduce:
```
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
#[structopt(name = "example", about = "An example of a bug.")]
pub struct Opt {
    foo: String
}

fn main() {
    let args = Opt::from_args();
    dbg!(args);
}
```
Shell: `cargo run -- "-i"`

I expected this to assign the string "-i" to the variable foo, but it actually prints this error: `Found argument '-i' which wasn't expected, or isn't valid in this context`.

This also happens in my project which uses try_from_str - the string causes this error before being passed to my parser function. However, it works if I use the form --flag="-i". This is an okay workaround, but requires users to change their behaviour, which can be frustrating.

Bonus picture:
![image](https://user-images.githubusercontent.com/15344581/60399747-b4e09800-9b69-11e9-994f-758341c497f0.png)

**Comment by TeXitoi** [comment]
First, note that `cargo run -- "-i"` and `cargo run -- -i` are strictly the same as the `"` is interpreted by the shell. If you want to have `-i` as argument, you can do `cargo run -- -- -i` (the second `--` is given to the binary.

You can also use the clap settings for this use case: https://docs.rs/clap/2.33.0/clap/enum.AppSettings.html#variant.AllowLeadingHyphen

```rust
use structopt::StructOpt;
use structopt::clap::AppSettings::AllowLeadingHyphen;

#[derive(StructOpt, Debug)]
#[structopt(name = "example", about = "An example of a bug.", raw(setting = "AllowLeadingHyphen"))]
pub struct Opt {
    foo: String
}

fn main() {
    let args = Opt::from_args();
    dbg!(args);
}
```

(not tested)

**Comment by expectocode** [comment]
Thanks! What about the case of a named argument like `cargo run -- -f "-i"`? This also causes an error, although `-f"-i"` and `-f="-i"` work

**Comment by TeXitoi** [comment]
https://docs.rs/clap/2.33.0/clap/enum.ArgSettings.html#variant.AllowLeadingHyphen
