### ISSUE TITLE
Yank 0.2.18?

### ISSUE THREAD

**Issue by tangmi** [TeXitoi/structopt#211]
Hi all! It looks like [0.2.18](https://github.com/TeXitoi/structopt/commits/v0.2.18) has fewer commits than [0.2.17](https://github.com/TeXitoi/structopt/commits/v0.2.17)!

I noticed this because [`Option<Vec<T>>` support](https://github.com/TeXitoi/structopt/commit/57b33d33161070e205618a3fa1e917c924e32179) exists in 0.2.17, but not in 0.2.18.

Cheers!

**Comment by TeXitoi** [comment]
Option<Vec<T>> is a breaking change. That's why 0.2.17 is yanked. Will be in 0.3

**Comment by tangmi** [comment]
Gotcha, thanks for the explanation!
