### ISSUE TITLE
ChangeLog does not mention removing raw attributes in 0.3

### ISSUE THREAD

**Issue by sphynx** [TeXitoi/structopt#214]
As far as I can see, "Breaking Changes" section of the `ChangeLog` currently does not mention that raw attributes can't be specified anymore (one just have to use Rust expressions instead of strings directly). I believe it should be highlighted, since it's a serious breaking change.

Moreover, there is `raw` attribute in Clap, so `structopt`'s `raw` will be now converted to Clap's `raw` which has a totally different semantics and that might be confusing for users.

Perhaps, we should intercept this situation and gently fail with some helping suggestion.

**Comment by TeXitoi** [comment]
I agree, must be done before v0.3. Everything for migrating must be clearly explicited in the changelog.

I don't require a dedicated raw parsing (allowing only `raw(true)` and `raw(false)` might be tricky) but if you find a simple and non instrusive way of doing it, why not.

**Comment by CreepySkeleton** [comment]
@TeXitoi I suggest to explicitly trigger an error on anything that's not one of `raw(true)` or `raw(false)`. Parsing a `bool` literal should be quite easy via [`syn::LitBool`](https://docs.rs/syn/0.15.44/syn/struct.LitBool.html)

**Comment by TeXitoi** [comment]
Ok for the raw check

**Comment by CreepySkeleton** [comment]
@TeXitoi I'll get to writing docs tomorrow, can't promise I'll do it *fast* - I'm not a native English speaker after all - but I'll do my best. Any hints and discussion are welcome, you should know this crate much better than me. I'd also appreciate if you point me at any other issues that are stalling the `0.3` release

**Comment by TeXitoi** [comment]
The goal is, for a 0.2 user, to easily migrate to 0.3. You can look at the 0.2 migration guide in the changelog as an example.

That's the last one, even the syn/quote update is transparent and can be done later.
