### ISSUE TITLE
Subcommands with spaces

### ISSUE THREAD

**Issue by lordvlad** [TeXitoi/structopt#219]
I like to write my CLIs in a conversational manner, e.g. `my-app add user foobar` instead of `my-app user add foobar`, and as such, the subcommand would be `add_user` instead of the subsubcommand `user -> add`.

A quick experiment with 
```rust
enum Cmd {
    /// Add a user to the application
    #[structopt(name = "add user")]
    AddUser,
}
```
Printed the correct usage information
```
FLAGS:
    -d, --debug      Show additional debug output
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -f, --format <format>    Override the default output formatting

SUBCOMMANDS:
    add user       Add a user to the application
```

but using the subcommand failed with
```
$ cargo run -- add user
error: The subcommand 'add' wasn't recognized
        Did you mean 'add user'?
```

Using quotes around the subcommand yields the expected result:
```
$ cargo run -- "add user"
```

Is it feasible to implement it in a way that the quotes are not required?

**Comment by TeXitoi** [comment]
You can't with clap. A subcommand is one argument, and you want a 2 arguments subcommand name.

The closest would be "add-user" which is also less disturbing for a unix user, as he would think that `add user`  would be subcommand `add` subsubcommand `user` (you can do that also).

**Comment by lordvlad** [comment]
I've tried subcommand `add` subsubcommand `user`, it works well, the only issue I have with that solution is the help which will show only `add` in `my-app --help` and you need to type `my-app add --help` to get the help for `add user`. Or is there a way to override command helps?

**Comment by TeXitoi** [comment]
I don't have any better idea.

**Comment by lordvlad** [comment]
Is there a way to add additional lines to the command line help? I guess I could mix both of my approaches and use a dummy like this:

```rust
enum Cmd {
    /// Add a user to the application
    #[structopt(name = "add user")]
    AddUserDummy,

    #[structopt(name = "add")]
   AddStuff(AddStuffCmd),
}
```

**Comment by TeXitoi** [comment]
you can, but it's smelly IMHO ;-)
