### ISSUE TITLE
Subcommand or argument

### ISSUE THREAD

**Issue by David-OConnor** [TeXitoi/structopt#222]
Is there a way to mix subcommands with arguments? (Or wildcard subcommands?)

Ie, with this struct:
```rust
#[derive(StructOpt, Debug)]
#[structopt(name = "example")]
struct Opt {
    #[structopt(subcommand)]
    subcmds: SubCommand,  // an enum
    #[structopt(name = "custom")]
    custom: Option<String>,
}
```

The user could enter one of the subcommands defined in `SubCommand`, but if he enters something else instead, it's handled as such instead of reporting a mistake.

**Comment by David-OConnor** [comment]
I think the solution is to make `SubCommand` an option in my example.

**Comment by TeXitoi** [comment]
Subcommand option should be what you want. Vec<String> should ne enough for the rest, no need of another option.

**Comment by David-OConnor** [comment]
Looks like you're right!
