### ISSUE TITLE
Question: Use of const for defaults

### ISSUE THREAD

**Issue by dcsobral** [TeXitoi/structopt#226]
Is there a way of getting defaults to use `const` declarations? I'd like to share defaults between my tests and the app, but I see no way of doing it.

**Comment by TeXitoi** [comment]
I'm not sure to understand the question but I try.

```rust
use structopt::StructOpt;

const DEFAULT_FLAG_VALUE: &'static str = "My default value";

#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(short, raw(default_value = "DEFAULT_FLAG_VALUE"))]
    flag: String,
}

fn main() {
    println!("{:?}", Opt::from_args());
}
```

**Comment by dcsobral** [comment]
Oh, that works! I don't know if the difference is in the lifetime I had not specified, or some other syntax difference -- I tried using "raw", which I did use for settings, but the above seems subtly different than what I had written.

**Comment by TeXitoi** [comment]
If you have some complete non compiling example, I can Help you understand the problem.

**Comment by dcsobral** [comment]
I don't. I tried various things, but I was really pressed for time so I just shrugged it off, posted this question, and moved on.
