### ISSUE TITLE
Question: Capturing extra arguments

### ISSUE THREAD

**Issue by Relrin** [TeXitoi/structopt#228]
Hello,

I'm trying to write an application with `structopt` package and wondering, is it possible to capture excessive arguments (that not specified in subcommand parameters), save it in some variable and use it later on. I would like to do something like this:
```rust
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
#[structopt(name = "app")]
pub enum Command {
    // ...
    #[structopt(name = "deploy")]
    /// Make a deploy with the specified configuration
    Deploy {
        #[structopt(
            short = "c",
            long = "config",
            required = true,
            default_value = "",
            help="Config name"
        )]
        config: String,
        #[structopt(
            default_value = "",
            hidden = true,
            help="List of arguments to be passed on to Terraform command"
        )]
        context: Option<Vec<String>>
    }
}
```
So, I could use in terminal/console command like `app deploy -c dev -backend-config="key=test" --var-file=file1.tfvars` and put all terraform args in `context` ?

**Comment by TeXitoi** [comment]
I'm not sure I understand your question, but maybe applying https://github.com/TeXitoi/structopt/issues/130#issuecomment-521819213 on your subcommand is what you want?

**Comment by David-OConnor** [comment]
I was about to post a new issue about a specific case of this, but I think I've solved your general case. Here, `subcmds` are the normal structopt args, and `script` is something arbitrary.

```rust
#[derive(StructOpt, Debug)]
#[structopt(name = "Pypackage", about = "Python packaging and publishing")]
struct Opt {
    #[structopt(subcommand)]
    subcmds: Option<SubCommand>,
    #[structopt(name = "script")]
    script: Vec<String>,
}

// ...

    let opt = Opt::from_args();
    let subcmd = match opt.subcmds {
        Some(sc) => sc,
        None => {
            let args = opt.script;
            if !args.is_empty() {
            // do things with args here.
            }  
        }
    };
    // Pattern-match normal subcommands here.
```

My issue: If the arbitrary arg isn't similar to the official ones, it works. If it is, I get this message:
```
error: The subcommand 'ipython' wasn't recognized
        Did you mean 'python'?

If you believe you received this message in error, try re-running with 'pypackage -- ipython'

USAGE:
    pypackage [script]... [SUBCOMMAND]
```
Is there a way to disable this behavior?

**Comment by Relrin** [comment]
I have tried to attach `raw(setting = "structopt::clap::AppSettings::TrailingVarArg")` option to subcommand, but it doesn't work:
```rust
#[derive(StructOpt, Debug)]
#[structopt(name = "terraform-sage")]
pub enum Command {
    /// Initialize a Terraform working configuration
    #[structopt(
        name = "init",
        raw(setting = "structopt::clap::AppSettings::TrailingVarArg")
    )]
    Init {
        #[structopt(required = true, help = "Configuration name")]
        config: String,
        #[structopt(
            short = "d",
            long = "dir",
            default_value = ".",
            help = "Path to directory with Terraform files"
        )]
        directory: String,
        #[structopt(
            short = "t",
            long = "target",
            help = "Path to the Terraform module (*.tf)"
        )]
        target: Option<String>,
        #[structopt(
            long = "template",
            default_value = "main.tpl",
            help = "Path to the used template file (*.tpl)"
        )]
        template: String,
        #[structopt(
            short = "o",
            long = "out",
            help = "Path to the generated file (*.tf)"
        )]
        out: Option<String>,
        extra: Vec<String>
    }
}
```
And when trying to run a programm like this `terraform-sage init dev --dir=examples/templates/ --var-file=test`, I'm getting the error about wrong parameters for command:
```
Running `target/debug/terraform-sage init dev --dir=examples/templates/ --var-file=test`       
error: Found argument '--var-file' which wasn't expected, or isn't valid in this context            
```

**Comment by TeXitoi** [comment]
@David-OConnor you can desactivate the suggestions feature that will be forwarded to clap, I think that's what you want.

**Comment by TeXitoi** [comment]
@Relrin you can break with `--` before the extra part : `terraform-sage init dev --dir=examples/templates/ -- --var-file=test`

Maybe you can also try https://docs.rs/clap/2.33.0/clap/enum.AppSettings.html#variant.AllowLeadingHyphen

**Comment by Relrin** [comment]
@TeXitoi Thank you for a good explanation how to work with that. Now it works!

**Comment by TeXitoi** [comment]
Welcome, and sorry to not been more reactive (I skipped the notification).

**Comment by David-OConnor** [comment]
@TeXitoi: Could you provide an example of how to disable suggestions? Thank you.

**Comment by TeXitoi** [comment]
Something like that in `Cargo.toml`
```toml
structopt = { version = "0.3", default_features = false, features = ["color", "wrap_help", "doc"] }
```
without `"suggestions"` in features.

**Comment by David-OConnor** [comment]
Thank you! That worked.
