### ISSUE TITLE
Argument groups

### ISSUE THREAD

**Issue by jackjen** [TeXitoi/structopt#23]
Is there a plan to add argument groups / mutually exclusive flags and or options? After a little searching I either couldn't see how to achieve them, or came to the conclusion that I would need to use clap directly. 

For example,

Allow:
command --arg1
command --arg2
command --arg1 [name]

But not allow:
command --arg1 [name] --arg2

Also to combine the mutually exclusiveness these with subcommands,

Allow:
command subcommand --subarg1

But not allow:
command --arg1 subcommand --subarg1
command --arg1 [name] --arg2 subcommand --subarg1

(edit, added examples)

Thanks.

**Comment by TeXitoi** [comment]
Transcription of https://docs.rs/clap/2.26.0/clap/struct.Arg.html#method.conflicts_with

```rust
extern crate structopt;
#[macro_use]
extern crate structopt_derive;

use structopt::StructOpt;

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(long = "config", conflicts_with = "debug")]
    cfg: Option<String>,
    #[structopt(long = "debug")]
    debug: bool,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

```
cargo run -- --debug --config file.conf
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/gupinot/dev/test-rs/target/debug/test-rs --debug --config file.conf`
error: The argument '--config <cfg>' cannot be used with '--debug'

USAGE:
    test-rs --debug

For more information try --help
```

From the doc at https://docs.rs/structopt-derive/0.1.0/structopt_derive/

>  Every method of clap::App in the form of fn function_name(self, &str) can be use through attributes placed on the struct.

Does it answer your question? Do you have an idea of what we can do to help find this information?

**Comment by jackjen** [comment]
It does answer my question for the most part - my bad for not reading thoroughly. As for clarity, I think it's clear enough.

So I have the ability to specify conflicting arguments per app/subcommand.
What about conflicts with for a subcommand? (require the inability to specify a particular argument *and* a subcommand)

**Comment by TeXitoi** [comment]
I can't find the feature in clap. Do you know how to do that with clap? If that's not possible with clap, that's not possible with structopt.

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/structopt/blob/master/examples/group.rs

**Comment by Fuuzetsu** [comment]
> https://github.com/TeXitoi/structopt/blob/master/examples/group.rs

This is unsatisfactory as it doesn't allow for convenient parsing of enums. To quote the given example:
```rust
struct Opt {
    /// Set a custom HTTP verb
    #[structopt(long, group = "verb")]
    method: Option<String>,
    /// HTTP GET
    #[structopt(long, group = "verb")]
    get: bool,
    /// HTTP HEAD
    #[structopt(long, group = "verb")]
    head: bool,
    /// HTTP POST
    #[structopt(long, group = "verb")]
    post: bool,
    /// HTTP PUT
    #[structopt(long, group = "verb")]
    put: bool,
    /// HTTP DELETE
    #[structopt(long, group = "verb")]
    delete: bool,
}
```

To get something like
```rust
enum Method {
  Get,
  Head,
  Post,
  Put,
  Delete,
}
```

The user has to do something like
```rust
if opts.get { return Method::Get }
if opts.head { return Method::Post }
…
panic!("shouldn't happen or structopt failed to ensure some option was set");
```

which gets really annoying super fast.

**Comment by TeXitoi** [comment]
A more appropriate pattern for this use case is https://github.com/TeXitoi/structopt/blob/master/examples/enum_in_args.rs but that's a different interface.
