### ISSUE TITLE
Outdated clippy `redundant_closure ` comment in code?

### ISSUE THREAD

**Issue by Phrohdoh** [TeXitoi/structopt#232]
Is [this comment] outdated and able to be removed?

Stable rust is currently `1.37.0` and https://github.com/rust-lang/rust-clippy/pull/3816 has been merged.

[this comment]: https://github.com/TeXitoi/structopt/blob/236381545d871010606583fdcfe88908d44872ac/structopt-derive/src/lib.rs#L121-L127

**Comment by TeXitoi** [comment]
Minimum rustc version is 1.34 for thé upcomming 0.3 structopt. Juste updating this to remove this comment  is against out minimum ristc policy described un thé readme. That's noy a problematic thing, thus we van keep it to support thé 1.34 users.

**Comment by TeXitoi** [comment]
Sorry, mobile auto correction.

**Comment by Phrohdoh** [comment]
Ok so the issue is the min rust dep, not 1.35.0 being released.
Please feel free to close if you'd like.

**Comment by TeXitoi** [comment]
Thanks for reporting

**Comment by TeXitoi** [comment]
FYI that's now removed.
