### ISSUE TITLE
Support for global arguments

### ISSUE THREAD

**Issue by asafigan** [TeXitoi/structopt#237]
I am interested in using global arguments ([reference](https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.global)). Would this be hard to add? It would really help clean up my cli.

**Comment by TeXitoi** [comment]
Can you add an exemple of what you are expecting?

**Comment by asafigan** [comment]
I would expect it to work like long with no argument

```rust
#[derive(StructOpt)]
#[structopt(name = "app")]
struct Cli {
    #[structopt(global, long)]
    global_argument: String
}
```

**Comment by TeXitoi** [comment]
The point of the `global` arguments feature has 2 sides:
 - allowing `bin cmd --verbose` and having `--verbose` at the level of the bin, not `cmd`
 - having in the `cmd` subcommand matches the `verbose` flag present.

The first point already work with structopt:

```rust
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(global = true)]
    verbose: bool,
    #[structopt(subcommand)]
    cmd: Cmd,
}

#[derive(StructOpt, Debug)]
#[structopt(rename_all = "kebab")]
enum Cmd {
    Cmd,
    Command,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

The second point is much more complicated, and I don't see how to include this functionality within structopt.

**Comment by CreepySkeleton** [comment]
@TeXitoi I'm pretty sure @asafigan knows about `global = true` and just asking to add `global` method with no arg that is shortcut for `global = true`

**Comment by TeXitoi** [comment]
I don't think changing `global = true` to `global` will "really help clean up [his] cli". Thus I suspect he doesn't know that is can be used as is or that he want something for the 2nd feature.

**Comment by CreepySkeleton** [comment]
@TeXitoi By the way, I don't understand what you mean by 
> having in the cmd subcommand matches the verbose flag present.
Could you please explain?

**Comment by TeXitoi** [comment]
In clap, using the global feature, when you have the `matches` object of the subcommand (that is more or less the `Map<String, Vec<String>>` corresponding to the parsing of the subcommand), you have access to the global flag. That may translate in structopt to adding the `global` flag to each subcommand struct, that is not really possible.

**Comment by asafigan** [comment]
Wait? Sorry, I thought I tried `global = true`. Just tried it again and it worked sorry for the confusion. I will try and search the documentation more before submitting an issue next time.

**Comment by TeXitoi** [comment]
No problem, better to ask than to skip interesting features!
