### ISSUE TITLE
New release with syn 1.0

### ISSUE THREAD

**Issue by kpcyrd** [TeXitoi/structopt#238]
hey! I'm looking forward to the next release with syn, proc-macro2 and quote 1.0 now that #227 is merged. Please let know when this change is released! :)

**Comment by CreepySkeleton** [comment]
One - two days, maybe even today. @TeXitoi cc

**Comment by CreepySkeleton** [comment]
And pay attention: this is going to be 0.3 version, with a number of breaking changes. you may need to adjust your code - mostly by simplifying :)

**Comment by TeXitoi** [comment]
I think I want to change the mimimum rustc version to 1.36 (i.e. not the last one, but the one before) to not have to do a breaking change if we need this version. @CreepySkeleton what do you think? If you agree, I can do that now and publish 0.3 within the hour.

**Comment by CreepySkeleton** [comment]
Out of curiosity: what would we need this version for? You seem to have something in mind for it already :) And no - I have no objection against

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/structopt/blob/236381545d871010606583fdcfe88908d44872ac/structopt-derive/src/lib.rs#L121

And maybe something other that I have no idea right now

**Comment by CreepySkeleton** [comment]
Bump minor version by 2 just to remove a comment - I like it, quite radical :smile:. Let's  do it

**Comment by TeXitoi** [comment]
0.3 published
