### ISSUE TITLE
Inherit no_version for enum variants

### ISSUE THREAD

**Issue by dtolnay** [TeXitoi/structopt#242]
In my non-Cargo build environment I end up with a lot of noise from no_version attributes. For subcommands, if the outer enum is no_version I think I shouldn't need to specify no_version as well for each of the command variants.

Currently `derive(StructOpt)` produces an error if any of the no_version attrs here are removed:

```rust
use structopt::StructOpt;

#[derive(StructOpt)]
#[structopt(no_version)]
enum Show {
    #[structopt(no_version)]
    Stats,
    #[structopt(no_version)]
    Capacity,
}
```

**Comment by CreepySkeleton** [comment]
I agree. @TeXitoi what do you think? 

By the way, @dtolnay , I wonder what non-cargo environment you're working with?

**Comment by CreepySkeleton** [comment]
By the way, it looks like a bug - `#[structopt(no_verison)]` should not (and need not to) be usable on enum variants, only on top of the struct or enum

**Comment by TeXitoi** [comment]
That's because the enum can be transformed to a `clap::App`, and that each enum is a subcommand that also generate a `clap::App`.

**Comment by CreepySkeleton** [comment]
I'll see if we can catch this situation. I also think that `no_version` should be propagated down to subcommands - if we don't want version for the program itself why would we wan a version for subcommands?

**Comment by CreepySkeleton** [comment]
@TeXitoi so what do you think about it? It can be implemented almost for no effort.

**Comment by TeXitoi** [comment]
Then OK for it
