### ISSUE TITLE
methods are not allowed for skipped fields when using multi-line doc comments

### ISSUE THREAD

**Issue by DianaNites** [TeXitoi/structopt#245]
Title. Structopt 0.3.0 errors out with `methods are not allowed for skipped fields` if skipped fields have doc comments, but only multi-line ones.

Repro:

```rust
#[derive(StructOpt)]
struct Example {
    /// This does an internal thing.
    /// Run-on sentence explanation.
    #[structopt(skip)]
    works: String,

    /// This does another internal thing.
    ///
    /// # IMPORTANT NOTE
    #[structopt(skip)]
    fails: String,
}
```

**Comment by TeXitoi** [comment]
Should also exists in 0.2, that's because we generate a long_help when we detect a paragraph.

**Comment by CreepySkeleton** [comment]
Perhaps we need to completely separate auto-generated stuff from explicitly requested.

**Comment by CreepySkeleton** [comment]
> Should also exists in 0.2, that's because we generate a long_help when we detect a paragraph.

Changelog says `skip` was introduced in 0.3
