### ISSUE TITLE
Changelog for optional vectors may have wrong example for old behaviour

### ISSUE THREAD

**Issue by AluisioASG** [TeXitoi/structopt#249]
From the changelog; issue in comments:

> If you need to fall back to the old behavior you can use a type alias:
> 
> ```rust
> type Something = Vec<String>; // Not actually used
> #[derive(StructOpt)]
> struct Opt {
>   #[structopt(long)]
>   fruit: Option<Vec<String>>, // Shouldn't this be `Option<Something>`?
> }
> ```

**Comment by CreepySkeleton** [comment]
That's right, thanks for reporting
