### ISSUE TITLE
Help text is only taken from the last line of doc comments

### ISSUE THREAD

**Issue by boustrophedon** [TeXitoi/structopt#25]
If you have something like
```rust
#[derive(StructOpt, Debug)]
struct Args {
    /// Doc comment: First line
    /// Doc comment: Second line
    parameter: String,
}
```

the help text for `parameter` will be "Doc comment: Second line". This is a problem when you have a long help text, but you want to keep a reasonable line length.

**Comment by boustrophedon** [comment]
Awesome thanks!

**Comment by TeXitoi** [comment]
Welcome.
