### ISSUE TITLE
Using third party structs and annotate them

### ISSUE THREAD

**Issue by SirWindfield** [TeXitoi/structopt#253]
Is it somehow possible to use a struct from another crate and annotate it somehow to make it work with structopt? Something like this?

```rust
use other_crate::ConnectionConfig;

#[derive(StructOpt)]
struct Config {
    #[structopt(long)]
    field_name_1: i32,

    #[structopt(long)]
    field_name_2: String,

    #[structopt(long, flatten)]
    connection_config: ConnectionConfig,
}
```

The only solution I came up with was to basically re-define the same struct with the same fields and annotate them on my part. Then passing the values into the other libraries config.

```rust
use other_crate::ConnectionConfig;

#[derive(StructOpt)]
struct Config {
    #[structopt(long)]
    field_name_1: i32,

    #[structopt(long)]
    field_name_2: String,

    #[structopt(long)]
    field_from_struct_1: i32,

    #[structopt(long)]
    field_from_struct_2: String,
}

fn main() {
    let config = Config::from_args();
    let other_config = ConnectionConfig {
         field_from_struct_1: config.field_from_struct_1,
         field_from_struct_2: config.field_from_struct_2,
    };
}
```

**Comment by CreepySkeleton** [comment]
The field's type being flattened must derive/implement `Structopt`, no matter  what crate it's from

**Comment by SirWindfield** [comment]
Well, that closes up my question. Thanks!

**Comment by CreepySkeleton** [comment]
@TeXitoi we also could support external structs in [`serde_derive`-like style](https://serde.rs/remote-derive.html)

**Comment by SirWindfield** [comment]
That actually looks super interesting! I didn't know that this was possible.

**Comment by CreepySkeleton** [comment]
>  I didn't know that this was possible

@SirWindfield That's not possible in structopt for now, let's see what's the big guy has to say

**Comment by TeXitoi** [comment]
Looks like a lot of work for little to no benefices.

**Comment by CreepySkeleton** [comment]
@TeXitoi I personally agree, it doesn't look like a common request. We may want to ask on reddi or something
