### ISSUE TITLE
clippy warning when using structopt

### ISSUE THREAD

**Issue by SirWindfield** [TeXitoi/structopt#262]
I am getting some clippy warnings as of lately. The CI server spits out the following:

```
warning: returning the result of a let binding from a block
   --> src/config.rs:147:26
    |
147 | #[derive(Debug, Default, StructOpt)]
    |                          ^^^^^^^^^
...
171 |     #[structopt(flatten)]
    |                 ------- unnecessary let binding
    |
    = note: #[warn(clippy::let_and_return)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
```

The mentioned line can be found [here](https://github.com/Spotifyd/spotifyd/blob/cdd3bce48ac085dd3f60db8fb20df2d8d5e949db/src/config.rs#L147), but as far as I can tell there is nothing wrong with it.

**Comment by CreepySkeleton** [comment]
Yep, the code generated may be sometimes somewhat complicated and redundant. We'll fix this warning in v0.3.2

**Comment by TeXitoi** [comment]
I was thinking clippy should not warn in code generated by proc macro anymore, no?

**Comment by CreepySkeleton** [comment]
@TeXitoi Nope, according to [this thread](https://github.com/rust-lang/rust-clippy/issues/702) clippy-guys (I hope that's the correct tittle) suggest to insert some `#[allow(clippy::whatever)]` into generated code to suppress them. This is what I propose we're doing
