### ISSUE TITLE
Unnecessary name sanitisation

### ISSUE THREAD

**Issue by Fiedzia** [TeXitoi/structopt#265]
Clap has no problem with subcommand names starting with colon.
I need this to namespace them (users will be able to create their own, so I want standard ones not to clash witht them.

However something in structopt removes them (and anything that's not a letter) from beginning and end of subcommand name. This seems accidental.

**Comment by CreepySkeleton** [comment]
It seems like influence of `rename_all`.

**Comment by TeXitoi** [comment]
That's a feature, but you can use
```rust
#[structopt(rename_all = "verbatim")]
```
to manage the names by hand.

**Comment by CreepySkeleton** [comment]
@TeXitoi That's right, but I never thought that dots `.` or other punctuation marks should be renamed by this, `rename_all` meant to rename `SomeCase` to `some-case` and the like?

**Comment by CreepySkeleton** [comment]
Err, wait, there's no way to start a name with a colon except for explicit `name = ":asda"`. @Fiedzia do you already do this?

**Comment by Fiedzia** [comment]
I am explicitely setting name with name=":somevalue", that doesn't work.
rename_all = "verbatim" does work.

This behavior was surprising though, especially that using clap directly doesn't do that.

**Comment by CreepySkeleton** [comment]
> but it's technically a breaking change.

Technically - yes, it is, but I highly doubt that much user has been relying on this change. We should really ask on `users.rust-lang.org` or `reddit`

**Comment by CreepySkeleton** [comment]
@TeXitoi I think this is basically a bug, and semver states that bugfixes does not require major version bump.

I'd like to conduct a survay on users.rust-lang.org, do you mind?

**Comment by TeXitoi** [comment]
I'm OK with doing it even without asking, but feel free to ask if you prefer to be sure.

**Comment by CreepySkeleton** [comment]
@TeXitoi this is closed too
