### ISSUE TITLE
help text wrong for number_of_values=1

### ISSUE THREAD

**Issue by metajack** [TeXitoi/structopt#267]
For a field defined like:
```
    #[structopt(long="package", short="p", name="name", number_of_values=1)]
    roots: Vec<String>,
```

The help text implies you can specify multiple values per option:
```
    -p, --package <name>...
```

It should probably remove the `...` in this case. Is there anyway to work around this right now?

**Comment by TeXitoi** [comment]
`multiple = false` maybe.

Why not just use `roots: String,`?

**Comment by metajack** [comment]
I'm trying to support `-p package1 -p package2` just like the Cargo syntax.

**Comment by TeXitoi** [comment]
https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.multiple

Looks like you're doing the good thing. I think that's wanted by clap to add this `...` to show that you can use this parameter multiple times. If you suspect that's a bug, please open one in clap and link it to here.

**Comment by CreepySkeleton** [comment]
@metajack  This is entirely about `clap`, `structopt` has nothing to do with it. You should move this issue there.

**Comment by metajack** [comment]
Moved
