### ISSUE TITLE
A question on how to accomplish stdin piping with required switches.

### ISSUE THREAD

**Issue by schplat** [TeXitoi/structopt#268]
I'm building a command line app that requires a list of nodes be supplied.  I'm using a group with a requirement.  I have -n and -f and one of the two is required.  -n is a comma separated list of nodes, -f makes an external call to generate a comma separated list based on a filter query. -c is arbitrary text that applies to those nodes.

I want to set it up such that I can pass stdin into the app, with the result that:

`cliapp -n foo,bar,baz -c 'arbitrary text'`

is the same command as:

`echo "foo,bar,baz" | cliapp -c 'arbitrary text'`

where stdin is passed arguments for -n.  Basically if stdin len > 0, then run the command with -n stdin().read_line(), but satisfy the requirement that -n or -f has been provided
Or is the only way to make this happen is with:

`echo "foo,bar,baz" | cliapp -c 'arbitrary text' -n -` ?

Or can I somehow make stdin a member of the structopt group?  Then from that I can populate the variable that -n populates from there.  Snippets of what I have working so far (as a note, eventually -n and -f will be made mutually exclusive):

```
extern crate structopt;
extern crate structopt_derive;

use structopt::clap::ArgGroup;
use structopt::StructOpt;
```
```
#[structopt(name="cliapp",
            group = ArgGroup::with_name("nodelist").required(true)]
```
```
    #[structopt(short = "n",
                long = "nodes",
                group = "nodelist")]
    nodes: Option<String>,

    #[structopt(short = "f",
                long = "filter",
                group = "nodelist")]
    filter: Option<String>,
```

**Comment by TeXitoi** [comment]
I'm not sure I really understand the question but I try to respond. If I misunderstand, please connect me.

Structopt can only handle command line parsing, not reading stdin in some case. But you can integrate that using some impl on the struct.

For example, you can do something like that (that's just an idea, you can adapt to your case):

```rust
struct Opt {
    #[structopt(...)]
    nodes: Option<String>,
    #[structopt(...)]
    filter: Option<String>
    #[structopt(skip)]
    real_nodes: Vec<String>,
}
impl Opt {
    fn init(&mut self) {
        if let Some(n) = &self.nodes {
            self.real_nodes = parse_nodes(n)
        } else if let Some(f) = &self.filter {
            self.real_nodes = parse_filter(f);
        } else {
            self.real_nodes = parse_from_stdin();
        }
    }
    fn nodes(&self) -> &[String] {
        &self.real_nodes
    }
}
```

**Comment by schplat** [comment]
I think you mostly got it.  I'm still in the learning phase, and keep forgetting what I can do at times, so it just didn't occur to me to follow up the struct with an impl.  I can definitely use a variation of the above (the structopt(skip) helps my thinking around this as well, especially around later parse_* extensions, for when we change inventory backends).

Thanks for taking the time to answer, it is much appreciated.
