### ISSUE TITLE
Support clap-rs number_of_values change

### ISSUE THREAD

**Issue by daaku** [TeXitoi/structopt#27]
With a recent [clap-rs](https://github.com/kbknapp/clap-rs/commit/0c223f54ed46da406bc8b43a5806e0b227863b31) change comes an api which makes args with `multiple(true)` work better in the presence of subcommands. It would be great if there was a way to enable this.

**Comment by TeXitoi** [comment]
With `cargo update`, you'll update clap to its latest version. You'll have the new way. If you need to tune that, with the latest structopt, you can use the `_raw` feature implemented in #23.

Does it fixes your needs ?

**Comment by daaku** [comment]
Yep, that feature very nicely solves the problem -- thanks!
