### ISSUE TITLE
Add support for negative boolean flags

### ISSUE THREAD

**Issue by vmalloc** [TeXitoi/structopt#280]
Apologies if this is a duplicate or has already been requested -- but it would be nice to have a way to set a boolean flag which defaults to `true` unless it is given (e.g. `--no-do-something` would set the `do_something` field to `false`, otherwise it would be `true`)

**Comment by CreepySkeleton** [comment]
That would be `clap`'s feature, you should open an issue there instead. Typically, if you have a feature request that adds some functionality to `clap::App/Arg` you should go there, not here. If it would require explicit support in `structopt` we'll be happy to do that but we need it implemented in `clap::Arg` in the first place.  

By the way, there's [such a request](https://github.com/clap-rs/clap/issues/815) already, feel free to send a PR.

**Comment by TeXitoi** [comment]
As of today, you can also do the machinery by hand, I.e. creating a no-do-something flag on a do_something field, with a custom from_flag.

I'm on mobile, I'll try to write such an example within the day.

**Comment by vmalloc** [comment]
@CreepySkeleton I see. Thanks for the reply, and sorry for the spam!

**Comment by TeXitoi** [comment]
```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(long = "no-verbose", parse(from_flag = std::ops::Not::not))]
    verbose: bool,
}
fn main() {
    let cmd = Opt::from_args();
    println!("{:#?}", cmd); 
}
```

**Comment by vmalloc** [comment]
@TeXitoi awesome! Going to add it to my personal cookbook. That is exactly what I needed.

Thank you very much!

**Comment by TeXitoi** [comment]
Example proposed in #281

**Comment by ryuta69** [comment]
@TeXitoi 
Hi, thank you for your great example.

I have an question, can I use switching flag...?

```
    #[structopt(long = "verbose")]
    #[structopt(long = "no-verbose", parse(from_flag = std::ops::Not::not))]
    pub verbose: bool,
```

Looking at an issue https://github.com/TeXitoi/structopt/issues/126, it looks not implemented yes.
But the issue is two years ago, so I wonder it actually implemented now.

**Comment by TeXitoi** [comment]
It's not. But you can do with 2 field, a verbose and a quiet, and implement a getter on your struct that read the 2 fields to decide what to return.

**Comment by ryuta69** [comment]
@TeXitoi 
Thank you for answer.
I got it. Thank you very much!
