### ISSUE TITLE
`version = expr` ignored, and incorrectly uses `env!(CARGO_PKG_VERSION)`

### ISSUE THREAD

**Issue by matsadler** [TeXitoi/structopt#283]
Setting `#[structopt(version = expr)]` (where `expr` is any expression, but not a literal) the expression is ignored and `env!(CARGO_PKG_VERSION)` is used instead.

It looks like the problem is `clap::App::version` is being called twice, first time with `expr`, and second time with the value of `CARGO_PKG_VERSION`, and the second call wins. In the expanded macro output I'm seeing something like:

``` rust
let app = ::structopt::clap::App::new("example")
    .version(VERSION)
    .version("0.1.0");
```

Here is a reduction of my code that's seeing the problem:

``` rust
use structopt::StructOpt;

const VERSION: &str = "custom version";

#[derive(StructOpt)]
#[structopt(version = VERSION)]
pub struct Opts {}

fn main() {
    let _ = Opts::from_args();
}
```

As a workaround I can set `#[structopt(no_version, version = VERSION)]` and get the result I want, although looking at [structopt_derive::attrs::Attrs::top_level_methods][tlm] it doesn't look like this was intended to work.

[tlm]: https://github.com/TeXitoi/structopt/blob/b5907e8996d39d2bcecd5aeb04466a256611eb9e/structopt-derive/src/attrs.rs#L591

**Comment by CreepySkeleton** [comment]
Right, we'll fix it sometime this week
