### ISSUE TITLE
'infer subcommand' doesn't work with nested subcommands

### ISSUE THREAD

**Issue by danieleades** [TeXitoi/structopt#289]
When `InferSubcommands` is enabled, subcommand inference only works for the top level of subcommands- to call nested subcommands the entire command must be written out.

```rust
use structopt::{StructOpt, clap::AppSettings};

#[derive(StructOpt)]
#[structopt(setting = AppSettings::InferSubcommands)]
enum Args {
    SomeCommand(SubSubCommand),
    AnotherCommand,
}

#[derive(StructOpt)]
#[structopt(setting = AppSettings::InferSubcommands)]
enum SubSubCommand {
    TestCommand,
}

fn main() {
    let args = Args::from_args();
}
```

- `cargo run some-command test-command` *works*
- `cargo run some test-command` *works*
- `cargo run some-command test` *doesn't work*
- `cargo run some test` *doesn't work*

i've tried both the above syntax, and explicitly marking with the `#[structopt(subcommand]` tag.

**Comment by CreepySkeleton** [comment]
This is the same problem as #151 , the same fix should apply
