### ISSUE TITLE
Enable subcommand of subcommand

### ISSUE THREAD

**Issue by NotBad4U** [TeXitoi/structopt#29]
Actually when I try to implement a cli with nested subcommands like this exemple:  
``` bash
git_command 0.9999.0

SUBCOMMANDS:
    commit   subcommands relative to commit  
    issue       subcommands relative to issues
``` 
Where the commit, issue has there own subcommands too:
`git_command commit list --filter`

I tried to implement with enums nested :
``` rust
#[derive(StructOpt)]
#[structopt(name = "git")]
struct Cmd {
    #[structopt(subcommand)]
    subcommand: SubCommand,
}
#[derive(StructOptSubCommand)]
enum SubCommand {
     #[structopt(name = "issue")]
    Issue(Issue),
    #[structopt(name = "commit")]
    Commit(Commit),
}

#[derive(StructOpt)]
enum Commit {
    List {filter: Option<String>},
}

#[derive(StructOpt)]
enum Issue {
    ...
}
```
But I'm getting this "derive" error: 
> enum variants cannot be tuples

There is a current way to implement this or it's a missing feature ?

**Comment by TeXitoi** [comment]
You can't (at least now, but that's quite ambiguous as you described, thus I'm not sure I what such an evolution) directly use an enum 1-uple to specify subsubcommand.

You'll need a bit more, something like that:

```rust
#[derive(StructOpt, PartialEq, Debug)]
enum SubSubCmdWithOption {
     #[structopt(name = "remote")]
    Remote {
        #[structopt(subcommand)]
        cmd: Option<Remote>
    },
    #[structopt(name = "stash")]
    Stash {
        #[structopt(subcommand)]
        cmd: Stash
    },
}
#[derive(StructOpt, PartialEq, Debug)]
enum Remote {
     #[structopt(name = "add")]
    Add { name: String, url: String },
     #[structopt(name = "remove")]
    Remove { name: String },
}

#[derive(StructOpt, PartialEq, Debug)]
enum Stash {
     #[structopt(name = "save")]
    Save,
     #[structopt(name = "pop")]
    Pop,
}
```

For your information, while trying to answer your question, I've found a bug and fixed it https://github.com/TeXitoi/structopt/commit/227d1fa73c375b0479e182fb041b1a8630d29f0a

There is another example in the tests: https://github.com/TeXitoi/structopt/blob/master/tests/nested-subcommands.rs
