### ISSUE TITLE
Ability to have positionals interspersed with non-positionals?

### ISSUE THREAD

**Issue by vmalloc** [TeXitoi/structopt#309]
Is there a way to make a program accept the following:
```
$ ./executable --flag <arg>
```
as well as:
```
$ ./executable <arg> --flag
```
were `flag` is a boolean (i.e. no confusion around <arg> being its value) and `arg` is a positional?

If not, would it be possible to add such a capability?

**Comment by CreepySkeleton** [comment]
This works out of box since clap does know that flags don't take any value, nobody's getting confused 
```rust
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
struct Opts {
    #[structopt(long)]
    flag: bool,

    arg: String
}


fn main() {
    let opt = Opts::from_args();
    println!("{:?}", opt);
}
```

```sh
$ cargo run -- --flag yahoo
Opts { flag: true, arg: "yahoo" }

$ cargo run -- yahoo --flag
Opts { flag: true, arg: "yahoo" }

$ cargo run -- yahoo
Opts { flag: false, arg: "yahoo" }

**Comment by vmalloc** [comment]
@CreepySkeleton oh you are right! For some reason I was sure it didn't work for me earlier. Thanks!
