### ISSUE TITLE
It must be possible to not call author and about clap method

### ISSUE THREAD

**Issue by Boscop** [TeXitoi/structopt#31]
StructOpt will always call to author and about method. There should be a way to avoid these call. The goal is that if the value is the empty string, no call will be performed.

The issue originally was:

Order of args in --help should be in the order that fields appear in the options struct.
E.g. I want to have `-i` shown before `-o` in `--help`, but even though I put it before it in the struct, it appears after it in `--help`, why?

**Comment by TeXitoi** [comment]
StructOpt doesn't do anything about that, clap does.

You want that: https://docs.rs/clap/2.27.1/clap/enum.AppSettings.html#variant.DeriveDisplayOrder

Using structopt:
```rust
extern crate clap;
extern crate structopt;
#[macro_use]
extern crate structopt_derive;

use structopt::StructOpt;

#[derive(StructOpt, Debug)]
#[structopt(setting_raw = "clap::AppSettings::DeriveDisplayOrder")]
struct Opt {
    #[structopt(short = "s")]
    speed: bool,
    #[structopt(short = "d")]
    debug: bool,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

It gives:
```
$ cargo run -- -h
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/test -h`
test 0.0.1
Guillaume Pinot <texitoi@texitoi.eu>


USAGE:
    test [FLAGS]

FLAGS:
    -s               
    -d               
    -h, --help       Prints help information
    -V, --version    Prints version information
```

Does it answer your question?

**Comment by Boscop** [comment]
Thanks!

Is there also a way to display the ARGS before OPTIONS and FLAGS?
Both in the USAGE line but also in the detailed list below.

**Comment by TeXitoi** [comment]
I can't find any similar feature in clap.

**Comment by TeXitoi** [comment]
By convention, ARGS will always be at the end on the USAGE line, because you can use `--` to say "finish with options/flags, only args now" to be able to have args begining with a `-` (as used in my invocation of `cargo run` just above).

Thus, I think clap will not allow such a thing.

**Comment by Boscop** [comment]
Ah ok, and how can I not include the about or author info in structopt?

**Comment by mattiasb** [comment]
Sorry for chiming in, but just to be sure: @Boscop did you check the Clap documentation for how to do it there? If yes and it is indeed possible to perform it with Clap, what troubles did you have translating that into StructOpt?

**Comment by Boscop** [comment]
In clap it's done with `.author(..)` and `.about(..)`, but Structopt generates the code calling `.author(..)` and `.about(..)`. How can I tell it to not generate these calls?

**Comment by Boscop** [comment]
If I pass `author=""` it calls `.author("")` (and it generates `.about("")` if my Cargo.toml description is not set). So those are two additional empty lines between the line containing `<program name> <version>` and `USAGE` (in the output of `--help`).  So 3 empty lines in total (if both `author` and `about` are set there is 1 line as space).

How can I tell Structopt to not do these calls if the strings are empty?

**Comment by TeXitoi** [comment]
You're right, that's not possible for the moment. I'll manage the case empty string to not call the clap method on author and about.

**Comment by TeXitoi** [comment]
v0.1.6 published

**Comment by Boscop** [comment]
Thanks!

**Comment by Boscop** [comment]
I just switched from 0.1 to 0.2 and this doesn't work anymore: 
`#[structopt(setting_raw = "clap::AppSettings::DeriveDisplayOrder)]"`

What's the right way to do this now?

**Comment by TeXitoi** [comment]
The changelog explain everything.

Here, that's `raw(setting ="..."))`
