### ISSUE TITLE
[BUG] from_occurrences with a String as the destination type for T requires a value be passed in with the flag

### ISSUE THREAD

**Issue by yaahc** [TeXitoi/structopt#318]
I would like to setup my app to allow setting the verbosity level via `-vv` style flags with `from_occurrences` as the parse strategy, and the documentation made it seem like it should be possible to set the parser fn to a custom fn via `parse(from_occurrences = to_envfilter)` where `to_envfilter` is a custom function i defined with the signature of `fn(u64) -> String`.

I set it up like so.

```
fn to_envfilter(count: u64) -> String {
    let level = match count {
        0 => "error",
        1 => "warn",
        2 => "info",
        3 => "debug",
        4 => "trace",
        _ => {
            tracing::warn!(
                "Trace is the highest supported verbosity level. extra -v's will be ignored"
            );
            "trace"
        }
    };

    format!(
        "scdev={0},scale={0},scmake={0},sctest={0},gsync={0},tb={0}",
        level
    )
}

// ...

    #[structopt(short, long, parse(from_occurrences = to_envfilter), env = "RUST_LOG", set = Global)]
    pub verbosity: String,

// ...
```

And this works! Almost

This renders the help like so

```
    -v, --verbosity <verbosity>...         [env: RUST_LOG=]
```

notice that it requires a value for verbosity

```
❯ scdev sync -v
error: The argument '--verbosity <verbosity>...' requires a value but none was supplied

USAGE:
    scdev sync --host <host> --remote <remote> --verbosity <verbosity>...

For more information try --help
```

if I pass in multiple v's it no longer errors but it seems to parse the extra v's as the input rather than as extra occurrences of the flag, so writting `scdev test -vv` gives me occurrences = 1, and `scdev test -vv -vv` gives me occurrences = 2

If I pass in garbage after each v it works exactly how you'd expect, `scdev test -v 1 -v 1 -v 1` gives me 3 occurrences and brings me up to debug logging.

**Comment by CreepySkeleton** [comment]
The problem here is: `Arg::env` sets implicitly `takes_value(true)`, I explained it in detail [here](https://github.com/TeXitoi/structopt/issues/305#issuecomment-564593163). 

This is [known problem in `clap`](https://github.com/clap-rs/clap/issues/1476), and, unfortunately, there's no workaround or fix as far as I'm aware. We can't do anything in `structopt` to fix it, it must be done in clap.

**Comment by CreepySkeleton** [comment]
Like this:
```rust
use structopt::{StructOpt, clap::ArgSettings};

fn to_envfilter(count: u64) -> String {
    let level = match count {
        0 => "error",
        1 => "warn",
        2 => "info",
        3 => "debug",
        _ => "trace"
    };

    format!(
        "scdev={0},scale={0},scmake={0},sctest={0},gsync={0},tb={0}",
        level
    )
}

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(
        short,
        long,
        parse(from_occurrences = to_envfilter),
        set = ArgSettings::Global)
    ]
    verbosity: String,

    #[structopt(long, hidden = true, env = "RUST_LOG")]
    vers_str: Option<String>
}


fn main() {
    let mut opt = Opt::from_args();
    if let Some(s) = opt.vers_str {
        opt.verbosity = s;
    }
    /// ...
}
```

**Comment by CreepySkeleton** [comment]
And a hint: use `Arg::global(true)` instead of explicit `Arg::set(Global)`

**Comment by yaahc** [comment]
I opted to instead let the my logger silently grab from the env and use the flag if RUST_LOG is not set. The main reason for me wanting to use the env fall back was just because it displays more context about how you can interact with the log level in the `--help` output so having a hidden arg that lets you set it would indeed work but kinda defeats the thing I was trying to do. I might still go with the two args option and just not hide the second one though, that is a good idea.

I'm sorry to hear its a problem in clap, thank you for such a detailed explanation and for the suggestions!
