### ISSUE TITLE
Replace one big docs.rs page with a book

### ISSUE THREAD

**Issue by CreepySkeleton** [TeXitoi/structopt#319]
Right now, `structopt`'s documentation is nothing more than just a one big page on docs.rs. 

While this approach has some advantages, namely:

* One big page makes it easier to search via `Ctrl+F`.
* Code snippets can be tested with simple `cargo test`.

It also has a great number of disadvantages:

* Such a huge page isn't really easy to navigate. `Ctrl+F` will help you only if you know what you need *exactly*, otherwise you are doomed to scroll up and down until you happen to stumble on the right topic.
* Our artificial TOC isn't really helpful since it's placed only at the beginning of the page, once you hit a tittle you have no easy way back, you're going to have to scroll. 
* `rustdoc` does not verify links.
* We can't tweak the theme ("Important" blocks look ugly and don't really attract attention).
* We can't fix typos without publishing a new version (this is arguable).

Thus, I propose to make a book via [`mdbook`](https://github.com/rust-lang/mdBook) and publish it via github pages. Tt addresses all the disadvantages above:

* Built-in search, works *great*.
* Built-in TOC, looks awesome.
* We can verify links via [mdbook-linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck), integration is trivial.
* We can inject any `.css` styles we please.
* We can update it whenever we wish (the question is, should we?).
* Testing is possible via [`skeptic`](https://github.com/budziq/rust-skeptic), integration is pretty easy.

In fact, I already made a [test repo](https://github.com/CreepySkeleton/structopt-book-test.github.io), and published it on [github pages](https://creepyskeleton.github.io/structopt-book-test.github.io/).

What do you think?

**Comment by TeXitoi** [comment]
Having the doc on docs.rs is easier to find, and needed. We must be careful to have a good doc here whatever we do around.

A mdbook can be a plus, but it can't replace completely the doccomments.

**Comment by CreepySkeleton** [comment]
> but it can't replace completely the doccomments.

It can't, and it won't. 

Doc comments are superb at documenting *items*: the `StructOpt` trait, modules, the crate itself. They are so wonderful at this task because they offer crosslinks out of box, you can just look at the function signature, click on some type within it, and, congrats!, you are reading the docs for this type now. 

But the situation is completely different for proc-macros and their attributes in particular. They don't have any builtin links, they have no logical structure and the only way to document them is the plain text with manually crafted links. `rustdoc` doesn't offer anything for proc-macros.

So, every single proc-macro's documentation on docs.rs is doomed to grow and grow and grow, until it's so large that it's basically unnavigatable. 

What I'm proposing is pretty much the same, but logically separated into different pages, which is much easier to both read and navigate. 

If you are concerned that the book would be undiscoverable - well `serde` has the same [summary on docs.rs + book](https://docs.rs/serde) solution; the link to the book is present in the first paragraph. We could render it bold so it's more attractive.

**Comment by TeXitoi** [comment]
OK, but if clap v3 will be out in a "short" time, maibe that's better to focus on it.

**Comment by CreepySkeleton** [comment]
Hmm, to focus on releasing clap 3 or making a book?

**Comment by TeXitoi** [comment]
To write the book for clap and not structopt.

**Comment by CreepySkeleton** [comment]
Agreed. I'm transferring the issue.

**Comment by CreepySkeleton** [comment]
No, I'm not transferring the issue because I simply can't :( I'll figure it out later.
