### ISSUE TITLE
Support TOML and env vars parsing

### ISSUE THREAD

**Issue by bestouff** [TeXitoi/structopt#32]
Hi,
Structopt is really nice, but to have a complete solution what would be good is to also support TOML and env vars parsing (think [12-factor apps](https://12factor.net/config)).

**Comment by TeXitoi** [comment]
That's not the scope of StructOpt. StructOpt is an interface for clap. If clap implement such functionality, StructOpt will, but StructOpt can't support such a functionality without support from clap.

**Comment by TeXitoi** [comment]
I think it's a very interesting feature, but the feature request is for https://github.com/kbknapp/clap-rs, not StructOpt

**Comment by TeXitoi** [comment]
Related issues:  https://github.com/kbknapp/clap-rs/issues/748

**Comment by bestouff** [comment]
Thanks, I'll have a look at that issue.

**Comment by colemickens** [comment]
Clap supports sourcing values from env vars now. Could this be reconsidered for `structopt`? https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.env

**Comment by TeXitoi** [comment]
Yes, you can use it using `env = "FOO"`
