### ISSUE TITLE
feature request: collect multiple args into other containers than Vec

### ISSUE THREAD

**Issue by nagisa** [TeXitoi/structopt#321]
Custom parsers appear to only go from a single value to another kind of type, but there’s no way to do e.g.

```rust
#[structopt(multiple=true, takes_value=true, ...?)]
something: std::collections::HashSet<...>,
```

that I can see. It becomes necessary to convert from `Vec` to `HashSet` or similar containers after arguments are parsed.

**Comment by TeXitoi** [comment]
Duplicates of #79

**Comment by TeXitoi** [comment]
I agree that it would be a great feature. That's one of the oldest proposition, but we don't have any viable proposition, neither any motivated contributor yet.
