### ISSUE TITLE
Documentation should mention positional arguments explicitly

### ISSUE THREAD

**Issue by vi** [TeXitoi/structopt#33]
I assume it's `Vec<String>`, but help text should explicitly call it "positional arguments" and mandate that it should be the last entry if necessary.

Grepping the word "positional" over crate documentation should in any case find something.

**Comment by TeXitoi** [comment]
That's a positional argument if there is no short nor long a notation. So a strict with 2 strings will require 2 arguments.

I'll improve the doc when I'll have the time. Feel free to open a PR if you're inspired.
