### ISSUE TITLE
clippy warnings with rust 1.40

### ISSUE THREAD

**Issue by dvermd** [TeXitoi/structopt#330]
We're trying to enforce the use of `#![deny(clippy::option_unwrap_used, clippy::result_unwrap_used)]` in our crate and we're hitting warnings triggered by structopt macro expansion.

I looked into the generated code with `cargo expand` and the code contains `#[allow(clippy)]` as fixed in #262. 
I think the problem we're facing is that we use rust 1.40 and according to [readme diff](https://github.com/rust-lang/rust-clippy/commit/83baf8f5fe32fab5dc5e0190cf16ca1d281d4fd5) and [commit](https://github.com/rust-lang/rust-clippy/pull/2977/commits/392235d6e1eec4ab67dd4c14169f134b0ef49118), the generated code should contain `#[allow(clippy::all)]`.

**Comment by dvermd** [comment]
I tested this change more in depth with the new version of the crate and `clippy::all` refers to the clippy categories that are enable by default : `style`, `correctness`; `complexity`, `perf`.
There are other documented categories that may me denied/warned on. These are `pedantic`, `nursery` and `cargo`.
There's also a `restriction` category which `option_unwrap_used` and `result_unwrap_used` belongs to. This one is mentioned on the readme but not intentionally listed as a category by the bullets.
Finally, there's a `deprecated` category intentionally not listed in the readme.

A list of available categories can be seen on the [lint site](https://rust-lang.github.io/rust-clippy/master/index.html)

Can you consider also adding `#[allow(clippy::pedantic, clippy::nursery, clippy::cargo, clippy::restriction)]` to the generated code ?

**Comment by CreepySkeleton** [comment]
Ugh... Why the isn't the world a simple place ruled by Aphrodite?

**Comment by CreepySkeleton** [comment]
A real shame that our MSRV is below 1.37 so we can't generate one big 
```rust
const _: () = {
    // ...
};

**Comment by CreepySkeleton** [comment]
Fixed by #337 , now we suppress all clippy lints except from the `correctness` category.

**Comment by dvermd** [comment]
Thanks for your time, your work and your high reactivity
