### ISSUE TITLE
Possible Values

### ISSUE THREAD

**Issue by Michael-F-Bryan** [TeXitoi/structopt#34]
Is it possible to provide a list of possible values for something? I tried using a string which contains what I'd normally pass to the [possible_values()] method from clap, but got a compile error.

```
   |
41 | #[derive(Debug, Clone, PartialEq, StructOpt)]
   |                                   ^^^^^^^^^ expected slice, found str
   |
   = note: expected type `&[&str]`
              found type `&'static str`

error: aborting due to previous error
```

My example:

```rust
#[derive(Debug, Clone, PartialEq, StructOpt)]
struct Args {

    #[structopt(short = "f", long = "format", default_value = "auto",
                help = "The format checker to use.",
                possible_values = "&[\"fstab\", \"auto\")]")]
    format: Format,
}

#[derive(Debug, Copy, Clone, PartialEq, StructOpt)]
enum Format {
    Fstab,
    Auto,
}

impl FromStr for Format {
    type Err = &'static str;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let as_lower = s.to_lowercase();
        match as_lower.as_str() {
            "auto" => Ok(Format::Auto),
            "fstab" => Ok(Format::Fstab),
            _ => Err("Unknown format"),
        }
    }
}
```

[possible values]: https://docs.rs/clap/2.27.1/clap/struct.Arg.html#method.possible_values

**Comment by TeXitoi** [comment]
You can change `possible_values` by `possible_values_raw` and it'll compile.

But in this case, the FromStr implementation will be used as a validator, thus `possible_values` is not so useful.

**Comment by TeXitoi** [comment]
Also, you don't need to derive SyructOpt on Format. Deriving StructOpt on enum is for subcommands.

**Comment by Michael-F-Bryan** [comment]
> You can change possible_values by possible_values_raw and it'll compile.

Ah that makes a lot of sense. I'm not sure if it was just me not reading the documentation properly but I don't recall seeing anything which says the difference between the `*_raw` attributes and their validated counterparts.

**Comment by TeXitoi** [comment]
That's on the big paragraph just before the table. Do you have any idea to improve comprehension? Maybe put a `_raw` attribute in the example?

**Comment by TeXitoi** [comment]
Added an example about that.
