### ISSUE TITLE
If a help message ends in a single period the period does not show up when printed to the console

### ISSUE THREAD

**Issue by davidMcneil** [TeXitoi/structopt#341]
Example code

```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opt {
    /// This message ends in a period.
    #[structopt(long)]
    arg: u64,
    /// This message ends in two periods..
    #[structopt(long)]
    arg2: String,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}

```
The help message output
```text
USAGE:
    my-bin --arg <arg> --arg2 <arg2>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --arg <arg>      This message ends in a period
        --arg2 <arg2>    This message ends in two periods..
```
Oddly enough it seems to work fine if there are two periods.

**Comment by CreepySkeleton** [comment]
That's right, everything's working as intended. From our documentation: If the first paragraph ends in exactly one period, remove the trailing period We do this because rustdoc best practice is to use complete sentences (do put the period) but --help messages tend to omit the period. So, structopt chops it off. But structopt doesn't touch multiple periods, like ellipses, this is why your "two dot" are preserved.

**Comment by CreepySkeleton** [comment]
This can be prevented with `#[structopt(verbatim_doc_comment)]`.

For the record: I hate github email replies.

**Comment by davidMcneil** [comment]
My bad. Thanks for the reply. I should have searched the docs more closely.

**Comment by CreepySkeleton** [comment]
Gold words! Once I'll have conquered the world, I'll make RTFM the hard and ruthlessly punishable law. And you're welcome!23.01.2020, 23:56, "David McNeil" <notifications@github.com>:My bad. Thanks for the reply. I should have searched the docs more closely.

**Comment by davidMcneil** [comment]
I apologize if I am misunderstanding, but I do not believe `#[structopt(verbatim_doc_comment)` works when applied to a struct field. PR #342 addresses this.

**Comment by obskyr** [comment]
Is there a way to disable this behavior without needing to specify `verbatim_doc_comment` on each individual option?
