### ISSUE TITLE
verbatim_doc_comment should keep trailing blank lines from doc comment in long help 

### ISSUE THREAD

**Issue by zhaojiangbin** [TeXitoi/structopt#344]
It appears that structopt removes _trailing_ blank lines in long help text that is created from doc comment, even with the `verbatim_doc_comment`.

This makes the long help output look inconsistent between the entries defiend by the user and the entries (-h and -V) added by structopt. Trailing blank lines from raw strings with the `long_help` attribute are also not removed by the library.

**Comment by CreepySkeleton** [comment]
Yes, structopt does that so these forms are equivalent.
```rust
/** This is a doc comment

Hello! */

/**
This is a doc comment

Hello!
*/

/// This is a doc comment
///
/// Hello!
```

> This makes the long help output look inconsistent between the entries defiend by the user and the entries (-h and -V) added by structopt.

This is [known problem with clap](https://github.com/clap-rs/clap/issues/1642) and I don't think that a hack like "let's add few trailing lines to cheat clap" is good way to solve it. Let's fix this in clap.

> Trailing blank lines from raw strings with the long_help attribute are also not removed by the library.

And they shouldn't be! `long_help` is a raw method (structopt's terminology, see documentation), structopt has no idea what's inside them, it merely forwards the args to clap, that's all.

**Comment by zhaojiangbin** [comment]
Good to know that there is already an issue open in clap for this.
