### ISSUE TITLE
min_values seems to be ignored

### ISSUE THREAD

**Issue by runfalk** [TeXitoi/structopt#345]
I have a sub command that has a member specified like this:

```rust
#[derive(Debug, StructOpt)]
pub enum Cmd {
    // There are more commande here
    // ...
    Import {
       /// One or more files or directories to import
       #[structopt(parse(from_os_str))]
       paths: Vec<PathBuf>,
    },
}
```

It works when I run `cargo run import path1 path2 path3`. My issue is that it also works when there are no paths provided (`cargo run import`). I expect it to give an error in this case. I've tried to add both `multiple = true` and `min_values = 1`.

If I understand the documentation correctly this is the behaviour for `Option<Vec<PathBuf>>`. Am I misunderstanding the documentation or is this a bug?

**Comment by CreepySkeleton** [comment]
You need `required = true` here.

Also, `Option<Vec<T>>` is pretty much the same as `Vec<T>`, the only difference is - it allows you to distinguish between `--foo <no args>` and `<no option at all>`.
