### ISSUE TITLE
Fatal Internal error when migrating from Clap to StructOpt

### ISSUE THREAD

**Issue by Razican** [TeXitoi/structopt#348]
Hello,
I'm having this error when migrating from `clap` to `structopt`:

<details>
<summary>Backtrace</summary>
<pre>
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', src/libcore/option.rs:1188:5
stack backtrace:
   0:     0x560868b86a94 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x560868b86a94 - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x560868b86a94 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x560868b86a94 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x560868ba8ddc - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x560868b82a67 - std::io::Write::write_fmt::h6808f3d5eceed5e5
                               at src/libstd/io/mod.rs:1426
   6:     0x560868b88c0e - std::sys_common::backtrace::_print::hcc0fd4b3552039ef
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x560868b88c0e - std::sys_common::backtrace::print::h1c9c5c1c0505592d
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x560868b88c0e - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59
                               at src/libstd/panicking.rs:193
   9:     0x560868b88901 - std::panicking::default_hook::h1b037d2bf0657ab3
                               at src/libstd/panicking.rs:210
  10:     0x560868b892eb - std::panicking::rust_panic_with_hook::h787d7f532b084b9a
                               at src/libstd/panicking.rs:471
  11:     0x560868b88e9e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x560868ba567e - core::panicking::panic_fmt::h76b979c035808e69
                               at src/libcore/panicking.rs:84
  13:     0x560868ba56e7 - core::option::expect_failed::h7475be656707bdc0
                               at src/libcore/option.rs:1188
  14:     0x5608682c0ae6 - core::option::Option<T>::expect::hfdc45f92c206d5f5
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:348
  15:     0x560868304866 - clap::app::usage::get_required_usage_from::{{closure}}::h45717b11861e9a29
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/usage.rs:457
  16:     0x5608682b3c0f - core::option::Option<T>::unwrap_or_else::h7dbf4ec74e5ac965
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:422
  17:     0x560868302fc1 - clap::app::usage::get_required_usage_from::hf60c50ca74d34664
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/usage.rs:454
  18:     0x5608682fd889 - clap::app::usage::create_help_usage::hfe9e5f6fd22fcba5
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/usage.rs:71
  19:     0x5608682fd5d4 - clap::app::usage::create_usage_no_title::h5d21df508996d348
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/usage.rs:53
  20:     0x5608682d7f14 - clap::app::help::Help::write_default_help::h39cf54ad7d85f6a7
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/help.rs:757
  21:     0x5608682c78be - clap::app::help::Help::write_help::h8d5a0923cfaee14b
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/help.rs:198
  22:     0x5608682c75cd - clap::app::help::Help::_write_parser_help::h3abb5980868d6bcb
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/help.rs:178
  23:     0x5608682c73c5 - clap::app::help::Help::write_parser_help::h42b91c013915511e
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/help.rs:152
  24:     0x5608683314c8 - clap::app::parser::Parser::_help::h1f57f40db03a23ce
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:1539
  25:     0x560868330f13 - clap::app::parser::Parser::check_for_help_and_version_char::h2b8b304720e32347
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:1502
  26:     0x560868333b8c - clap::app::parser::Parser::parse_short_arg::h0e8e93733c643a8f
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:1712
  27:     0x560868327f8c - clap::app::parser::Parser::get_matches_with::h9d6540e4e533519e
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:947
  28:     0x56086838e34f - clap::app::App::get_matches_from_safe_borrow::h07ddc1e3bb9bb6ba
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/mod.rs:1629
  29:     0x56086838d894 - clap::app::App::get_matches_from::h4d302b7e83785469
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/mod.rs:1509
  30:     0x56086838d7de - clap::app::App::get_matches::heb9d677572bfa1e9
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/mod.rs:1451
  31:     0x56086821af12 - structopt::StructOpt::from_args::h933b32471955b5d1
                               at /home/razican/.cargo/registry/src/github.com-1ecc6299db9ec823/structopt-0.3.9/src/lib.rs:1073
  32:     0x5608682293bc - list_prbs::run::h6bb31186f5e87396
                               at src/main.rs:90
  33:     0x560868228e63 - list_prbs::main::h5ab1431a4ea66eb8
                               at src/main.rs:55
  34:     0x5608682345c0 - std::rt::lang_start::{{closure}}::he25d476a5b5e71ad
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  35:     0x560868b88d33 - std::rt::lang_start_internal::{{closure}}::h0760fb8bd9f1a4c7
                               at src/libstd/rt.rs:52
  36:     0x560868b88d33 - std::panicking::try::do_call::hccaa7cebf2335ab2
                               at src/libstd/panicking.rs:292
  37:     0x560868b8cf2a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  38:     0x560868b89840 - std::panicking::try::h3ce8e2e4440720f0
                               at src/libstd/panicking.rs:270
  39:     0x560868b89840 - std::panic::catch_unwind::h2a767bac361346af
                               at src/libstd/panic.rs:394
  40:     0x560868b89840 - std::rt::lang_start_internal::h14e7168ba039f170
                               at src/libstd/rt.rs:51
  41:     0x560868234599 - std::rt::lang_start::h9cc68feb8677b326
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  42:     0x56086822bcba - main
  43:     0x7f41a9ae61a3 - __libc_start_main
  44:     0x56086821022e - _start
  45:                0x0 - <unknown>

</pre>
</details>

Here it is my `clap` version of the CLI:
```rust
pub(crate) fn app() -> App<'static, 'static> {
    App::new("App name")
        .version(crate_version!())
        .author(crate_authors!())
        .about(
            "Description",
        )
        .arg(
            Arg::with_name("current_patch")
                .help("HelpText current_patch")
                .value_name("current_patch")
                .takes_value(true)
                .required_unless("update")
                .requires_all(&["upgrade_patch", "out_file"]),
        )
        .arg(
            Arg::with_name("upgrade_patch")
                .help("HelpText upgrade_patch")
                .value_name("upgrade_patch")
                .takes_value(true)
                .required_unless("update")
                .requires_all(&["current_patch", "out_file"]),
        )
        .arg(
            Arg::with_name("out_file")
                .help("Output CSV file.")
                .value_name("out_file")
                .takes_value(true)
                .required_unless("update")
                .requires_all(&["upgrade_patch", "current_patch"])
                .short("o"),
        )
        .arg(
            Arg::with_name("update")
                .help("HelpText update")
                .value_name("update")
                .takes_value(false)
                .required(false)
                .short("u"),
        )
}
```

And here the same implemented with `structopt`:
```rust
#[derive(Debug, StructOpt)]
#[structopt(name = "App name", author, about)]
struct Cli {
    /// HelpText current_patch
    #[structopt(required_unless = "update", requires_all = &["upgrade_patch", "out_file"])]
    current_patch: Option<PatchData>,
    /// HelpText upgrade_patch
    #[structopt(required_unless = "update", requires_all = &["current_patch", "out_file"])]
    upgrade_patch: Option<PatchData>,
    /// Output CSV file.
    #[structopt(short, required_unless = "update", requires_all = &["upgrade_patch", "current_patch"])]
    out_file: Option<PathBuf>,
    /// HelpText update
    #[structopt(short, long)]
    update: bool,
}
```

Am I doing something wrong? If so, shouldn't it be handled at compile time?

**Comment by TeXitoi** [comment]
I suspect bad references. Is it working with `#[structopt(name = "App name", author, about, rename_all = "verbatim")]`? (i.e. adding `rename_all = "verbatim"` at the top level).

**Comment by Razican** [comment]
It is working, yes! It seems that by default, `structopt` renames everything to kebab-case.
