### ISSUE TITLE
Support std::path::PathBuf

### ISSUE THREAD

**Issue by mbr** [TeXitoi/structopt#35]
If I am not mistaken, types that implement `std::str::FromStr` are automatically supported as struct fields. Unfortunately, `std::path::PathBuf` is not among them, although it does implement `From<String>`.

While the workaround of `opt.field.as_str().into()` does work, it would be much nicer to be able to write something like this:

```rust
#[derive(StructOpt, Debug)]
#[structopt(about = "...")]
struct Opt {
    #[structopt(help = "Output filename")]
    outfile: path::PathBuf,
    // ...
}
```

**Comment by TeXitoi** [comment]
As you can see at https://docs.rs/structopt-derive/0.1.6/structopt_derive/#custom-string-parsers this should do exactly what you want.

```rust
#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(help = "Output filename", parse(from_os_str))]
    outfile: path::PathBuf,
}
```

As StructOpt is a macro, we can't know automatically that `PathBuf` has an implementation of `From<OsString>`.

What can I do to improve the doc for your problem?

**Comment by TeXitoi** [comment]
Precision: to do what you asked, that's `parse(from_str)`, but for `PathBuf`, `parse(from_os_str)` is much more appropriate.

**Comment by TeXitoi** [comment]
I've added that on the examples.
