### ISSUE TITLE
Raw syntax doesn't work for validator

### ISSUE THREAD

**Issue by SWW13** [TeXitoi/structopt#350]
The new syntax for raw attributes no longer works for the `validator` function, or at least I can't get it to work.

```rust
fn is_u64(value: String) -> Result<(), String> {
    Err("Test.")
}

#[derive(StructOpt, Debug)]
pub enum Test {
    #[structopt(validator = is_u64)]
    test: Option<u64>
}
```
gives
```
error: proc-macro derive panicked
    |
    | #[derive(StructOpt)]
    |          ^^^^^^^^^
    |
    = help: message: invalid structopt syntax: # [structopt (validator = is_u64)]
```
Using `validator = "is_u64"` instead fails also:

```
error[E0277]: expected a `std::ops::Fn<(std::string::String,)>` closure, found `str`
    |
    | #[derive(StructOpt, Debug)]
    |          ^^^^^^^^^ expected an `Fn<(std::string::String,)>` closure, found `str`
    |
    = help: the trait `std::ops::Fn<(std::string::String,)>` is not implemented for `str`
    = note: required because of the requirements on the impl of `std::ops::Fn<(std::string::String,)>` for `&str`

error: aborting due to previous error
```

Using `validator(is_u64)` or `validator("is_u64")` fails with:
```
error: proc-macro derive panicked
    |
    | #[derive(StructOpt, Debug)]
    |          ^^^^^^^^^
    |
    = help: message: unsupported option: validator ("is_u64")
```

**Comment by CreepySkeleton** [comment]
First, are you sure you use `0.3.x` and not `0.2.x`? `0.3.x` versions do not panic in such circumstances.

Second, are you *sure* you want an `enum` here? It looks like you're making a `struct` instead. I think *this* is your problem because this snippet compiles and runs just fine (`structopt 0.3.9`):
```rust
use structopt::StructOpt;

fn is_u64(_value: String) -> Result<(), String> {
    Err("Test.".into())
}

#[derive(StructOpt, Debug)]
pub struct Test {
    #[structopt(validator = is_u64)]
    test: Option<u64>
}
fn main() {
    println!("{:?}", Test::from_args());
}
```

Also, could you please explain why do you want to use a validator directly? `structopt` uses it's own parsing system on top of it, see https://docs.rs/structopt/0.3.9/structopt/index.html#custom-string-parsers

**Comment by SWW13** [comment]
Thanks for the fast response, you are right about the version. I had one in `dependencies` and another one in `build-dependencies` but only updated one of it.

The `enum` was a left over from shrinking the my code for the issue.

I use the custom validator for some arguments to further validate the argument, for example to verify the argument is a valid path of an existing file. I didn't find a way to extend the validation in the docs, so I just overwrite the existing one with a more narrow implementation.

**Comment by TeXitoi** [comment]
The structopt version would be to use a custom converter: https://github.com/TeXitoi/structopt/blob/master/examples/keyvalue.rs
