### ISSUE TITLE
Add try_from_args to support error handling

### ISSUE THREAD

**Issue by zacps** [TeXitoi/structopt#351]
Currently there's no easy way to handle an error during command parsing yourself.

In my case the program is run as a script from another program, and I want to be able to log errors if it gets parsed invalid arguments.

Proposal:

```rust
pub trait StructOpt {
    fn try_from_args() -> Result<Self, ArgumentsError>
    where
        Self: Sized, {}
    ...
}
```

**Comment by CreepySkeleton** [comment]
It can be implemented via `from_iter_safe` and `std::env::args()`
```rust
match Opts::from_iter_safe(std::env::args()) {
    Ok(opts) => {},
    Err(e) => { /* log it */ }
}
```

If @TeXitoi agrees, I would be willing to accept such a PR though.

**Comment by TeXitoi** [comment]
Nothing against.

**Comment by CreepySkeleton** [comment]
Nobody seems to be interested, so I'm closing this. A PR will still be accepted.
