### ISSUE TITLE
Add global magic method in the docs

### ISSUE THREAD

**Issue by psinghal20** [TeXitoi/structopt#352]
There is a `global` magic method that takes `true` as its argument for enabling global args. There is no mention of the same in the docs. 

The only reference I found after searching a lot for this feature was this [StackOverflow thread](https://stackoverflow.com/questions/59868058/how-to-use-a-cli-argument-after-subcommand-with-the-structopt-crate) which further helped me find [this issue](https://github.com/TeXitoi/structopt/issues/237).

PS: Thanks for such a great library. It is a joy to work with.

**Comment by TeXitoi** [comment]
The global method is a clap feature. As almost everything in clap can be used in structopt, structopt doesn't copy all the clap documentation. You have to search the clap documentation to discover such features.

https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.global

**Comment by psinghal20** [comment]
Oops, didn't think of that. Can we still add some kind of note suggesting a user to go through Clap docs also? Might help people new to the ecosystem.

**Comment by CreepySkeleton** [comment]
I'm having hard time imagining the better way to express "you can use any method from App/Arg" than [the current one](https://docs.rs/structopt/0.3.9/structopt/index.html#raw-methods), but if you think your imagination surpasses mine, go ahead and send a PR.

**Comment by CreepySkeleton** [comment]
I'm closing this. If somebody thinks they have a better idea how to put in the doc, a PR is welcome.
