### ISSUE TITLE
Optional option does not work with environment variable

### ISSUE THREAD

**Issue by davidMcneil** [TeXitoi/structopt#366]
When using an optional option with an environment variable an error is thrown because too many values are passed to the argument. For example:

```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opt {
    /// This is a test
    #[structopt(long, env = "MY_ENV_VAR")]
    test: Option<Option<u32>>,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

If `MY_ENV_VAR` is set and the `--test` argument is set this error is thrown `error: The value '4' was provided to '--test <test>', but it wasn't expecting any more values`.

A hacky fix is to set `max_values = 2`, but obviously this allows setting two values if the environment variable is not set.

**Comment by davidMcneil** [comment]
I am not sure what the best fix this would be. If the maintainers have a specific idea for a fix, I would be happy to submit a PR.

**Comment by TeXitoi** [comment]
Env vives a default value. Option<Option> is really a niche feature to check the difference between not using the option, --option and --option val

So, what are you trying to do? What is your usecase?

**Comment by davidMcneil** [comment]
Allow the user to set a value on the command line or as an environment variable. I think this would be nice behavior if possible:

`app` -> `None`

`MY_ENV_VAR=4 app` -> `Some(Some(4)`

`app --test` -> `Some(None)`

`app --test 6` -> `Some(Some(6))`

`MY_ENV_VAR=4 app --test` -> `Some(Some(4)`

`MY_ENV_VAR=4 app --test 6` -> `Some(Some(6)`

**Comment by TeXitoi** [comment]
I don't think that's possible with clap, so it should be a clap issue.

Also, `MY_ENV_VAR=4 app --test -> Some(Some(4)`, why not `Some(None)`?

And do you have a usecase (a real one) of this?

**Comment by davidMcneil** [comment]
> Also, MY_ENV_VAR=4 app --test -> Some(Some(4), why not Some(None)?

Yes, that would make more sense.

> And do you have a usecase (a real one) of this?

Yep, I have an argument that I would like to behave exactly as described above. It really all works except that clap combines values from the environment and the command line.

Thanks for your help. I will go ahead and close this.
