### ISSUE TITLE
Conflict between `Vec` values and `subcommand`: can we escape `Vec` values?

### ISSUE THREAD

**Issue by antonylsg** [TeXitoi/structopt#367]
Hello,

I came a cross a situation where I need to have both a list of arguments through a `Vec` and a `subcommand` like in this minimal example:
```rust
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
enum SubCommand {
    Cmd,
}

#[derive(StructOpt, Debug)]
struct Cli {
    #[structopt(short, long)]
    list: Option<Vec<u8>>,

    #[structopt(subcommand)]
    sub: SubCommand,
}

fn main() {
    let cli = Cli::from_args();
    println!("{:?}", cli);
}
```

Calling the binary this way will works as expected:
```bash
cargo run -- cmd
```
However, if we specify the list:
```bash
cargo run -- --list 0 1 cmd
```
It'll result in:
```
USAGE:
    cli [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -l, --list <list>...    

SUBCOMMANDS:
    cmd
    help    Prints this message or the help of the given subcommand(s)
```
The subcommand will be interpreted as an element of the list...
What is the right way to handle this? Can we imagine to be able to escape the values with `"`?
Like in this example:
```bash
cargo run -- --list "0 1" cmd
```

Thanks in advance!

**Comment by CreepySkeleton** [comment]
This is known limitation of `clap`, see https://github.com/clap-rs/clap/issues/1708 and https://github.com/clap-rs/clap/issues/1721. To put it simply, there's no way to know where values end and where the subcommand starts in general. I doubt it will ever be fixed.

The situational workaround could be taking only fixed amount of arguments for `--list`, like you have described (only one in your case), and then parse them manually into a list.

**Comment by antonylsg** [comment]
I may found a workaround thanks to https://github.com/TeXitoi/structopt/issues/94#issuecomment-381978295, which allow to escape the list! :)

```rust
#[derive(StructOpt, Debug)]
struct Cli {
    #[structopt(short, long, use_delimiter = true)]
    list: Option<Vec<u8>>,

    #[structopt(subcommand)]
    sub: SubCommand,
}
```

Now, this works:
```bash
cargo run -- --list 0,1 cmd
```
But also:
```bash
cargo run -- --list 0, cmd
```
