### ISSUE TITLE
Optional option has odd behavior with `default_value`

### ISSUE THREAD

**Issue by davidMcneil** [TeXitoi/structopt#368]
Using `default_value` with an optional option leads to unexpected behavior. The value will always be `Some(Some(<default_value>))` unless an actual value is specified. I think, either an optional option should give the same error as option `default_value is meaningless for Option` or better yet only apply if the argument is used without specifying any values: For example:

```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opt {
    /// This is a test
    #[structopt(long, default_value = "10")]
    test: Option<Option<u32>>,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

If the above program is run with no arguments it currently results in `test` equaling `Some(Some(10))`. I propose it should equal `None`, and equal `Some(Some(10))` when only `--test` (with no value) is passed in.

**Comment by CreepySkeleton** [comment]
I would go for the error. Looks like a weird corner case to me, and this can be solved by `Option<T>` with `default_value`. ping @TeXitoi

**Comment by TeXitoi** [comment]
But I really can't understand the usecase of using Option and default_value at the same time.

We can't check all the possibilities of the methods used. And, IMHO, the behavior is quite consistant.

**Comment by davidMcneil** [comment]
> this can be solved by Option<T> with default_value

Could you explain more what you mean by this? Using a `default_value` with `Option<T>` gives an error.

**Comment by davidMcneil** [comment]
> But I really can't understand the usecase of using Option and default_value at the same time.

The usecase is not wanting any value unless the user specifies the argument, but then if the user specifies the argument not requiring them to specify an explicit value.

A real-life example would be an application that operates on files. One of its options (`--keep-latest`) turns on old file cleanup. If `--keep-latest` is not specified we do not want it to clean up any files. If `--keep-latest` is set with no value specified we want it to clean up all but the latest. If `--keep-latest=5` we want it to clean up all but the 5 latest files.

There are certainly workarounds, but that is the usecase I am running into.

**Comment by CreepySkeleton** [comment]
> > 
> 
> Could you explain more what you mean by this? Using a `default_value` with `Option<T>` gives an error. Are you saying this could be a new feature?

I misunderstood, sorry.

What you want is actually a normal field with a default value, but you also need to check if it was present at all, correct? This is [not possible in clap](https://github.com/clap-rs/clap/issues/1358), it seems.

**Comment by TeXitoi** [comment]
@CreepySkeleton so, should we close this feature request with won't fix?

**Comment by CreepySkeleton** [comment]
Yeah, I think we should. Changing this, either to error or the proposed behavior, would be a breaking change for a very little benefit, sorry @davidMcneil .
