### ISSUE TITLE
zsh: option with value breaks completions

### ISSUE THREAD

**Issue by kpcyrd** [TeXitoi/structopt#369]
Having an flag that takes a value seems to break tab completion in zsh because the value is considered a subcommand.

I think this might be a clap bug but I'm having issues reproducing the exact example in clap, help to report this appropriately would be greatly appreciated!

The example works correctly with bash.

## Code

```rust
use std::io::stdout;
use structopt::StructOpt;
use structopt::clap::Shell;

#[derive(Debug, StructOpt)]
pub struct Args {
    #[structopt(short="f", long="foo")]
    pub foo: Option<String>,

    #[structopt(subcommand)]
    pub subcommand: Option<SubCommand>,
}

#[derive(Debug, StructOpt)]
pub enum SubCommand {
    Zsh,
    Bash,
}

fn main() {
    let args = Args::from_args();
    eprintln!("{:?}", args);

    if let Some(c) = args.subcommand {
        let shell = match c {
            SubCommand::Zsh => Shell::Zsh,
            SubCommand::Bash => Shell::Bash,
        };

        Args::clap().gen_completions_to("completion-bug", shell, &mut stdout());
    }
}
```

## Steps to reproduce

```
cargo run -- zsh > ~/.zsh_completions/_completion-bug # you might need to tweak this for your setup
zsh

# this works
completion-bug z<tab>
# this doesn't
completion-bug -f x z<tab>
# this does something unexpected
completion-bug -f z<tab>
```

**Comment by CreepySkeleton** [comment]
@kpcyrd Sorry I left you waiting, but I don't have an answer for you. I'm not familiar with zsh, I don't have it installed, and I'm not really interested in it (no offense). I can't help you reproduce.

Could you please provide an example of `clap::App` that does work? So I could compare them and highlight the differences?

**Comment by kpcyrd** [comment]
Sure, I was basically just wondering if there's an easy way to convert this into clap code that I could report upstream.

**Comment by CreepySkeleton** [comment]
That would be
```
App::new("app")
    .arg(
        Arg::with_name("foo")
            .short("f")
            .long("foo")
    )
    .subcommand(SubCommand::new("zsh"))
    .subcommand(SubCommand::new("bash"))
```

**Comment by CreepySkeleton** [comment]
Closing in favor of the upstream issue
