### ISSUE TITLE
Minimize binary size due to structopt/clap?

### ISSUE THREAD

**Issue by rom1v** [TeXitoi/structopt#37]
In a Rust app, I tried to [replace](https://github.com/Genymobile/gnirehtet/commit/structopt) my dirty manual command-line parsing by `structopt`.

It works well and the source code is far better. However, it makes my resulting binary 6× bigger. For instance the release+stripped version grows from 600K to ~~4M~~ 1.4M, so at least ~~85%~~ 57% of the binary is related to command-line parsing…

Are there any tips to reduce the final binary size?

EDIT: In fact, 4M is the non-stripped binary, the stripped is 1.4M (this is still bigger than 600K, but this makes a difference).

**Comment by TeXitoi** [comment]
I think there is features in clap to limit the depedencies. Then, structopt have to forward the features.

**Comment by TeXitoi** [comment]
fixed by #46
