### ISSUE TITLE
Accept anything `ToString` as a `default_value`

### ISSUE THREAD

**Issue by CodeSandwich** [TeXitoi/structopt#371]
It would be great if `default_value` could accept anything implementing `ToString`, e.g.
```rust
const ABC_DEFAULT: u32 = 123;
...
#[structopt(long, default_value = ABC_DEFAULT)]
abc: u32,
```

or 

```rust
#[structopt(long, default_value = 50 * 2 + 20 + 3)]
abc: u32,
```

It's already possible to pass nothing to `default_value` and then its `ArgType::default().to_string()` is used. This change wouldn't affect existing code, because all string literals implement `ToString`.

**Comment by CreepySkeleton** [comment]
The main problem here is that `Arg::default_value` takes `&str` and not `String`. We would have to leak the string which may be undesirable.

**Comment by CodeSandwich** [comment]
How is empty `default_value` solved? It uses type's `ToString`, does it cache it anywhere?

**Comment by CreepySkeleton** [comment]
Exactly as described: we leak the string and make use of `lazy_static` to make sure that using it in loops is safe.

https://github.com/TeXitoi/structopt/blob/15f65db7540dfe6818d440329198d98c0ca49505/structopt-derive/src/attrs.rs#L314-L323

Well yeah, we could use direct call for `"..."` string literals and `(expr).to_string().leak()` for everything else.

@TeXitoi What do you think?

**Comment by CreepySkeleton** [comment]
@TeXitoi gentle ping

**Comment by TeXitoi** [comment]
The problem, is that it's really a special case. A lot of other methods would like such a feature (I think in particular to `env`).

And no leak, but a lazy static is acceptable.

**Comment by TeXitoi** [comment]
Maybe just https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=884d76afb1211e02a6ddfd2f176cea6d would do the job? (I didn't try inside structopt attribute, but it should work

**Comment by CreepySkeleton** [comment]
Sure, it would. Can I make a PR?

**Comment by TeXitoi** [comment]
Ok

**Comment by TeXitoi** [comment]
This is an enhancement, and structopt is now feature frozen.
