### ISSUE TITLE
specify (long) help string at runtime

### ISSUE THREAD

**Issue by astraw** [TeXitoi/structopt#375]
Is it possible to generate the (long) help string at runtime? How? My use case is that I want to print some example config values which are built using `Default::default()` and I do not want to hardcode these in a string.

An alternative would be to have a flag that can short-circuit the rest of the argument parsing. This would behave much like `-h` or `--help`: it is a valid invocation on the command line which will just run this "subcommand" but not require the other command line arguments. I could seeing this being done using subcommands - the help-like subcommand and the other subcommand which would be the default.

I have looked through the docs but cannot find this - apologies if I missed it.

**Comment by CreepySkeleton** [comment]
Use your imagination 💭!

```rust
lazy_static! {
   static ref VAL_HELP: String = format!(...);
}

#[derive(StructOpt, Debug)]
#[structopt(name = "basic")]
struct Opt {
    #[structopt(short, long = VAL_HELP)]
    val: String,
}

**Comment by astraw** [comment]
Thanks. With your inspiration, I managed the following, which worked for me. (By "help string" I meant the primary usage for the entire command, not for a specific field.)

```rust
#[derive(StructOpt, Debug)]
#[structopt(after_help = VAL_HELP.as_str())]
struct Opt {
    ...
}
```

**Comment by CreepySkeleton** [comment]
`&VAL_HELP` would probably also work 😏

**Comment by astraw** [comment]
You mean `&*VAL_HELP`.

You'd think so, but it does not...

```
   Compiling kalmanize v0.1.0 (C:\Users\drand\Documents\src\kalmanize)
error[E0277]: the trait bound `&str: std::convert::From<&std::string::String>` is not satisfied
  --> kalmanize\src\bin\main.rs:37:13
   |
37 | #[structopt(after_help = &*VAL_HELP)]
   |             ^^^^^^^^^^ the trait `std::convert::From<&std::string::String>` is not implemented for `&str`
   |
   = help: the following implementations were found:
             <&'t str as std::convert::From<regex::re_unicode::Match<'t>>>
   = note: `std::convert::From<&std::string::String>` is implemented for `&mut str`, but not for `&str`
   = note: required because of the requirements on the impl of `std::convert::Into<&str>` for `&std::string::String`

```
