### ISSUE TITLE
Positional argument values similar to subcommand names trigger an error

### ISSUE THREAD

**Issue by kaikalii** [TeXitoi/structopt#378]
Consider the following code:
```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct App {
    #[structopt(index = 1)]
    name: String,
    #[structopt(subcommand)]
    sub: Sub,
}

#[derive(Debug, StructOpt)]
enum Sub {
    Apple,
    Banana,
}

fn main() {
    println!("{:#?}", App::from_args());
}

```

The idea behind this structure is to first provide the name of something on which you wish to operate, followed by a subcommand defining the operation.

Running the program with the arguments `app foo banana` outputs as expected:
```yaml
App {
    name: "foo",
    sub: Banana,
}
```
However, providing a name that is textually similar to a subcommand name gives an error. The arguments `app ba apple` gives the following error:
```
error: The subcommand 'ba' wasn't recognized
        Did you mean 'banana'?

If you believe you received this message in error, try re-running with 'tester.exe -- ban'

USAGE:
    tester.exe <name> <SUBCOMMAND>

For more information try --help
```
It seems strange that a positional argument having a value even slightly similar to a subcommand name should trigger this error.

Is there any way to fix this? Is this even a problem with `structopt` , or is it in `clap`? Is my idea to have a positional argument before a subcommand horribly misguided?

**Comment by CreepySkeleton** [comment]
Nope, you are right, this is a bug in clap. I took liberty to report it upstream closing this issue in favor of the upstream that one.
