### ISSUE TITLE
Allow to extract subcommand data

### ISSUE THREAD

**Issue by Fiedzia** [TeXitoi/structopt#38]
I can't figure out how to extract data associated with a command and assign to a variable.
For example:

```rust
#[derive(StructOpt)]
pub enum Command { 
    #[structopt(name = "foo"]
    Foo{ /*lots of fields*/}
}

#[derive(StructOpt)]
#[structopt(name = "classify"
pub struct ApplicationArguments {
    #[structopt(subcommand)] 
    pub command: Command,
}
let arguments = ApplicationArguments::from_args();
match arguments.command {
    Command::Foo{..} => .. now what?
}
```

`Command::Foo` is not a type. Can't use that.
structopt won't accept form `pub enum Command { Foo(foo_struct) };` this results in macro panicking.
`cmd @ Command::Foo{..}` yields Command, not Command::Foo (because its not a type).

Is there a way around it? I'd like to match on a command, extract command-related options and pass them to a function that only needs data associated with specific command.

**Comment by TeXitoi** [comment]
That's not possible for the moment.

The evolution should be what you proposed:

```rust
#[derive(StructOpt)]
struct Foo {
    /*lots of fields*/
}

#[derive(StructOpt)]
pub enum Command { 
    #[structopt(name = "foo"]
    Foo(Foo)
}

#[derive(StructOpt)]
#[structopt(name = "classify"
pub struct ApplicationArguments {
    #[structopt(subcommand)] 
    pub command: Command,
}
```

**Comment by Azphreal** [comment]
The example you provide fails compilation:

```
error: proc-macro derive panicked
  --> src/main.rs:10:10
   |
10 | #[derive(StructOpt)]
   |          ^^^^^^^^^
   |
   = help: message: enum variants cannot be tuples
```

**Comment by TeXitoi** [comment]
Yes, that's a proposition, not implemented yet.

**Comment by Azphreal** [comment]
Ah, my bad. Misread what you said and thought it had been a recent implementation, not an upcoming one.

**Comment by Fiedzia** [comment]
Awesome. Can we have a release?

**Comment by TeXitoi** [comment]
It's coming, waiting for the open PR and some feedback from quicli. I expect a release for structopt birthday (10th).
