### ISSUE TITLE
Optional subcommand that does not require global parameters

### ISSUE THREAD

**Issue by archer884** [TeXitoi/structopt#382]
Per prior discussion with @CreepySkeleton, the nominal solution for an optional subcommand is something like this:

```rust
#[derive(Debug, StructOpt)]
struct Foo {
    count: usize,
    #[structopt(subcommand)]
    cmd: Option<Command>
}

#[derive(Debug, StructOpt)]
enum Command {
    Bar,
    Baz,
    Quux
}
```

This can be called in the following form:

```shell
$ cargo run -- 5 bar
[src\main.rs:18] Foo::from_args() = Foo {
    count: 5,
    cmd: Some(
        Bar,
    ),
}
```

However, what I'm trying to do is to create a program that supports the following forms instead:

```shell
$ cargo run -- 5 #this works
[src\main.rs:18] Foo::from_args() = Foo {
    count: 5,
    cmd: None,
}
$ cargo run -- bar # this does not
error: The following required arguments were not provided:
    <count>

USAGE:
    scratch.exe <count> [SUBCOMMAND]

For more information try --help
```

As I mentioned to him previously, it appears to be possible to achieve something *like* this by creating two *distinct* commands and checking them in series, e.g.:

```rust
if let Ok(command) = Command::from_iter_safe(env::args()) {
    return match command {
        Command::List => Options::List,
        Command::Search { query } => Options::Search { query },
    };
}

let mut opt: Opt = StructOpt::from_args();
```

...But this makes for help documentation that does not mention the subcommands at all.

Any idea what I ought to do?

**Comment by CreepySkeleton** [comment]
This is a case of #124 . There are a couple of workarounds there, but no good solution have been proposed so far 😢 

I'm going to close this particular issue in favor of that one.
