### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ralpha** [TeXitoi/structopt#386]
I see you are using the MIT OR Apache-2.0 license, which is perfect.
But checking the licenses I found some minor remarks.

In your Apache license you might want to change this line and fill in your information:
https://github.com/TeXitoi/structopt/blob/203c6bc19e561da1734873794bbd420e0bfc79b9/LICENSE-APACHE#L189

Looking in crates.io I also noticed your license states:
https://github.com/TeXitoi/structopt/blob/203c6bc19e561da1734873794bbd420e0bfc79b9/Cargo.toml#L11
Maybe consider changing this to:
```
license = "MIT OR Apache-2.0"
```
Then it is written the same way as other rust-lang licenses.

I know this might be a bit nit-picky but yeah, just here to let you know.
Also, nice crate you made here. Like it a lot! :heart:

**Comment by TeXitoi** [comment]
For the LICENSE-APACHE, no, that's a template, not something you should update.

I'll open a PR shortly for the OR, but will not do a release just for that.

Thanks!

**Comment by ralpha** [comment]
I'm fairly sure you need to change the copyright notice.
> To apply the Apache License to specific files in your work, attach the following boilerplate declaration, with the fields enclosed by brackets "[]" replaced with your own identifying information. (Don't include the brackets!) The text should be enclosed in the appropriate comment syntax for the file format.

https://apache.org/licenses/LICENSE-2.0

For example: https://github.com/rust-lang/futures-rs/blob/3bf5ac99e939e6ff70283937fa91e8d77e5f70e8/LICENSE-APACHE#L189

And yes, an new release is not needed for this :)

**Comment by TeXitoi** [comment]
I doubt it should be done https://github.com/apache/httpd/blob/trunk/LICENSE#L189

**Comment by ralpha** [comment]
It could be the case, not sure. I'm also not here to argue about it, I am for from an expert in this.
Still think the information should be somewhere. As it would be hard for someone to find all the authors names if they are not available in GitHub.
https://www.apache.org/foundation/license-faq.html#Apply-My-Software

If someone knows more about it they will let you know at some point. But not many people are going to trip over this, I think. In the end you decide what you want to do with it.

**Comment by ralpha** [comment]
Sorry did not mean to close it. It will be closed when the pull request is through.

**Comment by TeXitoi** [comment]
Changelog was quite explicit about contributors, but I see that we are not so regarding since 0.3

**Comment by CreepySkeleton** [comment]
@ralpha is right here, you were supposed to put your name there, possibly along with "and other contributors", [like that](https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/LICENSE#1). It's just some open source projects don't really care about it.

Regarding changelog: well, it was just almost all contributions - short of "fix typo" - were being made by you or me at the time of 0.3.0. I could be putting "thanks to CreepySkeleton, TeXitoi, Creepy, TeXitoi..." but decided is was quite dumb and ceased to do it. After some time, I simply forgot about it, sorry.

**Comment by TeXitoi** [comment]
Don't really bother personally, and if someone whany note credits, they can.

You example is quite different: the line quoted is an appendix explaining who to put copyright notice in your source file. I really don't think the author is supposed to modify the license file here.
