### ISSUE TITLE
First example in docs panics when run naively

### ISSUE THREAD

**Issue by dandavison** [TeXitoi/structopt#389]
Hi, thanks for StructOpt! I wonder if the [first code example](https://docs.rs/structopt/0.3.14/structopt/#how-to-derivestructopt) in the docs could be made slightly more beginner-friendly? Currently if one creates a project with `cargo new`, and replaces main.rs with that example code, and issues `cargo run`, it panics:

```
thread 'main' panicked at 'Found positional argument which is not required with a lower index than a required positional argument: "output" index 2', /Users/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.1/src/app/parser.rs:643:21
```

Would it make sense to either

- Add an example command line invocation below the example code that does not panic, or
- Simplify the example code so that it does not panic when no arguments are provided?

**Comment by TeXitoi** [comment]
Thanks for reporting!
