### ISSUE TITLE
Q: How to use raw clap args across subcommands

### ISSUE THREAD

**Issue by Passeriform** [TeXitoi/structopt#393]
I'm new to structopt and trying it out has been amazing. I've been stuck at this problem for a while now. I have the following setup:

```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct CliArgs {
	#[structopt(short, long)]
	aisle: Option<String>,

	#[structopt(short, long)]
	shelf: Option<String>,

	#[structopt(subcommand)]
	operation: Option<Ops>,
}

#[derive(Debug, StructOpt)]
enum Ops {
	Add {
		isbn: Option<String>,
		pin: Option<String>
	},
	Remove {
		isbn: Option<String>,
	},
	Status,
}
```

In this scenario, I'd like a condition where either `aisle` and `shelf` are together specified or `isbn` alone is specified. I found both raw clap methods [`required_unless`](https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.required_unless)  and [`conflicts_with`](https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.conflicts_with), and their variants [`required_unless_all`](https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.required_unless_all)  and [`conflicts_with_all`](https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.conflicts_with_all) together could be of use.

Maybe using them like such:
```rust
...
	#[structopt(short, long, required_unless = "isbn", conflicts_with = "isbn")]
	aisle: Option<String>,

	#[structopt(short, long, required_unless = "isbn", conflicts_with = "isbn")]
	shelf: Option<String>,
...
```
and
```rust
...
	Add {
		#[structopt(required_unless_all = &["aisle", "shelf"], conflicts_with_all = &["aisle", "shelf"])]
		isbn: Option<String>,
		pin: Option<String>
	}
...
```
But it results in the following
```
~❯ RUST_BACKTRACE=full cargo run -q -- --aisle A1 --shelf X3 add 2441 
error: The following required arguments were not provided:
	<pin>
```
Which is right because passed pin is used as `isbn` instead.

```
~❯ RUST_BACKTRACE=full cargo run -q -- add A1/X3 2441 
error: The following required arguments were not provided:
	--aisle <aisle>
	--shelf <shelf>
```
```
~❯ RUST_BACKTRACE=full cargo run -q -- --aisle B1 --shelf Y3 add A1/X3 2441 
<It works>
```
```
~❯ RUST_BACKTRACE=full cargo run -q -- add 
error: The following required arguments were not provided:
	<isbn>
	<pin>
```
Which doesn't work for obvious reasons. I think the main issue with my problem is that the fields can't reference each other if put under a sub-command. Am I doing something wrong with the current approach? Would there be a better alternative to clap::arg methods in this case? Or is there a way of communicating between sub-commands? I'm sorry if this is a dumb question. Thanks for the help!

**Comment by TeXitoi** [comment]
Sorry for the long reply.

This is a clap usage problem, not really related to structopt, that just pass these parameters to clap.

I think that the constraints are subcommand local, and that you can't do that with clap today. But not sure.

@CreepySkeleton you that know clap better than me now, what do you think?

**Comment by CreepySkeleton** [comment]
> the fields can't reference each other if put under a sub-command.

Exactly. I think what OP was looking for is https://docs.rs/clap/2.33.2/clap/enum.AppSettings.html#variant.SubcommandsNegateReqs

See also https://github.com/TeXitoi/structopt/issues/124

**Comment by TeXitoi** [comment]
Can we close this? @Passeriform

**Comment by TeXitoi** [comment]
Thanks
