### ISSUE TITLE
version = expr ignored when using structs in subcommands

### ISSUE THREAD

**Issue by ajeetdsouza** [TeXitoi/structopt#394]
structopt ignores explicitly set version numbers when used on a struct inside an enum.

To reproduce:

```rust
#[derive(StructOpt)]
enum App {
    Baz(Baz),
}

#[derive(StructOpt)]
#[structopt(about = "testing", version = "v1337")]
struct Baz {}

```

Now running `cargo run -- help baz` gives us:

```
foo-baz 0.1.0
testing

USAGE:
    foo baz

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
```

This is unexpected, since structopt ignores the `version` field, but uses the `about` field.

Related issues:
- https://github.com/TeXitoi/structopt/issues/324
- https://github.com/TeXitoi/structopt/issues/283

**Comment by CreepySkeleton** [comment]
This isn't really a bug. The trick is that you need to annotate _the variants_, not the underlying struct: the attrs on it aren't used. This is a pretty common mistake people make with doc comments.

```rust
use structopt::StructOpt;

#[derive(StructOpt)]
enum App {
    #[structopt(about = "testing", version = "v1337")]
    Baz(Baz),
}

#[derive(StructOpt)]
struct Baz {}

fn main() {
    App::from_args();
}
```
```
probe.exe-baz v1337
testing

USAGE:
    probe.exe baz

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
```

**Comment by ajeetdsouza** [comment]
@CreepySkeleton true, but in the example I provided, the `about` field does work, despite the fact that it has been annotated on the struct and not the variant.

This is inconsistent behaviour, since the `version` field that has been annotated in the same place doesn't work.

**Comment by CreepySkeleton** [comment]
>  the about field does work

Yes, and it mustn't. This causes #391.
