### ISSUE TITLE
Method to unparse struct

### ISSUE THREAD

**Issue by ian-fox** [TeXitoi/structopt#404]
In the process of looking at https://github.com/rust-fuzz/cargo-fuzz/issues/228, and for that we need to give users a command to run to reproduce a result. This involves taking a struct which was parsed with StructOpt and unparsing it to a set of flags/options such that when the user enters those on the command line it parses back to the original struct.

e.g. given the following struct:

```rust
#[derive(StructOpt, Debug)]
#[structopt(name = "basic")]
struct Opt {
    #[structopt( short, long, default_value = "42" )]
    x: i32,

    #[structopt( short, long )]
    y: bool,
}
```

If you had a copy where `x` was 5 and `y` was false, unparsing would return something like the string `"-x 5"`. If `y` was also true, it'd give `"-x 5 -y"`.

My original plan was to implement this for the specific struct in that project, but if it seems like a feature that would be more generally useful I'd be happy to try to implement it here instead.

**Comment by CreepySkeleton** [comment]
I'm not sure we want this to be a part of `structopt` (or `clap_derive`) - it sounds quite niche. But you can write your own derive that does the thing! cc @TeXitoi

**Comment by ian-fox** [comment]
Fair enough, thought I'd check just in case!

**Comment by avnerbarr** [comment]
just asked a similar question - sometimes you need to modify the arguments and want to know what the valid string would be. Any way to generate this?

**Comment by avnerbarr** [comment]
for instance if some condition occured you would notify the user


```
if some_condition
  modify opts
  print!("re-run with {}", modified_opts);
}

>>> re-run with my_app -a 1 -b 2 .... 
```
