### ISSUE TITLE
Question: required_if and rust method calls

### ISSUE THREAD

**Issue by SirWindfield** [TeXitoi/structopt#409]
I have the following struct:
```rust
struct Config {
    #[structopt(required_if("a", "Option::is_none")]
    a: Option<String>,
    #[structopt(required_if("a", "Option::is_none"))]
    b: Option<String>,
}
```

It works with basic types like `&str`. But sadly it doesn't work (or I can't make it work) with Option.

**Comment by TeXitoi** [comment]
https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.required_if

At this stage, you are in clap, and required_if compare with a string. So that's normal, and nothing that structopt can do.

**Comment by TeXitoi** [comment]
https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.conflicts_with
Maybe that's what you are searching?

**Comment by TeXitoi** [comment]
Or maybe https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.required_unless_one

**Comment by SirWindfield** [comment]
Thank you for your help! The other methods suited my problem more!
