### ISSUE TITLE
Support allow_hyphen_values

### ISSUE THREAD

**Issue by coder543** [TeXitoi/structopt#41]
Currently, providing a negative value for an integer parameter results in an error about an unexpected argument. It would be nice if `structopt`  supported `clap`'s `allow_hyphen_values` option. `structopt` actually seems to, but only on Nightly, since you have to do...

    #[structopt(allow_hyphen_values=true, long = "timezone", default_value = "-4", help = "Specifies the timezone as the hours of offset from UTC.")]

and that literal `true` value requires `#![feature(attr_literals)]` to work currently.

**Comment by TeXitoi** [comment]
On mobile, but I'll try to explain. Use the `_raw` variant : `allow_hyphen_value_raw = "true" `

Does it fixes your issue ?

**Comment by TeXitoi** [comment]
Side note: timezone can be half and quarter of an hour. Look at India :'-(

**Comment by azriel91** [comment]
In case someone else stumbles upon this, you can go:

```rust
#[derive(StructOpt)]
#[structopt(name = "app"))]
struct Opt {
    // ...

    // Pass the rest of the arguments through
    #[structopt(raw(allow_hyphen_values = "true"))]
    rest_of_args: Vec<String>,
}
```

The command needs to be invoked like so:

```bash
# the '--' separator is important
$ app -- rest_of_args_1 --rest_of_args_option
```

**Comment by caiohamamura** [comment]
Not working here.

**Comment by TeXitoi** [comment]
Raw is no more a thing in 0.3

**Comment by PvdBerg1998** [comment]
`#[structopt(allow_hyphen_values(true))]` compiles, but doesnt work.

**Comment by TeXitoi** [comment]
@PvdBerg1998 please provide a more comprehensive example, that compiles, with a call explaining what you have, and what you're expecting. Also, adding a comment in a closed issue might not be noticed.

**Comment by PvdBerg1998** [comment]
I'm expecting the argument to get parsed with a hyphen in front, e.g. "-20".

I've found out this works with a negative x or y:
```rust
#[derive(Clone, Debug, PartialEq, Eq, StructOpt)]
#[structopt(setting = structopt::clap::AppSettings::AllowLeadingHyphen)]
struct Args {
    x: String,
    y: String
}
```

But this does not, although it does compile like I said:
```rust
#[derive(Clone, Debug, PartialEq, Eq, StructOpt)]
struct Args {
    #[structopt(allow_hyphen_values(true))]
    x: String,
    #[structopt(allow_hyphen_values(true))]
    y: String
}
```

**Comment by tami5** [comment]
I'm having the same issue 

```rust
    #[structopt(default_value = "0", allow_hyphen_values = true)]
    date: Vec<String>,

```

Also when I tried @PvdBerg1998 solution it gives me an error saying setting I get no named method
