### ISSUE TITLE
Documenting flattened fields?

### ISSUE THREAD

**Issue by leeola** [TeXitoi/structopt#411]
I'm trying to write Cargo documentation for a field that is flattened by structopt. This seems to be rejected as a compile-time error, via:

```
error: proc-macro derive panicked
  --> foo/src/serve.rs:12:10
   |
12 | #[derive(StructOpt, Debug)]
   |          ^^^^^^^^^
   |
   = help: message: methods and doc comments are not allowed for flattened entry

error: aborting due to previous error
```

I imagine StructOpt chose this behavior for automatically generated `--help`, however this directly conflicts with clippy lints that require documentation. Ie, i can't merge this structopt code as it either fails clippy lints or fails to compile due to StructOpt.

Is there a way to disable this compilation failure? Ie, ignore the flattened field's documentation? Maybe something like a `structopt(flatten, ignore_documentation)` attribute?

**Comment by CreepySkeleton** [comment]
I think we can just ignore the doc comments on top of `#[flatten/subcommand]` fields.
