### ISSUE TITLE
Aliasing flags to a value

### ISSUE THREAD

**Issue by Morganamilo** [TeXitoi/structopt#415]
I have the field `Mode` that accepts `a`, `b`, `c`. With structopt I can create a flag `--mode=a`. But what I want is `--a/b/c` to be their own flags that would set `Mode` to `a/b/c`.

Is there any way to achieve this currently?

**Comment by TeXitoi** [comment]
You can have the 3 bool and then implement a getter that will return your enum by matching on the bool triplet.

```rust
impl Opt {
    fn mode(&self) -> Mode {
        match (self.a, self.b, self.c) {
            (true, false, false) => Mode::A,
            // ...
        }
    }
}
```

**Comment by Morganamilo** [comment]
How would you handle the case of:

```
#run mode a by default
alias foo="foo --a"

#exlicitly choose mode b
foo --b
```

**Comment by CreepySkeleton** [comment]
```rust
#[derive(StructOpt)]
struct Opt {
    #[structopt(long, overrides_with_all = &["b", "c"]]
    a: bool,
    #[structopt(long)
    b: bool,
    #[structopt(long)
    c: bool,
}
```

**Comment by Morganamilo** [comment]
Thanks, didn't know about `overrides_with_all`. That will work.
