### ISSUE TITLE
Parse command line on existing config instance

### ISSUE THREAD

**Issue by Morganamilo** [TeXitoi/structopt#416]
There have been a couple of issues to allow parsing from a config file.

What I want is something more flexible. Instead of having to do `Config::from_args()`, I would Like to be able to do. `let mut config = Config::new(); config.parse_args()`.

This would allow for config parsing and any other processing to happen before parsing arguments.

```rust
let mut config = Config::new();
config.parse_config(config_file);
config.parse_args();
```

**Comment by CreepySkeleton** [comment]
Could you please say a few more words? Your comment doesn't give me any useful context or new information. Most importantly, I would appreciate an elaborated explanation of how your request is different from #72 .

**Comment by Morganamilo** [comment]
#72 seems to want to integrate with some config parsing crate.

I simply want the Structopt trait to be able to operate on an already existing struct instance. While `from_args()` creates the struct for  you, I want `parse_args()` to take in `&mut self` instead.

In my example above `parse_config()` is unrelated to structopt and would be a function implemented myself.

```rust
let mut config = Config::new(); // create an instance of my struct that implements Structopt
config.parse_config(config_file); // my own config parsing, make sure we do this before arg parsing so args have priority
config.parse_args(); //  structopt now modifies the struct and applies the arguments on top of the existing values
```

**Comment by CreepySkeleton** [comment]
I see. I don't think I'll ever be working on it (I'm simply not interested), but I'd approve such a PR. 

We will need to decide on the precise specification (update vs replace aka `config[true] + args[false] = false` vs `= true`) and the signature (the `parse_args` takes `enum { Replace, Update }`), but I think we can discuss it when somebody has actually stepped in and volunteered. 

This should also solve #72 as "good enough" solution.

**Comment by TeXitoi** [comment]
This is an enhancement, and structopt is now feature frozen.
