### ISSUE TITLE
How to read multiple occurrences of a flag?

### ISSUE THREAD

**Issue by pkolaczk** [TeXitoi/structopt#419]
I'm trying to define a flag that can be specified multiple times. I want to receive the number of times the flag has been given.
I tried this:

    #[structopt(short = "v", long, multiple(true), takes_value(false))]
    pub verbose: Vec<bool>,

But this returns an empty vector, regardless of the number of occurrences.
Also tried returning an integer, but that panics.

Is there a way to do it with structopt?

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/structopt/blob/master/examples/basic.rs#L17-L20

**Comment by pkolaczk** [comment]
Thank you!
