### ISSUE TITLE
Retain/keep help arguments sorting?

### ISSUE THREAD

**Issue by vn971** [TeXitoi/structopt#421]
Hi, thanks for the awesome project!
Is it possible to keep arguments sorting the same as written in the underlying `struct`? I think there are cases when you want to write arguments in a certain order, and I think it'd be nice to retain this order.

**Comment by vn971** [comment]
(I tried to think of a MergeRequest, but I can't find any obvious places like a use of HashMap / HashSet. Not sure what's the source of reordering.)

**Comment by CreepySkeleton** [comment]
Define "argument-sorting"? I don't understand the question; some examples might help.

**Comment by vn971** [comment]
I mean in the `--help` message. For example, given this structopt definition: https://gitlab.memri.io/memri/pod/-/blob/5bb03c2da52452b200792750d2ea1f7f8a689501/src/command_line_interface.rs

I get an output like this: https://gitlab.memri.io/memri/pod/snippets/1

As you see, even though port is defined first in the source code ( `#[structopt(short, long, default_value = "3030")]  port: i16,` ), it will be in fact listed somewhere in the bottom ( `-p, --port <port>   Port to listen to [default: 3030]` ).

Would it be possible or a better idea to preserve ordering?

**Comment by vn971** [comment]
( The problem persists if `AppSettings::UnifiedHelpMessage` is commented out as well )

**Comment by TeXitoi** [comment]
`AppSettings::DeriveDisplayOrder`

**Comment by vn971** [comment]
@TeXitoi oh nice, thanks a lot! Is there a reason why it's not "enabled" by default?

**Comment by vn971** [comment]
(EDIT)

**Comment by TeXitoi** [comment]
That's clap default. But I personally prefer this default, as it makes search in the help message easier.

**Comment by CreepySkeleton** [comment]
> Is there a reason to not "enable" it by default?

So many men, so many minds. Some prefer alphabetical sorting, some like "as declared" sorting. It's just happened that the former is default, the latter is opt-in, and I also think alphabetical is more common.

**Comment by vn971** [comment]
@CreepySkeleton that is not alphabetical sort in the first example sort though, is it? https://gitlab.memri.io/memri/pod/snippets/1
I don't recognize the type of sorting at all. When I changed some options around, some options that weren't change actually got swapped, the whole "picture" is moving randomly.

**Comment by CreepySkeleton** [comment]
That's... weird. I swear I saw the "alphabetical order" in clap docs, lemme check... [nope, I'm not delusional](https://docs.rs/clap/2.33.0/clap/enum.AppSettings.html#variant.DeriveDisplayOrder)

> Displays the arguments and SubCommands in the help message in the order that they were declared in, **and not alphabetically which is the default**.

Well, I guess you're going to have to live with it until clap 3.0 is out, sorry.

**Comment by vn971** [comment]
Is it a bug in clap then? I'm a bit lost. It would seem that the latest version of structopt already uses clap 2.33.0, but options are not listed alphabetically in `--help`.. Am I missing something here?

**Comment by CreepySkeleton** [comment]
Yes, this is a bug in clap 2.33. Unfortunately, it's unlikely to ever be fixed because all time we have we put into 3.0; clap 2.x is essentially frozen. You don't seem to be affected by the bug because you use `DeriveDisplayOrder`, and if you were, you could assign the order manually via `display_order = 1, 2, 3...` as a workaround.

I'll make sure this is fixed in 3.0.

**Comment by vn971** [comment]
Thanks, understood, all clear now!
