### ISSUE TITLE
Release/tag/release_notes for versions

### ISSUE THREAD

**Issue by jensim** [TeXitoi/structopt#422]
Hi!
I'm looking for release notes on the latest version 0.3.16, and found that some version-tags are missing in the git repo.
If I'm not asking to much, could someone add tags that correlate to the released versions, or just the latest version?
And (Cream on top) add some release notes in the GH-release interface, otherwise Ill just look at commits ^^

Love the lib! 
/Jens

**Comment by CreepySkeleton** [comment]
Tag created.

As for GH releases page, I'm not very interested in maintaining _yet another_ changelog in addition to `Changelog.md`. Do you know of any tool that would fill the releases page from changelog for me?

**Comment by jensim** [comment]
@CreepySkeleton the changelog.md was what I was looking for 😅
It might be a better choise for version descriptions as it follows the repo no matter where it's hosted.. 
But the tags are only present in crates.io 
The way i usually do it is let the CI system perform release.
Making it work flawlessly is way to much work imho..
So keep on doing what you are doing, its top notch 😘
