### ISSUE TITLE
positional arguments value cannot be set to subcommand name

### ISSUE THREAD

**Issue by Fiedzia** [TeXitoi/structopt#423]
```rust

use structopt::StructOpt;
  
#[derive(Clone, Debug, StructOpt)]
pub struct Git {
    #[structopt(help = "repo name")]
    pub repo: String,
    #[structopt(subcommand)]
    pub source: Command,
}

#[derive(Clone, Debug, StructOpt)]
pub enum Command {
    New,
}

fn main() {
    let args = Git::from_args();
} 

```

By my understanding this should allow this invocation:

```./demo <repo name> new```
for example: ./demo somerepo new

and it works fine, unless we want to set <repo name> to name of subcommand

./demo new new
error: Found argument 'new' which wasn't expected, or isn't valid in this context

looks like a bug to me

**Comment by CreepySkeleton** [comment]
I'm afraid this is one of clap's parser limitations. 

Subcommands have priority over everything else, and this apparently doesn't take required args under consideration. 

```
demo new new
     --- subcommand
         --- arg of the subcommand (unknown)
```

I'll relay it to clap, but no chance it's gonna be fixed in 2.x and structopt.

**Comment by Fiedzia** [comment]
Thanks.
