### ISSUE TITLE
error[E0425]: cannot find value `app` in this scope

### ISSUE THREAD

**Issue by d-e-s-o** [TeXitoi/structopt#424]
I have the following code:
```rust
use structopt::StructOpt;

macro_rules! Command {
  ( $name:ident, [
    #[$meta:meta] $var:ident($inner:ty)
  ] ) => {
    #[derive(Debug, PartialEq, structopt::StructOpt)]
    enum $name {
      #[$meta] $var($inner),
    }
  };
}

Command! {GitCmd, [
  #[structopt(external_subcommand)]
  Ext(Vec<String>)
]}

// Works:
//#[derive(Debug, PartialEq, StructOpt)]
//enum GitCmd {
//  #[structopt(external_subcommand)]
//  Ext(Vec<String>),
//}

fn main() {
  assert_eq!(
    GitCmd::from_iter(&["test", "git", "status"]),
    GitCmd::Ext(vec!["git".to_string(), "status".to_string()]),
  );
}
```

And it fails to compile (0.3.16, default features):
```
error[E0425]: cannot find value `app` in this scope
 --> src/main.rs:7:32
  |
7 |     #[derive(Debug, PartialEq, structopt::StructOpt)]
  |                                ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `foo`.

To learn more, run the command again with --verbose.
```

I checked the [expanded output](https://gist.github.com/d-e-s-o/4653b9ba305654bd6733573913c011a3) and everything seems perfectly fine.

So then I came up with the following patch to `structopt-derive`:
```diff
--- lib.rs
+++ lib.rs
@@ -481,7 +481,7 @@ fn gen_augment_clap_enum(
         let kind = attrs.kind();
         match &*kind {
             Kind::ExternalSubcommand => {
-                quote_spanned! { attrs.kind().span()=>
+                quote! {
                     let app = app.setting(
                         ::structopt::clap::AppSettings::AllowExternalSubcommands
                     );
```

And now everything works. I am not really sure what to make of that. I checked the `quote_spanned` macro but nothing stood out. Any ideas?

**Comment by d-e-s-o** [comment]
I played around a bit with `quote`. And I can get the original building with the following patch:
```diff
--- src/runtime.rs
+++ src/runtime.rs
@@ -228,7 +228,7 @@ pub fn push_ident_spanned(tokens: &mut TokenStream, span: Span, s: &str) {
     if s.starts_with("r#") {
         parse_spanned(tokens, span, s);
     } else {
-        tokens.append(Ident::new(s, span));
+        tokens.append(Ident::new(s, Span::call_site()));
     }
 }

```

Not really sure what this means, though. `¯\_(-_-)_/¯`

**Comment by CreepySkeleton** [comment]
That means that the `app` ident created via `quote_spanned` (with non-call_site span) and the `app` ident created via `quote` are two different identifiers entirely. Long story short: every token in source code has a span (kinda like original location but it's complicated) information which is a part of macro hygiene rules. Idents may have the same "value" (`app == app`), but may have different span info, and then they're different idents.

The app here should be `call_site`, that's an error I'll fix shortly.

**Comment by d-e-s-o** [comment]
Awesome!
