### ISSUE TITLE
Flags broken when used with env

### ISSUE THREAD

**Issue by MarinPostma** [TeXitoi/structopt#428]
When using a flag along with an env, the cli expect a value for the flag; this works fine:

```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(short, long)]
    debug: bool,
}
```

and this return an error when `cargo r -- --debug` is ran:

```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(short, long, env = "DEBUG")]
    debug: bool,
}
```
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/strucopt --debug`
error: The argument '--debug <debug>' requires a value but none was supplied

USAGE:
    strucopt --debug <debug>

For more information try --help
```

The expected behavior would be for both to behave like a flag

**Comment by TeXitoi** [comment]
Env doesn't work as flags, it works as option, and there is not really any way of changing that in clap.

https://github.com/clap-rs/clap/issues/1476

**Comment by jszwedko** [comment]
@TeXitoi Just noticing that https://github.com/clap-rs/clap/pull/2190 was merged to resolve https://github.com/clap-rs/clap/issues/1476 . Is this still the case that `structopt` cannot support this?

**Comment by TeXitoi** [comment]
This is for clap v3 (in alpha stage), that contains its own structopt fork. structopt use clap v2 (mainstream) that is frozen.
