### ISSUE TITLE
feature request: `default` function for struct

### ISSUE THREAD

**Issue by tamuhey** [TeXitoi/structopt#436]
I want to test my function that uses derived `MyOpt` to check the default value is valid.
Is there any way to construct `MyOpt` with default value, e.g. `MyOpt::default()`?

**Comment by CreepySkeleton** [comment]
>  Is there any way to construct `MyOpt` with default value, e.g. `MyOpt::default()`?

Of course! You absolutely can implement `Default` for it and then construct it via `MyOpt::default()`. 

But if you want a useful answer, please describe your problem in a more elaborate way. The best way to convey this kind of request is to show some examples along the lines of "This is what I want it to look like" and "This is how I expect it to behave".

**Comment by TeXitoi** [comment]
I think @tamuhey is looking for:

```rust
Opt::from_iter(&["test"]);
```

To get the Opt corresponding to "no agrument given" (test is the name of the program, of no importance here).

**Comment by tamuhey** [comment]
@TeXitoi thanks! That is what I'm looking for!
