### ISSUE TITLE
Optionally return an error instead of panicing.

### ISSUE THREAD

**Issue by StewartCanva** [TeXitoi/structopt#437]
We're currently using StructOpt and it works like a charm. 👍

One thing that would be great however is if `from_args()` could return an error instead of causing a panic. Ideally we would like to handle the case if there's any error parsing the arguments. For example we're using rust errors in order to log anytime our program fails, which we're not able to do in this specific case. That being said I'm guessing it's probably not a trivial change to make.

**Comment by CreepySkeleton** [comment]
`from_iter_safe(std::env::args_os())` is what you're looking for.

I guess this is the second time we were asked about it, so I think I'll go ahead and add `from_args_safe` as a shortcut for the invocation above.

**Comment by TeXitoi** [comment]
OK for me for the `from_args_safe` shortcut.

**Comment by CreepySkeleton** [comment]
Closed by https://github.com/TeXitoi/structopt/commit/f5a7dcc6fa2a98db59046fb1c93bea1f3880aba7 and released in `0.3.19`
