### ISSUE TITLE
Question - how can I print the arguments given an opt instance?

### ISSUE THREAD

**Issue by avnerbarr** [TeXitoi/structopt#441]
I want to get the string representation leading to a particular Opt instance (after I've modified it).

for instance

```
#[derive(StructOpt)]
struct Opt {
a : String,
b: String,
c: i32,
...
z : String
}

...
let opts = Opt::from_args();
...
if some condition occured, change opts and print the correct representation {
  let new_opts = Opt { z: "this_value_should_be_written", ..Opt::from_args() }; // change some values
  print(how do I print "new_opts" in such a way that is valid for the Opt parser for next run?)
}
```

**Comment by EverlastingBugstopper** [comment]
you could add a debug derivation like so: `#[derive(StructOpt, Debug)]` and then print like `println!("{:?}, new_opts);` or even `println!("{:#?}", new_opts);`

**Comment by TeXitoi** [comment]
AFAIK, that's not possible, and it will be a quite complicated feature, relying deeply in clap internal.

**Comment by therealbnut** [comment]
Adding to this I want to use `structopt` for IPC with a forked child process, and so I'd like to be able to go from an `Opt` structure to a `Vec`/`Iterator` of argument strings.

ie.
```rust
enum Opt {
    #[structopt(short, long)]
    host_name: String,
}

// ["--host_name", "my-server"]
(Opt { host_name: "my-server".to_owned() }).args()
```

If this was possible then you could emit debugging info by doing:
```rust
println!("{:?}", op.args())
```

**Comment by Xaeroxe** [comment]
@TeXitoi would you be open to a PR implementing this?

**Comment by TeXitoi** [comment]
Better to propose to clapv3

**Comment by TeXitoi** [comment]
This is an enhancement, and structopt is now feature frozen.
