### ISSUE TITLE
Feature: Grouping subcommands 

### ISSUE THREAD

**Issue by hatembentayeb** [TeXitoi/structopt#445]
I suggest to add a grouping feature to be visible on the help message when showing subcommands like this 

```
SUBCOMMANDS:
       Management: // Groups the management part 
           CommandA
           CommandB
       Operations: // Groups the operations part 
           CommandC
            CommandD
```
it's usefull when we have a lot of subcommands and help the end user to get it quickly.

**Comment by TeXitoi** [comment]
That's a feature to ask to clap. StructOpt just delegate this to clap.

**Comment by TeXitoi** [comment]
You can always write you help message by hand, as a "workaround".
