### ISSUE TITLE
change default text of `help` subcommand

### ISSUE THREAD

**Issue by EverlastingBugstopper** [TeXitoi/structopt#446]
Hi! I have an app with a bunch of nested subcommands. Each of these subcommands includes an emoji for some _spice_. It looks a little weird to not have an emoji for the help subcommand, so I'd love to be able to just pop one in front of it without really changing anything else.

To make this a bit more concrete:

what i have:

```console
$ cargo run -- config
⚙️ Manage configuration

USAGE:
    rover config [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -l, --log <log-level>     [default: debug]  [possible values: error, warn, info, debug, trace]

SUBCOMMANDS:
    api-key    🔑 Configure an account or graph API key
    clear      🚮 Remove all configuration
    help       Prints this message or the help of the given subcommand(s)
    profile    💁 Operations for listing, viewing, and deleting configuration profiles
```

what i want:

```console
$ cargo run -- config
⚙️ Manage configuration

USAGE:
    rover config [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -l, --log <log-level>     [default: debug]  [possible values: error, warn, info, debug, trace]

SUBCOMMANDS:
    api-key    🔑 Configure an account or graph API key
    clear      🚮 Remove all configuration
    help       🦮 Prints this message or the help of the given subcommand(s)
    profile    💁 Operations for listing, viewing, and deleting configuration profiles
```

**Comment by CreepySkeleton** [comment]
No straightforward way: [`App::help_message`](https://docs.rs/clap/2.33.0/clap/struct.App.html#method.help_message) affects only `--help` and `-h` switches, not the `help` subcommand (I checked).

Workarounds I can think of:
* Define _your own_ `help` subcommand that will replace the auto-generated one. Can't really advice that: you'll have to introduce a new `Help()` enum variant that's completely useless to you and will add some noise at `match` sites. Also, you'll have to do it for every nested subcommand and reimplement some of the printing logic by yourself.
* Just patch the damned message
    ```rust
    fn main() {
        let matches = Opt::from_args_safe()
            .map_err(|e| {
                e.message = e.message.replace(
                    "Prints this message or the help of the given subcommand(s)",
                    "🦮 Prints this message or the help of the given subcommand(s)",
                );
                e.exit();
            })
        // ...
    }
    ```
  This is of course an appalling dead unbecoming of man, women, and children, but programmers, as creatures of chaos, trickery, and destruction, cannot be held up to the same standard as humans. This code should as well be quite reliable: as a former developer of clap, I think that sooner [the skies turn red as blood and the sun goes dark at noon](https://abc7news.com/smoke-in-the-air-today-why-is-sky-orange-quality-index-oakland-bay-area/6414147/), [the earth shakes](https://www.sacbee.com/news/california/article245534855.html) and [plagues of locusts](https://www.bbc.com/future/article/20200806-the-biblical-east-african-locust-plagues-of-2020) cover the land than this part of the message change (`clap v2` branch is frozen and no longer developed).

**Comment by EverlastingBugstopper** [comment]
thank you for the helpful and hilarious response @CreepySkeleton - it's much appreciated :smile:

**Comment by azoyan** [comment]
Maybe there are more elegant solutions now?

**Comment by epage** [comment]
Keep in mind, the `help` subcommand's about is controlled by clap and not structopt.  Probably better to discuss concerns with customizing it over there.

**Comment by azoyan** [comment]
> Keep in mind, the `help` subcommand's about is controlled by clap and not structopt. Probably better to discuss concerns with customizing it over there.

Да, но мы используем structopt. 
It would be cool if there was a feature like this: 
```Rust
#[derive(StructOpt)]
#[structopt(help_message("🦮 Prints this message or the help of the given subcommand(s)"))]
pub enum Subcommand {
 // ...
}
```
