### ISSUE TITLE
Make structopt-derive's dependency on structopt optional

### ISSUE THREAD

**Issue by killercup** [TeXitoi/structopt#45]
So, I have a very weird request. I'm trying to re-export stuctopt-derive in a crate, but since this code

https://github.com/TeXitoi/structopt/blob/cc6dfd2e542440e4f194ce7823add4bf09ba9c22/structopt-derive/src/lib.rs#L907-L909

expands to `extern crate structopt`, my consumers would have to add structopt to their dependencies, which I want to avoid. Is there another option of doing this? E.g., making this part of the derive optional (with a feature flag).

cc https://github.com/killercup/quicli/issues/9

**Comment by TeXitoi** [comment]
This trick was taken to serde. Thus how do you manage serde case ?

Then, if you have the trick to only depend on structopt without depending on strict opted drive, I'm interested by the trick that may simplify this particular use case.

**Comment by TeXitoi** [comment]
The feature of this trick is to compile without the user needing to `extern crate structopt`

**Comment by killercup** [comment]
> Thus how do you manage serde case ?

By opening the same issue there as well, of course ;) https://github.com/serde-rs/serde/issues/1147

Since there are already some ideas in this thread, maybe we can discuss options there? Otherwise I'll let you know if you find a solution :)

> The feature of this trick is to compile without the user needing to extern crate structopt

And it's a great trick :) The thing is that my crate already re-exports `structopt::StructOpt;`, and users of quicli should always glob import the prelude that contains `StructOpt`. In such a case, the user doesn't need `extern crate structopt;`.
