### ISSUE TITLE
Question: how do I read a field?

### ISSUE THREAD

**Issue by garritfra** [TeXitoi/structopt#451]
Documentation of this crate is fine and dandy, but I could not find a single note about how to access the fields of the defined enum in my app. This is such a trivial thing that it must be documented. Did I overlook this?

**Comment by TeXitoi** [comment]
You need to be more precise. Can you give what you have, and were you don't know what to do?

**Comment by garritfra** [comment]
Consider this:

```rs
#[derive(StructOpt, Debug)]
enum Opt {
    #[structopt()]
    Build {
        in_file: PathBuf,
        #[structopt(short, long)]
        out_file: PathBuf,
    },
}

fn main() -> Result<(), String> {
    let opts = Opt::from_args();

    println!("{}", opts.<in_file>); <----
}
```

How do I access the `in_file` field here?

**Comment by TeXitoi** [comment]
That's a regular rust enum. https://doc.rust-lang.org/book/ch06-00-enums.html

```rust
match opts {
    Build { in_file, out_file } => println!("{:?} {:?}", in_file, out_file),
}
```

**Comment by garritfra** [comment]
Ah, I see. Apologies for my "didn't feel like googling"-attitude. I was in a hurry and jotted this down on my phone before leaving, but I should've figured this out myself. Nevertheless, I think this should be documented somewhere. I'll open a PR in a minute.
