### ISSUE TITLE
StructOptDefault: default implementation uses default values

### ISSUE THREAD

**Issue by whiterabbit42k** [TeXitoi/structopt#452]
I'd like to see something like this:

```rust
const PARTICLE_RADIUS: f32 = 0.5;
const SMOOTHING_FACTOR: f32 = 2.0;
const REST_DENSITY: f32 = 1000.0;

#[derive(StructOpt, Debug, Clone)]
pub struct FluidConfig {
    #[structopt(long, default_value = "0.5")]
    pub particle_radius: f32,
    #[structopt(long, default_value = "2.0")]
    pub smoothing: f32,
    #[structopt(long, default_value = "1000.0")]
    pub density: f32,
}

impl Default for FluidConfig {
    fn default() -> Self {
        Self {
            particle_radius: PARTICLE_RADIUS,
            smoothing: SMOOTHING_FACTOR,
            density: REST_DENSITY,
        }
    }
}
```

be able to be written like this:
```rust
const PARTICLE_RADIUS: f32 = 0.5;
const SMOOTHING_FACTOR: f32 = 2.0;
const REST_DENSITY: f32 = 1000.0;

#[derive(StructOpt, StructOptDefault, Debug, Clone)]
pub struct FluidConfig {
    #[structopt(long, default_value = PARTICLE_RADIUS)]
    pub particle_radius: f32,
    #[structopt(long, default_value = SMOOTHING_FACTOR)]
    pub smoothing: f32,
    #[structopt(long, default_value = REST_DENSITY)]
    pub density: f32,
}
```

or also this is ok:
```rust
#[derive(StructOpt, StructOptDefault, Debug, Clone)]
pub struct FluidConfig {
    #[structopt(long, default_value = "0.5")]
    pub particle_radius: f32,
    #[structopt(long, default_value = "2.0")]
    pub smoothing: f32,
    #[structopt(long, default_value = "1000.0")]
    pub density: f32,
}
```

where calling `FluidConfig::default()` has all the default values without needing the various forms of duplication in the first example (and hence potential source of mis-sync)

**Comment by CreepySkeleton** [comment]
I'm doubtful. This can only work with CLIs that have no required args, and I don't think it's a common case. Another problem, the first design (global constant of non-str type) is dead on arrival: 

* clap expects `&str`
* user wants `f32`, to be reused elsewhere (why would the user factor out the constant otherwise?)
* we have no idea what `PARTICLE_RADIUS` equals to from inside the macro and therefore cannot turn it into `&str` via `stringify!`.
  * `ToString` doesn't solve this problem. Even if we forget about reallocation, floating-point to string conversion is extremely hard to get right (you don't want any `default: 0.50000057914` in your help message, do you?). Perhaps could be solved by some clever algorithm, but I'd rather not to try.

Only the second design is feasible. @TeXitoi what do you think about it?

**Comment by TeXitoi** [comment]
I don't think that's a good idea to add this feature to structopt, that's too specific.

As a workaround, you can:

```rust
use structopt::StructOpt;

const PARTICLE_RADIUS: &str = "0.5";
const SMOOTHING_FACTOR: &str = "2.0";
const REST_DENSITY: &str = "1000.0";

#[derive(StructOpt, Debug, Clone)]
pub struct FluidConfig {
    #[structopt(long, default_value = PARTICLE_RADIUS)]
    pub particle_radius: f32,
    #[structopt(long, default_value = SMOOTHING_FACTOR)]
    pub smoothing: f32,
    #[structopt(long, default_value = REST_DENSITY)]
    pub density: f32,
}

impl Default for FluidConfig {
    fn default() -> Self {
        Self {
            particle_radius: PARTICLE_RADIUS.parse().unwrap(),
            smoothing: SMOOTHING_FACTOR.parse().unwrap(),
            density: REST_DENSITY.parse().unwrap(),
        }
    }
}
```

Or, simpler, but with a somethat costy default implementation:

```rust
use structopt::StructOpt;

const PARTICLE_RADIUS: &str = "0.5";
const SMOOTHING_FACTOR: &str = "2.0";
const REST_DENSITY: &str = "1000.0";

#[derive(StructOpt, Debug, Clone)]
pub struct FluidConfig {
    #[structopt(long, default_value = PARTICLE_RADIUS)]
    pub particle_radius: f32,
    #[structopt(long, default_value = SMOOTHING_FACTOR)]
    pub smoothing: f32,
    #[structopt(long, default_value = REST_DENSITY)]
    pub density: f32,
}

impl Default for FluidConfig {
    fn default() -> Self {
        FluidConfig::from_iter(&[""])
    }
}
```

**Comment by CreepySkeleton** [comment]
I was wrong. Default `ToString` impl for `f32` works fine. I kinda remember seeing `1.0` turning `"1.00000000342"`, but I think we're free from it so long we don't do math on floating point.

**Comment by whiterabbit42k** [comment]
So re usefulness, I can't speak to others, but this comes up quite frequently for me. I have config structs that can also be used as command line arguments. When the config forms part of the cli (and flatten becomes incredibly useful here), it substantially reduces config boilerplate, allows very fast iteration and experimentation, etc. E.g., when testing particle size (which the solver also needs to know, hence it's a config parameter), one simply reruns `cargo run -- --particle-size 1.0`. I have about 5-7 different config/cli structs that have this pattern, which can be mix and matched, and composed into different applications, so  generally find this pattern useful; the only ergonomic papercut is the duplication (and which i'm hoping to solve) is the duplication of defaulted values, e.g., i have to type `default_value = "0.5"` and then in the default implementation i have to type the unstringified version of this, which as i said has caused and will likely continue to cause subtle typo-based bugs around stringly typing things and forgetting to update one of the default values, etc.

For the first workaround, this seems strictly worse than what I have above? The constants are now stringly typed, and i still have to type them twice, but at least i don't type the _values_ twice which is a good property, and solves one of my problems.

This workaround seems like the best so far?

```
#[derive(StructOpt, Debug, Clone)]
pub struct FluidConfig {
    #[structopt(long, default_value = "0.5")]
    pub particle_radius: f32,
    #[structopt(long, default_value = "1.0")]
    pub smoothing: f32,
    #[structopt(long, default_value = "1000.0"]
    pub density: f32,
}

impl Default for FluidConfig {
    fn default() -> Self {
        FluidConfig::from_iter(&[""])
    }
}
```
but still not great. (for my usecases i dont' care about the default implementation being "expensive" so much)

**Comment by Pand9** [comment]
Yes I also stumbled upon this. "This can only work with CLIs that have no required args, and I don't think it's a common case." - whole CLIs rarely have no required args - but flattened structs quite often do.
