### ISSUE TITLE
issue with quoted parameters

### ISSUE THREAD

**Issue by divinusdracodominus** [TeXitoi/structopt#454]
perhaps this is intentional, I don't know, but it is somewhat inconvenient to not be able to pass in multi-word command line arguments in the form of --flag "this is what I want passed in". this kind of makes it difficult to pass in things like descriptions, names, etc.

**Comment by CreepySkeleton** [comment]
I don't quite get what you're asking, exactly.

* If you want the quoted string to be treated as one argument, for instance `app --flag "path to file.txt"`, that's the default behavior, no extra setup required.
* If you want the string to be treated as a sequence of multiple arguments delimited by space, this is also supported but need some extra setup:
  ```rust
  #[structopt(long, value_delimiter = " ")]
  flag: Vec<String>
  ```
  ```
  app --flag "file1.txt file2.txt" 
                  |
                  will yield vec!["file1.txt", "file2.txt"]
  ```

If that doesn't answer your question, please follow up with some code showing what you're trying to do.
