### ISSUE TITLE
feature: support collection of the rest of flags and options

### ISSUE THREAD

**Issue by efikarl** [TeXitoi/structopt#455]
For example, I'd like to create a cmd wapper of "ipmitool":
```rust
/// Hosts management tool and ipmitool wrapper
struct Opts {
    #[structopt(subcommand)]
    cmd: Option<Command>,

    /// Override inteface <lanplus>
    #[structopt(short = "I")]
    interface: Option<String>,

    /// The ipmitool args to process
    ipmitool_args: Vec<String>,
}
```
I don't know if there is a way to collect all other arguments into `ipmitool_args`. And for example when I:
```powershell
❯ ipmi.exe -b    
error: Found argument '-b' which wasn't expected, or isn't valid in this context

USAGE:
    ipmi.exe [OPTIONS] [ipmitool-args]... [SUBCOMMAND]

For more information try --help
❯
```
There would be a error about `-b`. But if there is a magical methods like `accept_rest_flags_and_options`
```rust
#[derive(StructOpt, Debug)]
/// Hosts management tool and ipmitool wrapper
struct Opts {
    #[structopt(subcommand)]
    cmd: Option<Command>,

    /// Override inteface <lanplus>
    #[structopt(short = "I")]
    interface: Option<String>,

    /// The ipmitool args to process
    #[structopt(accept_rest_flags_and_options)]
    ipmitool_args: Vec<String>,
}
```
That would be great for this case.

BR,
Karl

**Comment by CreepySkeleton** [comment]
The closest you can get is `cargo`-like style: 
```rust
#[derive(StructOpt, Debug)]
/// Hosts management tool and ipmitool wrapper
struct Opts {
    #[structopt(subcommand)]
    cmd: Option<Command>,

    /// Override inteface <lanplus>
    #[structopt(short = "I")]
    interface: Option<String>,

    /// The ipmitool args to process
    #[structopt(setting = ArgSettings::Last)]
    ipmitool_args: Vec<String>,
}
```
Invoke as
```
ipmi.exe -I -- -b
```

**Comment by efikarl** [comment]
> The closest you can get is `cargo`-like style:
> 
> ```rust
> #[derive(StructOpt, Debug)]
> /// Hosts management tool and ipmitool wrapper
> struct Opts {
>     #[structopt(subcommand)]
>     cmd: Option<Command>,
> 
>     /// Override inteface <lanplus>
>     #[structopt(short = "I")]
>     interface: Option<String>,
> 
>     /// The ipmitool args to process
>     #[structopt(setting = ArgSettings::Last)]
>     ipmitool_args: Vec<String>,
> }
> ```
> 
> Invoke as
> 
> ```
> ipmi.exe -I -- -b
> ```

Thank you very much.

**Comment by efikarl** [comment]
Sorry, when I add `#[structopt(setting = ArgSettings::Last)]`:
```powershell
error[E0433]: failed to resolve: use of undeclared type `AppSettings`
  --> src\main.rs:37:27
   |
37 |     #[structopt(setting = AppSettings::Last)]
   |                           ^^^^^^^^^^^ use of undeclared type `AppSettings`

error[E0599]: no method named `setting` found for struct `Arg<'_, '_>` in the current scope
  --> src\main.rs:37:17
   |
37 |     #[structopt(setting = AppSettings::Last)]
   |                 ^^^^^^^ method not found in `Arg<'_, '_>`

error: aborting due to 2 previous errors
```
Crate info: `name = "structopt" version = "0.3.21"`

**Comment by TeXitoi** [comment]
`structopt::clap::AppSettings::Last`

**Comment by efikarl** [comment]
> `structopt::clap::AppSettings::Last`

No `Last` in `clap::AppSettings`  when I use `structopt::clap::AppSettings::Last;`.

Then I use `use structopt::clap::ArgSettings;`
```rust
use structopt::clap::ArgSettings;
#[derive(StructOpt, Debug)]
/// Hosts management tool and ipmitool wrapper
struct Opts {
    #[structopt(subcommand)]
    cmd: Option<Command>,

    /// Override inteface <lanplus>
    #[structopt(short = "I")]
    interface: Option<String>,

    /// The ipmitool args to process
    #[structopt(setting = ArgSettings::Last)]
    ipmitool_args: Vec<String>,
}
```
And the result is:
```powershell
error[E0599]: no method named `settings` found for struct `Arg<'_, '_>` in the current scope
  --> src\main.rs:38:17
   |
38 |     #[structopt(settings = ArgSettings::Last)]
   |                 ^^^^^^^^ method not found in `Arg<'_, '_>`

error: aborting due to previous error
```
So, my question is: is `settings` supported by structopt now?

**Comment by TeXitoi** [comment]
There is no such things as "structopt support", it supports everything clap propose. The method is not `setting` on `Arg`, but `set`

```rust
use structopt::clap::ArgSettings;
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
/// Hosts management tool and ipmitool wrapper
struct Opt {
    #[structopt(subcommand)]
    cmd: Option<Command>,

    /// Override inteface <lanplus>
    #[structopt(short = "I")]
    interface: Option<String>,

    /// The ipmitool args to process
    #[structopt(set = ArgSettings::Last)]
    ipmitool_args: Vec<String>,
}

#[derive(StructOpt, Debug)]
enum Command {
    Run,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

**Comment by TeXitoi** [comment]
Also, you don't really need this `ArgSettings::Last`, as, if you have only one positional argument as here, it will have the same behavior without this option.

**Comment by efikarl** [comment]
@TeXitoi @CreepySkeleton Thank you all, it works now.

**Comment by CreepySkeleton** [comment]
> 
> 
> Also, you don't really need this `ArgSettings::Last`, as, if you have only one positional argument as here, it will have the same behavior without this option.

True, but it won't process `-b` flag-like extra args. Cargo-like style is the safest option.
