### ISSUE TITLE
Feature request: strict positional argument with #[structopt(parse)] attribute

### ISSUE THREAD

**Issue by paulrberg** [TeXitoi/structopt#456]
It looks like as of version [0.3.21](https://docs.rs/structopt/0.3.21/structopt/), it is not possible to have a required positional argument that also receives a `#[structopt(parse)]` attribute without making the same argument an option as well.

Take this example:

```rust
#[derive(StructOpt)]
pub struct Cli {
    pub contract_path: PathBuf,
}
```

This would generate a required positional argument, as per the output of `cargo run -- --help`:

```
USAGE:
    multisol [OPTIONS] <contract-path>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --no-optimization <no-optimization>    Disable the Solidity optimizer, which is enabled by default

ARGS:
    <contract-path>    The path to the Solidity contract to look for
```

But I would like to parse the `contract_path` field from an `OsStr` type, like this:

```rust
#[derive(StructOpt)]
pub struct Cli {
  #[structopt(long, parse(from_os_str))]
  pub my_path: Pathbuf,
}
```

The catch is that this will make the `contract_path` field an option, not just a positional argument:

```rust
USAGE:
    multisol [OPTIONS] --contract-path <contract-path>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --contract-path <contract-path>        The path to the Solidity contract to look for
        --no-optimization <no-optimization>    Disable the Solidity optimizer, which is enabled by default
```

It would be nice if I could have strictly positional arguments that can receive `#[structopt(parse)]` attributes without turning them into options. Thanks!

**Comment by TeXitoi** [comment]
`long` mean long option, just remove long:

```rust
use std::path::PathBuf;
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
pub struct Cli {
    #[structopt(parse(from_os_str))]
    pub my_path: PathBuf,
}

fn main() {
    let opt = Cli::from_args();
    println!("{:?}", opt);
}
```

**Comment by paulrberg** [comment]
Oh, I see. Thanks @TeXitoi!
