### ISSUE TITLE
Parsing complex data into list

### ISSUE THREAD

**Issue by elkowar** [TeXitoi/structopt#457]
One thing that, as far as i can tell, is not yet really possible with structopt is parsing more complicated invocations as lists.
What i mean by this is that it could be possible to allow for something like
```rust
#[derive(StructOpt)]
pub enum SomeSubCommand {
  #[structopt(name = "open")]
  OpenWindow(Vec<OpenWindow>)
  // and others, if desired, of course
}

#[derive(StructOpt)]
pub struct OpenWindow {
  name: String,
  #[structopt(short)]
  x: i32,
  #[structopt(short)]
  y: i32,
}
```

Which would then result in the command line API
```sh
myapp open \
  foo -x 12 -y 12 \
  bar -x 100 -y 200 \
  baz -x 200 -y 250
```
  
  Resulting in a data-structure of
```rs
SomeSubCommand::OpenWindow(vec![
    OpenWindow { name: "foo", x: 12, y: 12 },
    OpenWindow { name: "bar", x: 100, y: 200 },
    OpenWindow { name: "baz", x: 200, y: 250 }
])
 ```

With the current structopt featureset, the only way i could see how i could implement this API would be to use an external subcommand, with which I'd loose most of the niceties offered by structuopt.

**Comment by TeXitoi** [comment]
AFAIK, clap can't parse this, and structopt rely on clap for parsing (structopt is "just" an interface to clap).

**Comment by elkowar** [comment]
Right, makes sense! I'll close this and file an issue with clap instead :thumbsup:

**Comment by elkowar** [comment]
Note: after a quick look, it seems that an issue for this already exists in clap: https://github.com/clap-rs/clap/issues/1704
Progress seems to be going rather slowly though :/
