### ISSUE TITLE
Change the default output of structopt.

### ISSUE THREAD

**Issue by willdoescode** [TeXitoi/structopt#460]
When no parameters are passed there should be a way to modify that output to your liking.

**Comment by tejasag** [comment]
I agree

**Comment by TeXitoi** [comment]
Can you elaborate? I don't understand what you mean. An complete example, the actual behavior, and what you'd like would help.

**Comment by willdoescode** [comment]
is there a way to display other text than the default help menu when no arguments are passed?

**Comment by TeXitoi** [comment]
Depending on your structopt, no argument might success. I suppose you mean to customize the message in case of error?

Maybe you are searching for https://docs.rs/clap/2.33.3/clap/struct.App.html#method.usage ?

```rust
#[structopt(usage = "Don't put argument!")
struct Opt {}
```

**Comment by willdoescode** [comment]
That didn't do it but it seems as though what I was looking for was
```
#[structopt(usage = "Don't put argument!", help = "custom help")
struct Opt {}
```
Thanks for responding fast!

**Comment by TeXitoi** [comment]
Welcome.
