### ISSUE TITLE
Error using completions in zsh

### ISSUE THREAD

**Issue by MrDogeBro** [TeXitoi/structopt#461]
When trying to generate completions for my cli, I get this error every time zsh loads. Weird thing though is that if I tell it to use bash and not zsh completions, it works just fine and completions work, etc. I am using oh-my-zsh if that would affect it in any way. Any help/explanations would be greatly appreciated.

**Error:**
```
_arguments:comparguments:312: can only be called from completion function
```

**Code:**
```rust
Quicknav::clap().gen_completions_to("quicknav", Shell::Zsh, &mut std::io::stdout());
```

**Comment by TeXitoi** [comment]
You'll have to ask to clap, as `.get_completions_to` is a clap function, and give more information to be able to reproduce the bug (as the Quicknav struct with structopt annotations)

**Comment by TeXitoi** [comment]
Also, it looks like a function is used in a wrong context, are you sure you call the script correctly? (I don't know anything about zsh)

**Comment by gakonst** [comment]
For anyone bumping on this issue, here's the relevant Clap ones:
* https://github.com/clap-rs/clap/issues/2488
* https://github.com/clap-rs/clap/issues/1596

And how to config compinit in zsh https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#telling-zsh-which-function-to-use-for-completing-a-command
