### ISSUE TITLE
not document a parameter

### ISSUE THREAD

**Issue by emmanueltouzery** [TeXitoi/structopt#462]
would it be possible to have a parameter, handled by structopt (not skipped), but not documented in --help?

I have one special command-line option that is of more internal use, and I'd rather not document it in `--help`.

**Comment by TeXitoi** [comment]
https://docs.rs/clap/2.33.3/clap/struct.Arg.html#method.hidden

So something like

```rust
#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(short, long, hidden = true)]
    secret_parameter: Option<String>,
}
```

**Comment by emmanueltouzery** [comment]
Well, I apologize. I assumed it was possible, but couldn't find it. I was searching in the structopt apidocs, i didn't know to search also in the clap apidocs.

Well, thank you for answering, and thank you for a great library!

**Comment by TeXitoi** [comment]
No problem.
