### ISSUE TITLE
`required_if` silently useless when trying to check a flag value

### ISSUE THREAD

**Issue by MathieuDuponchelle** [TeXitoi/structopt#464]
Apologies if I misunderstood the feature, but:

```
extern crate structopt;

use structopt::StructOpt;
use std::path::PathBuf;

#[derive(Debug, StructOpt)]
#[structopt(name = "required_if_broken", about = "required_if not working")]
struct Opt {
    #[structopt(long)]
    foo: bool,

    #[structopt(long, required_if("foo", "true"))]
    output_file: Option<PathBuf>,
}


fn main() {
    let opt = Opt::from_args();

    eprintln!("Foo: {}, output_file: {:?}", opt.foo, opt.output_file);
}
```

prints `Foo: true, output_file: None`, I would expect it to print an error and exit?

**Comment by MathieuDuponchelle** [comment]
Run with `cargo run -- --foo` of course :)

**Comment by TeXitoi** [comment]
foo is a flag, not an option, thus, it has no value, and so its value is never "true".

So, maybe what you want is 

```rust
use std::path::PathBuf;
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
#[structopt(name = "required_if_broken", about = "required_if not working")]
struct Opt {
    #[structopt(long, requires("output-file"))]
    foo: bool,

    #[structopt(long)]
    output_file: Option<PathBuf>,
}

fn main() {
    println!("{:?}", Opt::from_args());
}
```

**Comment by MathieuDuponchelle** [comment]
Yes, perfect, thanks! Is it possible to somehow detect that pattern and warn the programmer? If not, feel free to close, retitling :)

**Comment by TeXitoi** [comment]
That's not possible in structopt, it just forward calls to clap without even knowing the method exists. It might be feasible in clap.

**Comment by najamelan** [comment]
@TeXitoi I have a similar issue but in the opposite sense. I have required options, but if `--version` is given I just want to output the version and exit and thus they shouldn't be required. Is there a way to express that? Ideally I would like to not have to put my required options in an `Option`, but that is extra.

**Comment by TeXitoi** [comment]
Automatic --version does that by default.

**Comment by najamelan** [comment]
Thanks for clarifying. It seems to be because I was trying to manually format my version. Thus I had a field in my struct for version.

I now figured out how to override the version for clap and format it with `const_format` at compile time. 

Thanks for responding, it put me in the right direction.

**Comment by kianenigma** [comment]
`bool` aside, shouldn't this trivial example with `String` work just fine? 

```
use structopt::StructOpt;

#[derive(StructOpt)]
struct Command {
	#[structopt(long)]
	pub arg1: String,

	#[structopt(
		long,
		required_if("arg1", "foo")
	)]
	pub arg2: String,
}

fn main() {
	let _ = Command::from_args();
}
```

`cargo run -- --arg1 xxx` still complains about missing `arg2`.

**Comment by TeXitoi** [comment]
you need options to allow "not required" on your options:

```rust
use structopt::StructOpt;

#[derive(Debug, Default, StructOpt)]
struct Opt {
    #[structopt(long)]
    pub arg1: Option<String>,

    #[structopt(long, required_if("arg1", "foo"))]
    pub arg2: Option<String>,
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

```
$ cargo run -- --arg1 xxx
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/test-rs --arg1 xxx`
Opt { arg1: Some("xxx"), arg2: None }
$ cargo run -- --arg1 foo
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/test-rs --arg1 foo`
error: The following required arguments were not provided:
    --arg2 <arg2>

USAGE:
    test-rs --arg1 <arg1> --arg2 <arg2>

For more information try --help
$ cargo run -- --arg1 foo --arg2 xxx
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/test-rs --arg1 foo --arg2 xxx`
Opt { arg1: Some("foo"), arg2: Some("xxx") }
$ 
```

**Comment by kianenigma** [comment]
Thanks! and how is it with subcommands? 

```rust 
use structopt::StructOpt;

#[derive(StructOpt)]
struct Command {
	#[structopt(long)]
	pub arg1: String,

	#[structopt(
		long,
		required_if("sub", "foo")
	)]
	pub arg2: Option<String>,

	#[structopt(subcommand)]
	pub sub: SubCommands
}

#[derive(Debug, Clone, StructOpt)]
enum SubCommands {
	Foo,
	Bar
}

fn main() {
	let _ = Command::from_args();
}
```

**Comment by TeXitoi** [comment]
Normally, if an argument is needed with a subcommand, better to put the argument in the subcommand as a required argument (just not an option).

Then, the functionality is to be searched in clap documentation. I didn't find anything about such a feature after a light search, but maybe there is a way to do it.

**Comment by kianenigma** [comment]
> Normally, if an argument is needed with a subcommand, better to put the argument in the subcommand as a required argument (just not an option).

yeah that's a reasonable and explicit way to go about it. The only downside is that since it is needed in multiple subcommands, it would cause some duplication.

**Comment by TeXitoi** [comment]
you can just use a struct "ThingConfiguration" with the different options, and flatten it in each subcommand that use it.
