### ISSUE TITLE
`no_version` have to be marked twice to hide version info of subcommand

### ISSUE THREAD

**Issue by loichyan** [TeXitoi/structopt#465]
In code below, I have to mark `no_version` at both **P1** and **P2** to hide version info of `sub1`.  For subcommands, their version info should be successfully hided when I marked `no_version` anywhere.

```rust
use structopt::clap::AppSettings::DisableVersion;

#[derive(structopt::StructOpt)]
enum Cmd {
    #[structopt(no_version)]  // P1
    Sub1(Sub1),
}

#[derive(structopt::StructOpt)]
#[structopt(
    no_version,  // P2
    global_settings = &[DisableVersion])]
struct Sub1 {}

#[paw::main]
fn main(cmd: Cmd) {
    match cmd {
        Cmd::Sub1(_s1) => {}
    }
}
```

BTW, this sounds a little similar to #324.

**Comment by TeXitoi** [comment]
There is no way of removing the version of a subcommand, as the different enum can't know each others.

The real solution to this problem would be to have no default version handling, and a argument less `version` to find automatically the version number. It would be coherent with authors. But that's a breaking change, and that's not enough to justify a new major version.
