### ISSUE TITLE
Short-hands boolean

### ISSUE THREAD

**Issue by Milo123459** [TeXitoi/structopt#468]
I want to make it so I can do -d or --dry, i know how to do alias' but I don't want to make it so you have to specify true. For example:
--dry would mean it is true
--dry true would mean it is true
without the flag it'd be false.

**Comment by TeXitoi** [comment]
```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(long, short, min_values(0), max_values(1), possible_value("true"))]
    dry: bool,
}

fn main() {
    println!("{:?}", Opt::from_args());
}
```

But I suspect you also want to support `-d false`, and I don't have the tricky idea just now.

**Comment by Milo123459** [comment]
Yes, I do want -d false, and do you mean that's not possible in the lib right now? or, you haven't  got it off the top of your head

**Comment by TeXitoi** [comment]
That's not really made for that, but a workaround might exists.

**Comment by TeXitoi** [comment]
```rust
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(long, short)]
    dry: Option<Option<bool>>,
}
impl Opt {
    fn dry(&self) -> bool {
        match self.dry {
            None => false,
            Some(None) => true,
            Some(Some(a)) => a,
        }
    }
}

fn main() {
    println!("{:?}", Opt::from_args().dry());
}
```

Not so elegant, but works.

**Comment by Milo123459** [comment]
Thanks for the help 😉
