### ISSUE TITLE
How can I use the `write_help` method from claptrap App?

### ISSUE THREAD

**Issue by zwhitchcox** [TeXitoi/structopt#469]
The [documentation](https://docs.rs/structopt/0.3.21/structopt/#attributes) claims structopt just creates a `clap` `App` with attributes, but the `write_help` method is not available.

Is there anyway to access the underlying `clap` `App` So, I can use the [features from it](https://docs.rs/clap/2.33.3/clap/struct.App.html)?

**Comment by TeXitoi** [comment]
https://docs.rs/structopt/0.3.21/structopt/trait.StructOpt.html#tymethod.clap

**Comment by zwhitchcox** [comment]
Oh, great, thanks!

**Comment by TeXitoi** [comment]
Welcome
