### ISSUE TITLE
support `requires_all`

### ISSUE THREAD

**Issue by bluejekyll** [TeXitoi/structopt#47]
It looks like `requires_all` is not supported, is this correct? I couldn't come up with a combination where it works.

**Comment by TeXitoi** [comment]
It should be possible using the `_raw` feature. Something like
```rust
#[structopt(requires_all_raw = "&[\"input\", \"output\"]")]
config: String,
```

(not tested)

**Comment by bluejekyll** [comment]
Ah, thanks! I didn't see that documented anywhere, and tried different variations of that. That works.
