### ISSUE TITLE
Apply #[structopt(short)] to subcommands

### ISSUE THREAD

**Issue by okamiterasu** [TeXitoi/structopt#472]
Would it be possible to allow specifying a short flag for a subcommand and let it be treated like a regular flag such that 
```rust
#[derive(StructOpt)]
struct App{
    #[structopt(subcommand)]
    sub: Cmd,

    #[structopt(short = "b")]
    bar: bool
}

#[derive(StructOpt)]
enum Cmd{
    #[structopt(short = "F")]
    Foo{
        #[structopt(short = "q")]
        quix: bool
    }
}
```
was valid and could be used like ```./app -Fqb```?

**Comment by TeXitoi** [comment]
If you can do it with clap, it's possible. But I don't think that's possible with clap.

Why do you want to do that?

**Comment by pksunkara** [comment]
short flags for subcommands is possible in clap v3

**Comment by okamiterasu** [comment]
> 
> 
> short flags for subcommands is possible in clap v3

Thanks for the heads-up. That's exactly what I needed.
