### ISSUE TITLE
Custom version flag

### ISSUE THREAD

**Issue by Milo123459** [TeXitoi/structopt#473]
Is there anyway to program a custom version flag?

**Comment by TeXitoi** [comment]
You can `no_version` on the struct attribute and then add a `#[structopt(long)] version:bool` as field, if that's what you want?

**Comment by Milo123459** [comment]
I just meant like removing the default -v flag and replacing it with a custom one, so I think it should work.

**Comment by TeXitoi** [comment]
So no_version should be what your are searching. If that's solve your problem, please close the issue, if not please explain why not.
