### ISSUE TITLE
Suggestion for different argument parsing

### ISSUE THREAD

**Issue by Milo123459** [TeXitoi/structopt#474]
Something that I think is just a little broken is the fact that for every argument you have to do something like this:
`project -- --foo=bar -- ....` when I personally think you should be able to do something along the lines of
`project --foo=bar -- ....` - it would make it simpler in my opinion.

**Comment by Milo123459** [comment]
Remove the first -- at the start, because I don't see a point for it personally.

**Comment by TeXitoi** [comment]
If you mean `cargo run -- --foo=bar -- argument`, that's cargo, not structopt. cargo must do the difference between the argument of it's subcommand run and the argument of the program, passed after `--`.

If that's not the problem, please be more precise if you want I understand your problem.

**Comment by TeXitoi** [comment]
```
gpinot@xps13:~/dev/test-rs$ cat src/main.rs
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(long)]
    foo: String,
    arg: String,
}

fn main() {
    println!("{:?}", Opt::from_args());
}
$ cargo run -- --foo=bar -- something
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/test-rs --foo=bar -- something`
Opt { foo: "bar", arg: "something" }
$ ./target/debug/test-rs --foo=bar -- something
Opt { foo: "bar", arg: "something" }
$ 
```

**Comment by Milo123459** [comment]
I know, the issue is that in the production binary requires -- at the start, for example:
```rs
impl Arguments {
	pub fn dry(&self) -> bool {
		match self.dry {
			None => false,
			Some(None) => true,
			Some(Some(a)) => a,
		}
	}
}
``` It won't work if I do `binary --dry -- ...` but does if I do `binary -- --dry -- ...`

**Comment by TeXitoi** [comment]
I don't understand. Please provide a complete example that I can compile and run.

**Comment by Milo123459** [comment]
Here is my [project](https://github.com/Milo123459/glitter) install it and run `glitter push --dry -- push x y z`

**Comment by TeXitoi** [comment]
Why do you use `Option<Option<bool>>`, that's a strange use, what are your expectations on that?

**Comment by Milo123459** [comment]
> Why do you use `Option<Option<bool>>`, that's a strange use, what are your expectations on that?

I used it for some checks in some other files. Pretty odd, I agree. There probably is a better way to do it


And I think I was using it wrong... Thanks for the help as always.
