### ISSUE TITLE
Assigning `short` changes nothing.

### ISSUE THREAD

**Issue by Milo123459** [TeXitoi/structopt#478]
Hello!

I had some code like this:
```rs
	/// if the branch is not on the hosted provider, call this
	#[structopt(long, short = "nh")]
	pub(crate) nohost: Option<Option<bool>>,
``` 

and I thought that the short would be -nh, but no, it's still -n as the short. Any ideas why?

**Comment by TeXitoi** [comment]
https://docs.rs/clap/2.33.3/clap/struct.Arg.html#method.short

short is one character, allowing `-fn` to be the same as `-f -n`
