### ISSUE TITLE
Default to Some(None) or Some(value) for Option<Option<T>>

### ISSUE THREAD

**Issue by d34db4b3** [TeXitoi/structopt#481]
I think i have the same needs as the issue #123 and i can't figure out what to do.

I'm trying to have an optional argument that have a default value when set and can be overriden:
```
app -v test # v = Some(Some("test"))
app -v # v = Some(None) or v = Some(Some("default"))
app # v = None
```

I can produce a similar behavior using ```Vec``` (```Option<Vec<T>>```)
```
#[derive(StructOpt)]
pub struct Opt {
    #[structopt(parse(from_os_str), short)]
    pub v: Option<Vec<PathBuf>>,
}
```

```
app -v test # v = Some(["test"])
app -v # v = Some([])
app # v = None
```

Why does ```Option<Option<T>>``` doesn't accept an empty argument as ```Some(None)``` (fails with error: ```error: The argument '-v <v>' requires a value but none was supplied```) ?

Thanks

**EDIT**: i mentionned ```Option<Option<T>>``` but if it would be possible to set a default value, an ```Option<T>``` would be enough:
```
app -v test # v = Some("test")
app -v # v = Some("default")
app # v = None
```

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/structopt/blob/master/tests/options.rs#L153-L176

Your Option<Option> should work, need a failing example to help you.

A workaround to have a default is to implement a getter:

```rust
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(short, long)]
    foo: Option<Option<String>>,
}
impl Opt {
    fn foo(&self) -> Option<&str> {
        match &self.foo {
            None => None,
            Some(None) => Some("default"),
            Some(Some(s)) => Some(s),
        }
    }
}

fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt.foo());
}
```

**Comment by TeXitoi** [comment]
Can we close this? Or there is still something wrong?

**Comment by TeXitoi** [comment]
Feel free to reopen if you have any question.
