### ISSUE TITLE
Bug: Version is always suffixed with Error:

### ISSUE THREAD

**Issue by Milo123459** [TeXitoi/structopt#484]
Example: ![img](https://salvage.is-inside.me/FjsRHNeM.png)

Code: https://github.com/Milo123459/salt

**Comment by TeXitoi** [comment]
https://docs.rs/clap/2.33.3/clap/enum.ErrorKind.html#variant.VersionDisplayed

I'd just use from_args instead of from_arg_safe in main, as that's the result in main that should print this unwanted text.

**Comment by Milo123459** [comment]
Let me try.

**Comment by Milo123459** [comment]
Works. Thank you!
