### ISSUE TITLE
boolean flag becomes pseudo-option when `env` is used

### ISSUE THREAD

**Issue by Follpvosten** [TeXitoi/structopt#488]
Gonna get right to the point; this struct:
```rust
#[derive(StructOpt)]
struct Opt {
    #[structopt(short, long)]
    dry_run: bool,
}
```
results in a flag, as expected:
```rust
FLAGS:
    -d, --dry-run    
    -h, --help       Prints help information
    -V, --version    Prints version information
```
but once you add an env fallback to the flag:
```rust
#[derive(StructOpt)]
struct Opt {
    #[structopt(short, long, env = "DRY_RUN")]
    dry_run: bool,
}
```
it confusingly becomes an option:
```rust
FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -d, --dry-run <dry-run>     [env: DRY_RUN=]
```
I don't think it should.

Another interesting point here is that the `[env: DRY_RUN=]` thing is a bit confusing as well, because a boolean env flag counts as true once the variable is set to *anything*, including empty, which means running the executable with `DRY_RUN=` doesn't change the output, but the behavior.

**Comment by TeXitoi** [comment]
Env is not adapted to flags in clap. So structopt can't do much.

Possibly related issue: https://github.com/clap-rs/clap/issues/2539

**Comment by Follpvosten** [comment]
Ah, for some reason, I had assumed this was a structopt-specific feature. I know better now. Thanks!

**Comment by rami3l** [comment]
@Follpvosten Hello! Just coming by to tell you that you're not alone :)

I also encountered the same problem, and I just got my fix merged in `clap`: https://github.com/clap-rs/clap/pull/2664.

**Comment by Follpvosten** [comment]
@rami3l Hi! That's nice to know. Maybe I should just start using the clap 3 beta instead of structopt anyways, docs have kept me from doing that so far...

**Comment by rami3l** [comment]
@Follpvosten Please note that the last `clap` release (even `beta2`) is made a long time ago.

This is a bit awkward, but I have to use `master` instead of `beta2` to get the right behavior, which however will not work if you want to publish your crate. Do think carefully before you make the switch :)

**Comment by Follpvosten** [comment]
@rami3l Don't worry, I'm just using clap/structopt for some internal (non-open source) tools (which also already depend on async-graphql git), so I'm already familiar with that and it doesn't affect me.
Thank you anyways!
