### ISSUE TITLE
Better Error handling

### ISSUE THREAD

**Issue by TeXitoi** [TeXitoi/structopt#5]
The custom derive should dump great error message instead of just generating dumb code in case of bad usage.

**Comment by williamyaoh** [comment]
The way I'd want to do this would be to not use `syn` to parse the input tokens and instead have `structopt` do its own validation/parsing. `syn` is already making use of a `nom` parser, so the idea would be to rip out some code from `syn` and write a parser to generate data structures specifically for use by `structopt`. This would also make it easier to write the code generation itself; we wouldn't need `assert`s sprinkled around and such.

**Comment by TeXitoi** [comment]
I think this will be overkill to do that like that.

**Comment by CreepySkeleton** [comment]
@TeXitoi 
Hi guys, I made a tool exactly for this purpose: https://github.com/CreepySkeleton/proc-macro-error . It should be relatively easy (mostly replace `panic`s with `span_error` and similar) to integrate and I would do it if you don't mind. What do you think?

**Comment by TeXitoi** [comment]
I thought it was now integrated directly in syn, but it seems you know better than me the proc macro ecosystem ;-)

Sure, I'll accept with pleasure. For perfect errors, you might have to change some code around to not loose span information.

**Comment by CreepySkeleton** [comment]
For the record: AFAIK `syn` has nothing to do with error reporting, it's almost entirely about parsing. There is `proc_macro::Diagnostics` which *is* for error reporting but is still expiremental. 

Just so you know - I *am* working on this, will make a PR in two days or so

**Comment by TeXitoi** [comment]
OK, seeing the span handling from a bit away in syn confused me about that.

I wait for your PR! Thanks!

**Comment by CreepySkeleton** [comment]
@TeXitoi By the way, I think we can close this

**Comment by TeXitoi** [comment]
Of course. Thanks again.
