### ISSUE TITLE
#[structopt(allow_hyphen_values = true]) compiles but does not work

### ISSUE THREAD

**Issue by nstinus** [TeXitoi/structopt#510]
Hi,

I am trying to allow an i32 positional argument and I can't parse negative inputs.
I have tried using
```
#[structopt(allow_hyphen_values = true]) 
arg: i32,
```
to no avail.

I'll greatly appreciate any help.

Thanks!

**Comment by DominikRusso** [comment]
Try `#[structopt(settings = &[AppSettings::AllowNegativeNumbers])]` on a top level field.

**Comment by TeXitoi** [comment]
Yeah, allow_hypen_values is for options, not for args.

Also, please provide a complete compiling example when you have a question, explaining the actual behavior and the expected behavior. It will be much easier to understand the question.
