### ISSUE TITLE
Question: future of clap and structopt

### ISSUE THREAD

**Issue by epage** [TeXitoi/structopt#516]
With clap 3.0.0-rc.0 out and a definite timetable for clap 3, what are the current plans for how our crates will collaborate moving forward?

**Comment by TeXitoi** [comment]
structopt stay on clap 2, and only bugfix release will be published one time clap3 is out. New feature should go to clap derive.

**Comment by epage** [comment]
To ensure none of the remaining work is lost, we plan to [copy the open issues over](https://github.com/clap-rs/clap/issues/3071).

**Comment by yerke** [comment]
Thank you for all your work @TeXitoi !
