### ISSUE TITLE
Document relation to clap v3's derive feature

### ISSUE THREAD

**Issue by dmarku** [TeXitoi/structopt#521]
Hi altogether!

I've noticed that [clap 3.0.0][clap-v3] integrates StructOpt into its `derive` feature. Does this affect the future of StructOpt as a standalone project? If it's preferred to start new projects with clap + derive and migrate existing projects away from StructOpt, I'd like to suggest adding a short (deprecation) note to the top of the StructOpt Readme and docs.rs pages so that users who are directly visiting StructOpt documentation become aware of that and can act accordingly. I could set up an initial Pull Request if you wish. :slightly_smiling_face:

For context: I started a small commandline app in Rust a few weeks ago following the [Rust CLI book][cli-book], which I'm pretty sure still referred to StructOpt at that time and has been updated to clap + derive since then (?). I encountered slightly odd behavior and looked through the issues of both StructOpt and clap to see if it is documented somehwere, where I found mentions of the merge into clap and finally discovered clap v3's release notes. They even have a short migration guide! :+1:

Best regards and thanks for all your effort from a happy user! 

[cli-book]: https://rust-cli.github.io/book/tutorial/cli-args.html
[clap-v3]: https://github.com/clap-rs/clap/releases/tag/v3.0.0

**Comment by TeXitoi** [comment]
README updated, thanks.
