### ISSUE TITLE
consider swithching to clap v3

### ISSUE THREAD

**Issue by mrl5** [TeXitoi/structopt#528]
`ansi_term` is a direct dependency of `clap-2` and `ansi_term` is official unmaintained now: https://github.com/ogham/rust-ansi-term/issues/72 - because of this it `cargo audit` started reporting it

the impact is only `cargo audit` message. if someone uses `cargo audit` as a github actions then issues like https://github.com/mrl5/vulner/issues/59 are beeing reported by `github-actions` bot

if it's not a big effort kindly consider switching to `clap-3` because they don't use `ansi_term` there

**Comment by TeXitoi** [comment]
Clap v3 provides clap derive that is a port of structopt to clap v3.

Migrating to clap v3 would be a breaking change.

So, if you want to migrate, clap v3 provide all that you need already.

**Comment by mrl5** [comment]
thank you @TeXitoi  :)
