### ISSUE TITLE
Is it possible to give the user a hint for the required argument type? 

### ISSUE THREAD

**Issue by antonylsg** [TeXitoi/structopt#53]
I was wondering if it would be possible to stringify the `FieldType` (see below). In order to give the user a hint for the expected type of the required argument, by using the [value_name](https://docs.rs/clap/2.29.2/clap/struct.Arg.html#method.value_name) method?

```rust
#[derive(StructOpt)]
struct Opt {
    #[structopt(short = "f", long  = "field")]
    field: FieldType,
}
```

In order to have the following output for the command `myapp --help`:

```
USAGE:
    myapp --field <FieldType>
```

**Comment by TeXitoi** [comment]
```rust
#[derive(StructOpt)]
struct Opt {
    #[structopt(short = "f", long  = "field", value_name = "FieldType")]
    field: FieldType,
}
```
I don't think that's a good idea to do that automatically because you will have some strange things as `PathBuf` instead of `FILE` for example.

**Comment by TeXitoi** [comment]
Basically, you can call any clap method that take `&str`, and every clap method using the `_raw` feature.
