### ISSUE TITLE
Documentation insufficient for a beginner

### ISSUE THREAD

**Issue by focusaurus** [TeXitoi/structopt#54]
I was unable to use this crate based on the docs in the README.

- Text says put 2 crates in my cargo but example only shows 1. This is confusing and requires me to research/experiment to figure out what is true.
- As a beginner an unqualified `#[macro_use]` is frightening. What is that going to bring in? I ended up doing the following but I have never seen macro_use bring in a binding that did not require `trailing_bang!` syntax.
- The combination of code I actually needed to get this to compile is not anywhere in the documentation. Here's what I ended up with after trial and error.

```rust
#[macro_use(StructOpt)]
extern crate structopt_derive;
use structopt::StructOpt;
```

**Comment by TeXitoi** [comment]
1. the readme does refere to the next 0.2 version that is not yet published on crates.io, you can read the corresponding README on crates.io.
2. `#[macro_use]` will export the `#[derive(StructOpt)]`
3. https://crates.io/crates/structopt

**Comment by focusaurus** [comment]
Ah I see. Yes the docs on crates.io are better at the moment.

**Comment by TeXitoi** [comment]
Sorry for the disturbing doc. I hope to publish 0.2 soon.
