### ISSUE TITLE
Clap examples with custom derive

### ISSUE THREAD

**Issue by fabiensanglard** [TeXitoi/structopt#540]
This repo (`structopt`) has plenty of excellent examples using custom derive notation. I checked out `clap` but there is very little there. It seems it is mostly using the builder.

Any plans to convert all the cool examples here into `clap` repo?

**Comment by epage** [comment]
FYI this would be more appropriate on clap's repe where the derive code lives.

We have a lot of examples
- https://docs.rs/clap/latest/clap/_derive/_tutorial/chapter_0/index.html
- https://docs.rs/clap/latest/clap/_derive/_cookbook/index.html

We are missing some cookbook entries on the derive side but are open to people porting them.

**Comment by fabiensanglard** [comment]
Thank you!
