### ISSUE TITLE
A special flag should make required options optional

### ISSUE THREAD

**Issue by kedeggel** [TeXitoi/structopt#57]
I have the use case that I want to offer an interactive mode that should be activated with `-i |--interactive`.
Currently my program has two required arguments, but I want to make them optional when interactive mode is set, so the user would be asked for them in the interactive mode step by step.
Is there a possibility to do this in the current version?
If not, would you please add this functionality?

**Comment by TeXitoi** [comment]
This kind of feature is not on structopt perimeter, but clap's.

You should be interested by https://docs.rs/clap/2.29.4/clap/struct.Arg.html#method.required_unless i.e. using structopt, something like that:
```rust
#[structopt(short = "i", long = "interactive")]
interactive: bool,
#[structopt(short = "f", long = "input-file", parse(from_os_str), required_unless = "interactive")]
input_file: PathBuf,
```

Does it answer your question?

**Comment by kedeggel** [comment]
Yes, that's exactly what I was looking for. Thanks
