### ISSUE TITLE
Help text not shown in subcommand summary

### ISSUE THREAD

**Issue by andor44** [TeXitoi/structopt#60]
I have something that looks like this:

```rust
#[derive(StructOpt, Debug)]
#[structopt(name = "foo", about = "bar")]
struct Config {
    // a couple fields for common options, their `help` works fine
    // ...

    #[structopt(subcommand)]
    subcommand: Subcommand,
}

#[derive(StructOpt, Debug)]
enum Subcommand {
    #[structopt(name = "foo", help = "Do foo")]
    Foo,
    #[structopt(name = "bar", help = "Do bar")]
    Bar,
    #[structopt(name = "baz", help = "Do baz")]
    Baz {
        #[structopt(subcommand)]
        some_subsubcommand: SubSubcommand,
    }
}
```

```
$ cargo run -- help
...
SUBCOMMANDS:
    bar
    baz
    foo
    help                  Prints this message or the help of the given subcommand(s)
```

When I invoke the automatically generated `help`, my subcommands show up, but only `help`'s short help will be shown, my subcommands' will not. `help <subcommand>` does show the help though. I think it would make sense to show the help description in the subcommands summary too.

**Comment by TeXitoi** [comment]
Looking at https://docs.rs/clap/2.29.4/clap/struct.SubCommand.html I think you want to use `about` instead of `help` on `enum Subcommand`:
```rust
enum Subcommand {
    #[structopt(name = "foo", about = "Do foo")]
    Foo,
    #[structopt(name = "bar", about = "Do bar")]
    Bar,
    #[structopt(name = "baz", about = "Do baz")]
    Baz {
        #[structopt(subcommand)]
        some_subsubcommand: SubSubcommand,
    }
}
```

Does it fix your problem?

**Comment by andor44** [comment]
Ahh, that is exactly what I'm looking for! I had only seen it used for the whole-program/top level object in the docs of `structopt` itself so it hasn't occurred to me it is valid for subcommands too.
