### ISSUE TITLE
Support for PathBuf (or Path?)

### ISSUE THREAD

**Issue by spease** [TeXitoi/structopt#63]
Something I've wished for a few times, as it would make code slightly cleaner, and I believe it would be technically more correct (eg if the command argument really is non-UTF8). Filepaths are a pretty common argument to CLI applications in my experience.

I could also see std::fs::File being used for higher-level file handling as well:
https://docs.python.org/3/library/argparse.html#filetype-objects

I haven't had the chance to try out the newest release, so if this has already been addressed, feel free to close this.

**Comment by TeXitoi** [comment]
From the README:
```rust
    /// Output file
    #[structopt(short = "o", long = "output", parse(from_os_str))]
    output: PathBuf,
```

It works since v0.1.4

**Comment by spease** [comment]
Thanks, that will come in handy. That being said, it would be more intuitive / discoverable / easier to remember if you could just specify PathBuf. I'm guessing this would require defining an extra trait for those types, or having a default based on a likely-to-be-impled-trait (eg From<OsString> or FromStr).

**Comment by TeXitoi** [comment]
You can't do that cleanly as custom derive gives you the code before typing. Thus you can't discover if a type implement a trait.

And I'm not found of magical heuristic that will change the parser looking at the string of the type. I prefer predictable code generation. It may bit a bit less easy, but I prefer it like that.

**Comment by spease** [comment]
Follow-up question - is there a way to parse IpAddr? I tried from_str, but IpAddr only implements FromStr, not From<&str>.

**Comment by TeXitoi** [comment]
FromStr is used by default. Thus it works without parse or with `parse(try_from_str)`
