### ISSUE TITLE
Example of enumeration whose names need to be changed

### ISSUE THREAD

**Issue by spease** [TeXitoi/structopt#67]
Is there a proper / good way to do this with the arg_enum! macro? Thanks.

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/structopt/blob/master/examples/enum_in_args.rs
https://github.com/TeXitoi/structopt/issues/42

Does it answers your question?

**Comment by spease** [comment]
No, I want a command line name for an enumeration value like “5g” but since this isn’t a valid identifier for an enumeration value, I was wondering if there’s a way to pass a rename attribute with the macro.

**Comment by TeXitoi** [comment]
My bad, I've not read the title.

Looks like it's not possible with clap's arg_enum. you have in #42 an example with serde and an example with strum that allow this feature. That's a bit boilerplate or not really feature complete, but it may fix your problem.

**Comment by TeXitoi** [comment]
You can also to it by hand using `parse(try_from_str = "my_convertion_function")`.

**Comment by TeXitoi** [comment]
Does it answer your question?

**Comment by spease** [comment]
Sort of. This is another case where it's painful to write a lot of boilerplate code each time this comes up. Is clap a more appropriate library for a better implementation?

**Comment by TeXitoi** [comment]
Long term solution would be to do the feature request (or the contribution) to https://github.com/kbknapp/clap_derive

**Comment by TeXitoi** [comment]
short term, maybe just asking strum to add a method to get a `&'static [&'static str]` of the enums for easy usage with clap/structopt.
