### ISSUE TITLE
Infer display order based on a layout of structs and enums

### ISSUE THREAD

**Issue by zummenix** [TeXitoi/structopt#70]
`clap` has an option `display_order` to change order of subcommands and arguments when showing a help message. It would be cool if `structopt` has ability to infer this information from a layout of structs and enums. For now I use `raw(display_order = "1")` which is pretty annoying :)

P.S.: if you're interested here is a PR moving from `clap` to `structopt`: https://github.com/zummenix/mprovision/pull/21
I'm happy with the result, thank you for the crate!

**Comment by birkenfeld** [comment]
Wouldn't that be done by using `#[structopt(raw(global_settings="&[AppSettings::DeriveDisplayOrder]"))]`?

**Comment by TeXitoi** [comment]
You're right. Thanks.
