### ISSUE TITLE
FTBFS on RHEL-7 with rustc 1.24.0

### ISSUE THREAD

**Issue by mcepl** [TeXitoi/structopt#73]
I was trying to build [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/) by @autozimu and failed (see autozimu/LanguageClient-neovim#315 ), but by looking at the issue with fresh eyes, it seems to me that actual problem is with ``structopt-derive``, isn't it?

**Comment by TeXitoi** [comment]
Looks like you have a bad cache. You have 2 versions of std, as if you have the one of 1.24 and 1.23.

**Comment by mcepl** [comment]
So, what should I do? ``rm -rf ~/.cargo`` seems a bit excessive

**Comment by TeXitoi** [comment]
`rm -fr target` ?

**Comment by mcepl** [comment]
hmm, that didn't help much. Now it failed somewhere else:
```
Compiling synstructure v0.6.1
error[E0523]: found two different crates with name `std` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
   --> /home/matej/.cargo/registry/src/github.com-1ecc6299db9ec823/synstructure-0.6.1/src/lib.rs:137:1
    |
137 | extern crate proc_macro;
    | ^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `synstructure`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [check] Error 101
matej@mitmanek: LanguageClient (next)$
```

**Comment by TeXitoi** [comment]
```
which rustc
rustc --version
which cargo
cargo --version
```

I suspect you have a messed up rust installation. You may try

```
rustup self update
rustup update
```

**Comment by mcepl** [comment]
Ah, got it, https://bugzilla.redhat.com/show_bug.cgi?id=1546541 (or rust-lang/rust#48319)

**Comment by TeXitoi** [comment]
Yeah, looks relevant.

**Comment by mcepl** [comment]
It does, it fixed it for me.
