### ISSUE TITLE
Share flags between subcommands

### ISSUE THREAD

**Issue by gnzlbg** [TeXitoi/structopt#75]
Is there a way to share flags between subcommands? From the docs, it looks like there might be a way to do this, but it is not clear to me how this is done. For example, given

```rust
struct Shared {
    shared: bool
}

struct B {
    a: bool
}

struct B {
    b: bool
}

enum Options {
    A(A),
    A(B),
}
```

Is it possible to have the subcommands A and B share the flags in `Shared` so that one can do:

```shell
app A --a --shared
app B --b --shared
```

?

**Comment by TeXitoi** [comment]
I think you want #21 If that's what you want, no, that's not possible yet.

**Comment by gnzlbg** [comment]
Yes, that looks like what I wanted. At the end I ended up duplicating the flags. It didn't turn too bad either. Thanks for working on this library. It's the best cli option parsing API i've used (better than docopt).
