### ISSUE TITLE
Feature request: ignore unspecified arguments

### ISSUE THREAD

**Issue by m4b** [TeXitoi/structopt#8]
This is a somewhat unusual request so if this isn't in your immediate plans, or ever, feel free to close. But I would be very happy to see it. 

But the gist is I'd like to be able to have a sort of "non strictness mode" perhaps configured via builder, etc., which ignores any arguments which aren't spec'd by the argument struct.

Reason: I'm writing a tool that is a drop in replacement for another tool, and I want it to not die when it receives an argument it doesn't understand. This will allow me to incrementally implement certain features or choose to die on some flags (by implementing them), etc. 

Is this something that's possible ?

Regardless awesome crate, already using it [here](https://github.com/m4b/bingrep), was painless to covert from basic toy arg iterator, I think you've got one of the nicest arg crates around at this point :) :thumbsup:

**Comment by TeXitoi** [comment]
I don't parse command line, I just forward all that to https://crates.io/crates/clap and I can't find this feature in clap.

Maybe a workaround is to get the generated clap object, add the arguments you want to ignore, and then parse. Something like that (not tested)

```rust
#[derive(StructOpt, PartialEq, Debug)]
struct Opt {
    #[structopt(short = "d", long = "debug")]
    debug: bool,
}
let app = Opt::clap().arg(Arg::with_name("v").short("v".long("verbose").help("Not implemented"));
let opt = Opt::from_clap(app.get_matches());
```

And thanks for the feedback!
