### ISSUE TITLE
default_value confuses bool flags

### ISSUE THREAD

**Issue by vorner** [TeXitoi/structopt#80]
Hello

If I have a bool flag and set `default_value = "false"`, it defaults to true. Even though it works if I don't set any default value, this is a bit confusing:

```rust
#[macro_use]
extern crate structopt;

use structopt::StructOpt;

#[derive(Debug, StructOpt)]
struct Opts {
    /// Flag that is always true even when not set explicitly.
    #[structopt(short = "f", long = "flag", default_value = "false")]
    flag: bool,
}

fn main() {
    println!("{:?}", Opts::from_args());
}
```

This prints (if I don't pass any arguments at all):

```
Opts { flag: true }
```

I'd suggest to this either work as expected (eg. defaulting to false) or erroring,

This is structopt 0.2.5.

**Comment by TeXitoi** [comment]
It can't work as expected. Erroring in this case seems a good thing. We should look at others methods that are meaningless with book, as `env`
