### ISSUE TITLE
Option to omit --version flag

### ISSUE THREAD

**Issue by mfarrugi** [TeXitoi/structopt#81]
Looks like by default, and when set to "" the --version flag is still prompted.

This is noisy if there are few parameters, and it would be good if it could be omitted.

**Comment by TeXitoi** [comment]
Ha, you want to remove the --version flag? 

You want to use 

https://docs.rs/clap/2.31.1/clap/enum.AppSettings.html#variant.DisableVersion

See 

https://github.com/TeXitoi/structopt/blob/master/examples/raw_attributes.rs

For an example usine settings.

Dotés it solve your issue?

**Comment by TeXitoi** [comment]
Example:  https://github.com/TeXitoi/structopt/blob/master/examples/no_version.rs

**Comment by mfarrugi** [comment]
Yes, thank you!

I would make the argument that this should be the default when no version string is passed, but this is simple enough.

**Comment by TeXitoi** [comment]
That would be a feature request for clap I think.
