### ISSUE TITLE
Include example of `main` in docs

### ISSUE THREAD

**Issue by luser** [TeXitoi/structopt#82]
I'm looking at using structopt for the first time and I was reading the docs on docs.rs. I noticed that they don't seem to include an example of actually parsing the commandline into the args struct, though! Looking at the example in the README does include this, which makes things much clearer:
```rust
fn main() {
    let opt = Opt::from_args();
    println!("{:?}", opt);
}
```

I think the example in the crate-level docs should include this as well!

**Comment by luser** [comment]
Thanks!

**Comment by TeXitoi** [comment]
Thanks for your feedback.
