### ISSUE TITLE
Set minimum number of entries to a Vec argument

### ISSUE THREAD

**Issue by liamdawson** [TeXitoi/structopt#84]
Say I have a structopt argument:

```
        #[structopt(name = "foos")]
        foos: Vec<String>,
```

I can't seem to find a way to pass a requirement to clap saying that _at least_ one value is required, and running the app without passing any values is considered a successful run.

How can I make it mandatory to pass at least one value to `foos`?

**Comment by TeXitoi** [comment]
you want https://docs.rs/clap/2.31.1/clap/struct.Arg.html#method.required so something like that:
```rust
#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(raw(required = "true"))]
    foos: Vec<String>,
}
```

You might also be interested by https://docs.rs/clap/2.31.1/clap/struct.Arg.html#method.min_values you can find a complete example at https://github.com/TeXitoi/structopt/blob/master/examples/at_least_two.rs

Does it answer your question?

**Comment by liamdawson** [comment]
Yes, that works well, thank you. 👍

**Comment by clbarnes** [comment]
For anyone coming across this in future, I believe the correct way to do it now is

```rust
#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(required = true)]
    foos: Vec<String>,
}
```

**Comment by vallentin** [comment]
To add to @clbarnes update, if you're searching for a way to require a "minimum number of entries" as the title suggested, then you can use `min_values = ...`.

```rust
#[derive(StructOpt, Debug)]
struct Opt {
    // #[structopt(required = true, min_values = 2)]
    // same as
    #[structopt(min_values = 2)]
    foos: Vec<String>,
}
```

If `min_values` is used, then `required` is implied. However specifying both is perfectly valid.

**Comment by WiSaGaN** [comment]
> To add to @clbarnes update, if you're searching for a way to require a "minimum number of entries" as the title suggested, then you can use `min_values = ...`.
> 
> ```rust
> #[derive(StructOpt, Debug)]
> struct Opt {
>     // #[structopt(required = true, min_values = 2)]
>     // same as
>     #[structopt(min_values = 2)]
>     foos: Vec<String>,
> }
> ```
> 
> If `min_values` is used, then `required` is implied. However specifying both is perfectly valid.

I tried to use only `min_values`, it still runs successfully when the arg is NOT specified. In this case we do need specify `required = true` explicitly.

**Comment by nicmr** [comment]
For anybody coming here from a search engine trying to find out how to do the same with `clap` v3+, now that `structopt` has been integrated into clap:
`min_values` does not exist directly on the `clap::Arg` type, but you can achieve the same behaviour using `num_args` with a range instead.

```rust
use clap::{Parser};
#[derive(Parser, Debug)]
struct Opt {
    #[arg(required=true, num_args=1..)]
    foos: Vec<String>,
}
```

**Comment by DavidAntliff** [comment]
> you can achieve the same behaviour using `num_args` with a range instead.

Note that `required = true` is also necessary (as shown), otherwise _no_ items is also allowed.
