### ISSUE TITLE
Improve help for subcommands

### ISSUE THREAD

**Issue by meven** [TeXitoi/structopt#86]
Given

```
#[derive(StructOpt, Debug)]
#[structopt(name = "test subcommand")]
enum Opt {
    #[structopt(name = "test", help = "do something")]
    AddonGroup {
        #[structopt(help = "Description of the parameter")] id: u16,
    },
}
```

Currently the help output renders this as
```
SUBCOMMANDS:
    test
```
I would expect this to be :
```
SUBCOMMANDS:
    test      do something
```

Furthermore `cargo run help test`
Outputs
````do something```
I would expect a description of this sub-command parameters as well.

Great lib :)

I could be a clap issue. I haven't made the research.

**Comment by TeXitoi** [comment]
Use `about` instead of `help`

**Comment by TeXitoi** [comment]
For reference:
 * https://docs.rs/clap/2.31.2/clap/struct.App.html#method.about
 * https://docs.rs/clap/2.31.2/clap/struct.App.html#method.help

Yo can also use doc comments that will do the right thing:
```rust
#[derive(StructOpt, Debug)]
#[structopt(name = "test subcommand")]
enum Opt {
    /// do something
    #[structopt(name = "test")]
    AddonGroup {
        /// Description of the paramater
        addon_group_id: u16,
    },
}
```

**Comment by meven** [comment]
Thanks !
