### ISSUE TITLE
`FromStr::Err` does not implement `Error`

### ISSUE THREAD

**Issue by JustAPerson** [TeXitoi/structopt#9]
Hi,

It appears StructOpt wrongly assumes that it can use the `Error::description()` method when converting a string to another object. The [definition](https://doc.rust-lang.org/nightly/std/str/trait.FromStr.html) of `FromStr` has no such bound.

```rust
use std;

#[derive(Debug, StructOpt)]
#[structopt(name="foo", about="bar")]
pub struct CliConfig {
    #[structopt(long="print")]
    print: Print,
}

#[derive(Debug)]
enum Print {
    Pretty,
    Ast,
}
impl std::str::FromStr for Print {
    type Err = ();
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "pretty" => Ok(Print::Pretty),
            "ast" => Ok(Print::Ast),
            _ => Err(()),
        }
    }
}
```
```
error: no method named `description` found for type `()` in the current scope
 --> src/cli.rs:3:17
  |
3 | #[derive(Debug, StructOpt)]
  |                 ^^^^^^^^^
```

In addition, maybe StructOpt could implement a basic `#[derive]` trait for enums?

**Comment by TeXitoi** [comment]
But how can I print an error message? The planned evolution was to give a custom parser that can do the parsing and the error message if you can't use a `FromStr` with an `Err: Error`: https://github.com/TeXitoi/structopt/issues/3

I'll clarify in the doc that the type must be `FromStr<Err: std::error::Error>`.

For the auto derive `FromStr` for enums without data, that's a great idea, but I should be done in another crate as it can be interesting for other cases.
