### ISSUE TITLE
How to implement group?

### ISSUE THREAD

**Issue by manfredlotz** [TeXitoi/structopt#95]
clap allows to specify a group where, for example, one (and only one) argument from that group must be present at runtime.

How would I do it in structop?

**Comment by TeXitoi** [comment]
As an example is better that a long talk: https://github.com/TeXitoi/structopt/blob/master/examples/group.rs

Does it fix your use case?

**Comment by manfredlotz** [comment]
> Does it fix your use case?
Yes, great. 

Sorry, that I was not able to figure it out from the documentation.

**Comment by TeXitoi** [comment]
You then must change the `group = "vers" ` to `group = "blabla" `

**Comment by manfredlotz** [comment]
I also I had to.
 
But I didn't change the group = "vers" to "blabla" and your sample worked anyway.

**Comment by TeXitoi** [comment]
I'm not sure I understand correctly. If your problem is solved, please close the issue, else, feel free to ask a question.

**Comment by manfredlotz** [comment]
I try to understand the code in your example.

You say: when I change "vers" to "blabla" in function `vers_arg_group()` I have to change it as well in 
`group = "vers"`

I ask: why does the code work when change "vers" to "blabla" in function `vers_arg_group()` but do not change it in `group = "vers"???

**Comment by TeXitoi** [comment]
Does it really work? I suspect you have the only one constraint because the args are in a group, bit you lost the required constraint, ie you can call the command without args. Sorry, on mobile, can't test.

**Comment by manfredlotz** [comment]
Well, I get this when changing only thas one line in `vers_arg_group()`

```
% ./target/debug/sotest --major  --set-ver 1
error: The argument '--major' cannot be used with one or more of the other specified arguments

USAGE:
    sotest <> <--set-ver <set_ver>|--major|--minor|--patch>

For more information try --help
```

or

```
 % ./target/debug/sotest --minor  --major                  :(
error: The argument '--minor' cannot be used with one or more of the other specified arguments

USAGE:
    sotest <> <--set-ver <set_ver>|--major|--minor|--patch>

For more information try --help
```

Perhaps I overlooked a case where it doesn't work.

**Comment by TeXitoi** [comment]
Your 4 args are still in the same group, named vers, that is created implicitly. Thus, you can use at most one of them. But you can use none, as the required constraint is done on the blabla group, not the vers group.

**Comment by manfredlotz** [comment]
Aah, I think I got it.

If I call `./target/debug/sotest` without parameter then I should get

```
error: The following required arguments were not provided:
    <--set-ver <set_ver>|--major|--minor|--patch>

USAGE:
    sotest [OPTIONS] <--set-ver <set_ver>|--major|--minor|--patch>

For more information try --help
```
but in the "blabla" case I get:

```
./target/debug/sotest                                   :(
error: The following required arguments were not provided:
    <>

USAGE:
    sotest [FLAGS] [OPTIONS] <>

For more information try --help
```

Thanks a lot for your patience but I needed to understand.

**Comment by manfredlotz** [comment]
One last point. 

If I just want to make sure I use **at most** one argument of a group I could just leave out the `vers_arg_group()` function and  the statement `#[structopt(raw(group = "vers_arg_group()"))]`

**Comment by TeXitoi** [comment]
Yes exactly, you don't need that.
