### ISSUE TITLE
Use variable for help?

### ISSUE THREAD

**Issue by polarathene** [TeXitoi/structopt#97]
A C project I am porting formats it's help with some options displaying the `current` value. These may be the default or active/current value set.  For example by default the `-x` and `-y` options help prints:

```
  -x XPOS   Initial window X position [current: center]
  -y YPOS   Initial window Y position [current: center]
```

The numeric values appeared when `-x` was set to 200 in addition to calling `-h`. the values could also come from a config file before CLI args are considered for overriding. 

```
  -x XPOS   Initial window X position [current: 200]
  -y YPOS   Initial window Y position [current: 0]
```

In clap the `.help(value)` method can take a formatted string into the arg builder. AFAIK that isn't possible with the way structopt works? Would there be a post-process way to inject/alter properties like this?(perhaps it's suitable for the integration of structopt when merged into clap?)

**Comment by TeXitoi** [comment]
using the raw feature, you can do whatever you want, but you can't access to the local variables. As a workaround, you can use static and/or `lazy_static`s.

You can also get the `clap::App` object by calling `Opt::clap()`, to some custom modifications, and then `Opt::from_clap(app)`, but I don't think you can modify the help of an arg.
